### ISSUE TITLE
BFA Season 4 sets are not showing

### ISSUE THREAD

**Issue by bartoszkonarski** [SLOKnightfall/BetterWardrobe#111]
There are no BFA S4 sets (both raid and pvp) shown in the extended sets list:
![image](https://user-images.githubusercontent.com/25281430/97766660-b92f1380-1b17-11eb-804a-d16be2454469.png)
![image](https://user-images.githubusercontent.com/25281430/97766650-a4528000-1b17-11eb-9721-8b8943cb204c.png)

**Comment by SLOKnightfall** [comment]
Added to the DB
