### ISSUE TITLE
Missing Pre-patch sets

### ISSUE THREAD

**Issue by lifebound** [SLOKnightfall/BetterWardrobe#115]
Argent Conscipt's Plate, Argent Conscipt's Mail, Argent Conscipt's Leathers, and Argent Conscipt's Cloth are all-non set Blue collections available only during the pre-patch, but are not listed in the 'Extras' tab. I tried to add it myself, but found no documentation on how to add it to the appropriate LUAs.

**Comment by SLOKnightfall** [comment]
Added in next release
