### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by the-quality** [SLOKnightfall/BetterWardrobe#117]
`6x ...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1014: attempt to index local 'module' (a nil value)
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1014: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1011>

Locals:
self = <unnamed> {
 0 = <userdata>
 SetCollapsed = <function> defined @Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:997
 SetAtlases = <function> defined @Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:974
 buttonType = "module"
 OnLoad = <function> defined @Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:969
}
module = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 SetCollapsed = <function> defined @Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:997
 SetAtlases = <function> defined @Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:974
 buttonType = "module"
 OnLoad = <function> defined @Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:969
}
(*temporary) = nil
(*temporary) = 44916
(*temporary) = nil
(*temporary) = "attempt to index local 'module' (a nil value)"
`

**Comment by SLOKnightfall** [comment]
Error does not have anything to do with addon
