### ISSUE TITLE
MogIt Preview from Collection (Ctrl+rightclick) not working when BW is enabled

### ISSUE THREAD

**Issue by chasaya** [SLOKnightfall/BetterWardrobe#132]
When using MogIt, ctrl-rightclicking an item in the Appearance collection will add that item to the MogIt preview window. When I have BetterWardrobe enabled as well, this doesn't work anymore (ctrl-rightclicking does nothing at all it seems). 

This was working before (about 3-4 builds ago i think) with both addons enabled. It also works again when I disable BetterWardrobe, so I'm reporting it here (pls let me know in case this is a MogIt problem and I should rather report it there).

I still like to use MogIt for its Wishlist function and the combined item list/preview function to create outfits (when you add e.g. a head item in the preview and then browse other slot items, it will show combined in the item list), and I also like it for the "Sheathe weapon" function. Would it be possible to enable the ctrl+rightclick again to work like before? 
Thanks a lot for looking into it and for the great addon!

**Comment by SLOKnightfall** [comment]
Thanks for letting me know.  I had to redo a lot of the menus to stop the taint errors and I think that accidentally broke.  I'll get a fix out as soon as I can .

**Comment by SLOKnightfall** [comment]
Fixed in the next update
