### ISSUE TITLE
attempt to index field 'ScrollFrame' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [SLOKnightfall/BetterWardrobe#133]
Working on the Maldraxxus questline. Finished the quest In Death We Are Truly Tested which awarded a bunch of new weapon skins and received the following error. Thanks.

6x BetterWardrobe\BetterWardrobe-2.5.1.lua:1015: attempt to index field 'ScrollFrame' (a nil value)
[string "@BetterWardrobe\BetterWardrobe-2.5.1.lua"]:1015: in function `Refresh'
[string "@BetterWardrobe\BetterWardrobe-2.5.1.lua"]:934: in function `OnEvent'
[string "@BetterWardrobe\Core.lua"]:1221: in function <BetterWardrobe\Core.lua:1221>

Locals:
self = <table> {
 RefreshAppearanceTooltip = <function> defined @BetterWardrobe\BetterWardrobe.lua:1518
 ClearAppearanceTooltip = <function> defined @Blizzard_Collections\Blizzard_Wardrobe.lua:3650
 UpdateProgressBar = <function> defined @BetterWardrobe\BetterWardrobe.lua:1040
 OnSearchUpdate = <function> defined @BetterWardrobe\BetterWardrobe.lua:1262
 CanHandleKey = <function> defined @Blizzard_Collections\Blizzard_Wardrobe.lua:3656
 RefreshCameras = <function> defined @Blizzard_Collections\Blizzard_Wardrobe.lua:3533
 OnUnitModelChangedEvent = <function> defined @Blizzard_Collections\Blizzard_Wardrobe.lua:3519
 OpenVariantSetsDropDown = <function> defined @Blizzard_Collections\Blizzard_Wardrobe.lua:3546
 SelectSetFromButton = <function> defined @BetterWardrobe\BetterWardrobe.lua:1282
 SetItemFrameQuality = <function> defined @Blizzard_Collections\Blizzard_Wardrobe.lua:3496
 GetSelectedSavedSetID = <function> defined @BetterWardrobe\BetterWardrobe.lua:1289
 RefreshScrollList = <function> defined @BetterWardrobe\BetterWardrobe.lua:1272
 DisplaySavedSet = <function> defined @BetterWardrobe\BetterWardrobe.lua:1155
 OnShow = <function> defined @BetterWardrobe\BetterWardrobe.lua:805
 OnLoad = <function> defined @BetterWardrobe\BetterWardrobe.lua:792
 OnHide = <function> defined @BetterWardrobe\BetterWardrobe.lua:841
 ClearLatestSource = <function> defined @BetterWardrobe\BetterWardrobe.lua:1045
 SelectSet = <function> defined @BetterWardrobe\BetterWardrobe.lua:1310
 OnEvent = <function> defined @BetterWardrobe\BetterWardrobe.lua:882
 ScrollToSet = <function> defined @BetterWardrobe\BetterWardrobe.lua:2477
 HandleKey = <function> defined @BetterWardrobe\BetterWardrobe.lua:2439
 GetDefaultSetIDForBaseSet = <function> defined @Blizzard_Collections\Blizzard_Wardrobe.lua:3570
 SetAppearanceTooltip = <function> defined @BetterWardrobe\BetterWardrobe.lua:1327
 DisplaySet = <function> defined @BetterWardrobe\BetterWardrobe.lua:1066
 Refresh = <function> defined @BetterWardrobe\BetterWardrobe.lua:1014
 SelectSavedSet = <function> defined @BetterWardrobe\BetterWardrobe.lua:1322
 GetSelectedSetID = <function> defined @BetterWardrobe\BetterWardrobe.lua:1301
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'ScrollFrame' (a nil value)"

**Comment by SLOKnightfall** [comment]
Just encountered that myself and a new release that should fix it should be out shortly/.
