### ISSUE TITLE
Possible graphical conflict with Narcissus

### ISSUE THREAD

**Issue by Ookami313** [SLOKnightfall/BetterWardrobe#134]
Started using Better Wardrobe recently and I'm liking it so far. Thanks.
Requesting that the Dressing Room frame be made larger if possible as there seems to be a bug or graphical conflict when using both BetterWardrobe and Narcissus together. Currently the internal item slot boxes within the largest sized BetterWardrobe dressing room frame show at least 3 or 4 item slot boxes outside the main frame itself. 

![BetterWardrobe_edited](https://user-images.githubusercontent.com/26803942/100688787-1bff0f00-3351-11eb-969f-889d6eeb4d74.jpg)

This problem seems to stem from having both BetterWardrobe and Narcissus running at the same time, since if I disable Narcissus those item slot boxes go away, but if I disable BetterWardrobe and enable Narcissus, the dressing room frame is much larger and incorporates all the item slot boxes.

![BetterWardrobe-Narcissus](https://user-images.githubusercontent.com/26803942/100689780-2a4e2a80-3353-11eb-8727-da7f75916f6c.jpg)

Also, is there any way to increase the size of the appearance frame, or decrease the size of the Extras tab so that it does not overlap the number of collected appearances bar. It's a minor issue, just weirds me out when I see it. :)

Any way, thanks for all the hard work. Keep it up.

**Comment by SLOKnightfall** [comment]
Closing Ticket.  Looks like Narcisis added code to hide their buttons if BetterWardrobe is active.
