### ISSUE TITLE
No way to remove 'saved' outfits

### ISSUE THREAD

**Issue by lifebound** [SLOKnightfall/BetterWardrobe#136]
It is possible to save a transmog, but it is not possible to delete it. My intuition tells me the way to delete a saved outfit would be to r-click on the outfit from the Saved tab and select 'Remove' or 'Delete' or 'Forget this outfit', but there's nothing. Nor is there any procedure available in the drop downs.

**Comment by SLOKnightfall** [comment]
The sets shown in the Saved tab are just a snapshot of a character's saved sets and there is currently no way to delete sets from the tab.  To delete a set you need to log into the character and delete the set by clicking on the Rename/Delete button in the saved set dropdown in the dressing room or the transmog vendor.
