### ISSUE TITLE
No longer possible to load queued transmog sets?

### ISSUE THREAD

**Issue by lifebound** [SLOKnightfall/BetterWardrobe#137]
in the readme it says you can click a checkmark next to the 'Save' button at the transmog vendor to load a queued set. This does not appear to be there anymore. The code to queue a set does appear to be working still, so I'm assuming the button's removal is a bug.

**Comment by SLOKnightfall** [comment]
The button was changed to the  "Import/Export Options" gear icon button. Clicking that button will bring up a dropdown that has the option to load the set.  I'll update the readme to reflect the change.
