### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by lalanthe** [SLOKnightfall/BetterWardrobe#14]
In the xpac drop down 'Wrath of the Lich King' is misspelled as 'Wrath of the Litch Kink' (see screenshot)
![CleanShot 2020-09-08 at 20 00 33@2x](https://user-images.githubusercontent.com/70987689/92542564-afbbb600-f20e-11ea-9335-f9f3415a8742.png)

**Comment by SLOKnightfall** [comment]
Fixed in the next version.
