### ISSUE TITLE
PetTracker + BetterWardrobe addon compatibility bug

### ISSUE THREAD

**Issue by addonaddict** [SLOKnightfall/BetterWardrobe#147]
Issue left on PetTracker addon page as well:
https://github.com/Jaliborc/PetTracker/issues/255

![image](https://user-images.githubusercontent.com/73442541/103433602-efdde480-4bc1-11eb-901a-a388c64b384b.png)

Thanks

**Comment by SLOKnightfall** [comment]
Modified dropdown frame level so it is hidden when pettracker is shown
