### ISSUE TITLE
Bug: Doesn't Remember Artifact Weapon appearances

### ISSUE THREAD

**Issue by hsdragoo** [SLOKnightfall/BetterWardrobe#148]
When attempting to save a set with an artifact weapon appearance (I am not using the legion artifact tab) The weapon appearance doesn't save and is gone after logging out and back in.

I am not 100% sure but it seems this may be due to the many appearances having the same name. I do not know if this works the same when choosing the appearance from the legion artifact tab as I was using an appearance for a different spec than my own.

**Comment by SLOKnightfall** [comment]
Artifact skins are not saved due to code on Blizzard's end that ignores those skins when saving an appearance.

**Comment by SLOKnightfall** [comment]
Closing as it appears the 9.1 upadate allows for saving artifacts in mogs now.
