### ISSUE TITLE
Error when opening Appearances during combat

### ISSUE THREAD

**Issue by LudiusMaximus** [SLOKnightfall/BetterWardrobe#150]
When you open the Appearances during combat, you get "Interface action failed because of an AddOn" in the chat box.
Using BugSack/BugGrabber, you see that BetterWardrobe is calling a protected function. Could you please avoid this by checking InCombatLockdown()?

AddOn 'BetterWardrobe' tried to call the protected function 'CollectionsJournal:SetFrameLevel()'.
[string "@BetterWardrobe\BetterWardrobe-2.5.2.lua"]:2330: in function <BetterWardrobe\BetterWardrobe.lua:2321>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:504: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:670: in function `CollectionsJournal_LoadUI'
[string "@FrameXML\UIParent.lua"]:1089: in function `SetCollectionsJournalShown'
[string "@FrameXML\UIParent.lua"]:1083: in function `ToggleCollectionsJournal'
[string "TOGGLECOLLECTIONSWARDROBE"]:1: in function <[string "TOGGLECOLLECTIONSWARDROBE"]:1>

**Comment by SLOKnightfall** [comment]
Fixed in next update
