### ISSUE TITLE
Lookalike Sets Missing from Appearances -> Extra

### ISSUE THREAD

**Issue by nomicide** [SLOKnightfall/BetterWardrobe#151]
Since today's update, the Lookalike sets are no longer appearing in Appearances -> Extra
I rolled back to 2.5.2, and they returned.
I tried to go through all the settings in case I was missing something, but I didn't see anything special. I tried browsing through unavailable sets, but those only showed the true class-only sets. A lot of these sets are recolors that are available to all leather wearers.

Examples:
  Chi'Ji's Battlegear (Mythic Lookalike)
  Fanged Slayer's Armor (Mythic Lookalike)
  Vestments of the Dark Phoenix (Heroic Lookalike)

**Comment by SLOKnightfall** [comment]
All the "Lookalike" sets were removed as a vast majority of them are really just the same items as the regular class set.  You can see all class sets by unchecking the Class Sets Only option in the filter menu and selecting one at the transmog vendor will populate it with any appearances that the character can use.
