### ISSUE TITLE
Sets not showing up, weapon not appearing, etc

### ISSUE THREAD

**Issue by jsaue003** [SLOKnightfall/BetterWardrobe#153]
Here is some feedback on this addon and issues I've had with it so far

- Weapon is hidden by default under the options menu for the dressing room. Makes no sense why this is a default option. People should select it themselves if they want it
- Half the time when you collect an appearance set item, you open the pane to check the set, the entire armor set doesn't show up in the preview but it shows your character literally naked. You have to close it, then reopen it again to see the set pieces
- It doesn't remember your choices for filters. Incredibly irritating. If I'm collecting Legion pieces, it's such a hassle to open window 50+ times and have to filter everything out I don't care about/dont want to see.

**Comment by SLOKnightfall** [comment]
These issues should be fixed in the next release.
