### ISSUE TITLE
Mythic Items Revert to normal versions of said item.

### ISSUE THREAD

**Issue by SyhrDRFC** [SLOKnightfall/BetterWardrobe#156]
Hi, not sure if this has been reported, i am however reporting mine for possible extra infomation. Not reported an addon bug before so if there is any config file you'd like me to send, let me know.

as you can see in the attached image, on the right it the set i am trying to save, on the left is the set that BW reverts to when i close the window. 

This is not stoping me using the addon however it is a big inconvenience

![BW](https://user-images.githubusercontent.com/79803963/109427418-3eed9d80-79ea-11eb-9f69-9103dfcf4078.PNG)

**Comment by Architekt909** [comment]
I'm having this same issue. Kind of makes the addon not useful to me as when I look at my list I get confused at why the wrong items are showing up in the list. Surprised it's been an issue for this long. Here's some more screen shots showing an easy example on my priest to reproduce. Now I know why all the wrong items are showing up.

Mythic item added:
<img width="605" alt="mythic_selected" src="https://user-images.githubusercontent.com/3301620/116485689-cd9b6100-a859-11eb-88ab-33a875b140ae.png">

Normal showing:
<img width="612" alt="normal item" src="https://user-images.githubusercontent.com/3301620/116485591-988f0e80-a859-11eb-883d-7f223c01cecf.png">

Normal showing 2:
<img width="602" alt="normal item 2" src="https://user-images.githubusercontent.com/3301620/116485596-9b89ff00-a859-11eb-9bd8-79a179504670.png">

**Comment by Architekt909** [comment]
I think I found and fixed the bug. Currently in file BetterWardobe\Modules\CollectionList.lua on line 146 it says this:

`local visualID = C_TransmogCollection.GetItemInfo(sourceInfo.itemID, itemModID)--(type == "set" and sourceInfo.visualID) or addon.GetItemSource(sourceID, setInfo.mod)`

I did some print debugging and noticed that first of all itemModID was always nil, and according to the WOW API, that method if you pass in nil (which it is) looks like it will just default to normal. If you look at [https://wowpedia.fandom.com/wiki/API_C_TransmogCollection.GetSourceInfo](url), which is called right before that line, you can see that one of the fields in the returned table is itemModID. This value is what specifies normal, LFR, mythic, heroic, etc. 

So I changed line 146 to be this instead and it started working for me:
`local visualID = C_TransmogCollection.GetItemInfo(sourceInfo.itemID, itemModID or sourceInfo.itemModID)`

Not sure if there's any other ramifications to that change, but I was able to get the right transmog to appear for all instance difficulty types by making that one edit. Hopefully the author will read this and can incorporate it into the next release. For now, try making that edit yourself.
