### ISSUE TITLE
Delete saved characters sets

### ISSUE THREAD

**Issue by Ashbringer905** [SLOKnightfall/BetterWardrobe#162]
Hello, My problem is that in the section "Saved" I have too much characters liste, but several of them are deleted characters, so I'm asking how to delete characters names appearing in that list ? I'm done spending half an hour to find just 1 name ...

**Comment by SLOKnightfall** [comment]
When I checked the addon to write up instructions I found that the page that has the character listings so you can delete them got accidentally removed when I redid the options.  I'm finishing up an update that should be out in a couple of days and will make sure to get that page showing up again.

**Comment by Ashbringer905** [comment]
Thank you, your addon is incredible by the way, a traduction (in french in my case) would be very appreciated when you will have some time.

**Comment by SLOKnightfall** [comment]
The option page to remove saved sets from the dropdown has been fixed in the v2.9
