### ISSUE TITLE
Please add the ability to import from the Transmog Outfits addon

### ISSUE THREAD

**Issue by Ketrel** [SLOKnightfall/BetterWardrobe#165]
There was another addon that worked very similarly to yours: https://www.curseforge.com/wow/addons/transmog-outfits

I've been looking to switch, but as all my outfits are stored in that one for all my toons, it would be a LOT easier to make the switch if your addon had some sort of way to import from that addon.

**Comment by SLOKnightfall** [comment]
Added in the next update.  The TransmogOutfits UI is now hidden but all the sets are shown with the saved sets.  The sets will have the abiltiy to be renamed, deleted or create a copy in BetterWardrobe
