### ISSUE TITLE
erroneous or missing listings for shadowlands raid/pvp gear

### ISSUE THREAD

**Issue by medecinqui** [SLOKnightfall/BetterWardrobe#167]
This is a fresh install of the addon, with the defaults.
In the "Extra" tab:

On my rogue char:
The cloth pvp gladiator gear shows up.

On both my rogue and paladin char:
Sinful Gladiator (Elite) doesn't show up
Only the normal castle nathria gear shows up - not heroic or mythic

an aside: thanks for the addon! Even with these minor issues, it's really useful!

![image](https://user-images.githubusercontent.com/3878365/119613164-8d27f800-bdb1-11eb-93c2-c2428fb64556.png)
![image](https://user-images.githubusercontent.com/3878365/119613337-c2344a80-bdb1-11eb-9ff2-64ac1e1c7980.png)

**Comment by SLOKnightfall** [comment]
Should be fixed now
