### ISSUE TITLE
local isDressableItem = C_Item.IsDressableItemByID(itemInfo)

### ISSUE THREAD

**Issue by Ookami313** [SLOKnightfall/BetterWardrobe#168]
Updated to 3.0 alpha. No issues that I can tell, but then ran into the following error when I was leveling my characters profession. Each time I mouse over a crafting reagent in a recipe, the following error occurs. I started with Jewelcrafting reagents, but also moused over reagents in my cooking list and the same error occurred. Thanks.

17x Usage: local isDressableItem = C_Item.IsDressableItemByID(itemInfo)
[string "=[C]"]: ?
[string "@BetterWardrobe\Modules\Tooltips.lua"]:241: in function `ShowTooltip'
[string "@BetterWardrobe\Modules\Tooltips.lua"]:75: in function <BetterWardrobe\Modules\Tooltips.lua:73>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Vendor\sys\hook.lua"]:54: in function <Vendor\sys\hook.lua:50>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua"]:98: in function <...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96>
[string "@Altoholic\Tooltip.lua"]:755: in function <Altoholic\Tooltip.lua:753>
[string "=[C]"]: in function `SetRecipeReagentItem'
[string "@Blizzard_TradeSkillUI\Blizzard_TradeSkillDetails.lua"]:768: in function `OnReagentMouseEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = "Usage: local isDressableItem = C_Item.IsDressableItemByID(itemInfo)"

**Comment by SLOKnightfall** [comment]
Thanks.  It will be fixed in the next build.
