### ISSUE TITLE
Ulduar 25 Man Sets

### ISSUE THREAD

**Issue by Zepher01** [SLOKnightfall/BetterWardrobe#169]
Each Ulduar 25 man set is only 5 pieces.

In particular the Paladin set has 7 shown (Conqueror's Aegis Regalia, https://www.wowhead.com/item-set=-71/conquerors-aegis-regalia)

Each set only contains the following locations:

Hands
Legs
Head
Shoulders
Chest

**Comment by SLOKnightfall** [comment]
The Ulduar 25 man sets data shown on the Sets tab is being pulled from the Blizzard API which lists the set with 7 pieces when Better Wardrobe is disabled.

**Comment by Zepher01** [comment]
That might be true but the pieces are from the cats xpack
-------- Original message --------From: SLOKnightfall ***@***.***> Date: 2021-07-03  2:00 p.m.  (GMT-05:00) To: SLOKnightfall/BetterWardrobe ***@***.***> Cc: Zepher01 ***@***.***>, Author ***@***.***> Subject: Re: [SLOKnightfall/BetterWardrobe] Ulduar 25 Man Sets (#169) 
The Ulduar 25 man sets data shown on the Sets tab is being pulled from the Blizzard API which lists the set with 7 pieces when Better Wardrobe is disabled.
