### ISSUE TITLE
Some elements in ElvUI style although skin disabled

### ISSUE THREAD

**Issue by TheKrowi** [SLOKnightfall/BetterWardrobe#17]
Some elements show as skinned ElvUI tabs although I have ElvUI skins disabled. Same for the sort dropdown.
![image](https://user-images.githubusercontent.com/22818581/93694236-9b7a9180-fb09-11ea-9cad-7e365d47a78d.png)
![image](https://user-images.githubusercontent.com/22818581/93694255-d1b81100-fb09-11ea-9398-9d9318d3142b.png)

**Comment by SLOKnightfall** [comment]
Thanks for letting me know.  Should be fixed in the next release.
