### ISSUE TITLE
Weapon illusion mog

### ISSUE THREAD

**Issue by redfiredrake** [SLOKnightfall/BetterWardrobe#170]
the weapon illusion/enhancement section for xmog completely disappears with this addons now, how do we xmog effects on weapons?

**Comment by Aur0r4** [comment]
Not sure if it helps but it seems like the buttons for weapon illusion transmog is on the bottom of screen...at least one button

![image](https://user-images.githubusercontent.com/28149249/124320739-bd1aa600-db7c-11eb-9bd9-da7d99822c3c.png)

**Comment by thats-how-you-get-ants** [comment]
Well having the buttons show up on the bottom is a real downgrade from where they used to be and people are likely to miss it. They also don't appear there for me. 

Not only do enchant options not appear anywhere, there is not even an enchant "slot" on the weapon.
![image](https://user-images.githubusercontent.com/11278095/124328887-75822300-db58-11eb-90eb-27e1bbe6f8f2.png)

Just to show the item is enchant-moggable without BetterWardrobe:
![image](https://user-images.githubusercontent.com/11278095/124329155-f50ff200-db58-11eb-8efb-1d82239218fc.png)

**Comment by Ketrel** [comment]
This is one of the issues I fixed in #172

**Comment by SLOKnightfall** [comment]
Fixed in the next update
