### ISSUE TITLE
V3.0 Filters appear to be broken 

### ISSUE THREAD

**Issue by Zepher01** [SLOKnightfall/BetterWardrobe#173]
V3.0 Filters appear to be broken 
![Broken Filters](https://user-images.githubusercontent.com/10968775/124338809-dc630480-db77-11eb-8af0-1f3a7f1fb7a5.JPG)

**Comment by SLOKnightfall** [comment]
Fixed in the next update.

**Comment by Zepher01** [comment]
Awesome thanks!  I've been doing a lot of set farming and this addon is amazing!  Thanks for keeping it up!
-------- Original message --------From: SLOKnightfall ***@***.***> Date: 2021-07-03  1:44 p.m.  (GMT-05:00) To: SLOKnightfall/BetterWardrobe ***@***.***> Cc: Zepher01 ***@***.***>, Author ***@***.***> Subject: Re: [SLOKnightfall/BetterWardrobe] V3.0 Filters appear to be broken  (#173) 
Fixed in the next update.
