### ISSUE TITLE
v3.0 Can't add new saved set

### ISSUE THREAD

**Issue by IDKnife** [SLOKnightfall/BetterWardrobe#174]
In dressing room after trying to add new set nothing happens. In transmogrification windown set can be added but displays incorrect. Tried to do it with only this addon turned on but it didn't helped. Also tried to delete cache folder and this didn't helped too.

**Comment by SLOKnightfall** [comment]
That should be fixed in the 3.1 version.  I ended up having to do a lot of rewriting but I think that I got it working with all the kinks worked out.
