### ISSUE TITLE
Links to New Collections Do Not Open Addon Window

### ISSUE THREAD

**Issue by Zepher01** [SLOKnightfall/BetterWardrobe#176]
Clicking on the links provided for newly collected appearances does not open the addon.
In this case : "[Thrall's Garb (10 Player (Normal))]"

Regarding "Interface action failed .." there are no new addons only recently updated ones.  Functionality worked previously to 9.1

![Broken Link](https://user-images.githubusercontent.com/10968775/124363936-4b8a3880-dc0c-11eb-999d-eef67374a15c.JPG)

**Comment by SLOKnightfall** [comment]
Should be fixed now.
