### ISSUE TITLE
doesn't work with addon Rarity 

### ISSUE THREAD

**Issue by tormaz0311** [SLOKnightfall/BetterWardrobe#178]
After 9.1 addon just stopped working. No "Extra" and "Saved" windows. No large transmog window. Nothing. I updated it a few days ago, but nothing changed for me, so i started looking if some of my other addons are "blocking" better wardrobe. And it was Rarity. When I dissably Rarity, everything work (except some of the things below)
What else dost work:
-list of all covenant sets, even those that I own
-list of raid sets
-when I enable "Ignore class restriction" I can see in "Extra" sets for different class, but I cant equip them. I get LUA error like in picture

Thank you!

![WoWScrnShot_070421_205407](https://user-images.githubusercontent.com/86926564/124394888-0e0bd500-dd0a-11eb-8796-4eb1635e228f.jpg)

**Comment by SLOKnightfall** [comment]
That should be fixed in the 3.1 update.  Rarity loads the Blizzard Colllection addon when it loads which causes parts of my addon to trigger before it has fully initialized.  I put a few checks in to hopefully prevent that from happening.
