### ISSUE TITLE
Conflict with Addon Wardrobe Enhanced (formerly Legion Wardrobe)

### ISSUE THREAD

**Issue by chasaya** [SLOKnightfall/BetterWardrobe#179]
Latest update (V3.0) doesn't seem to work witth Wardrobe Enhanced ([https://www.curseforge.com/wow/addons/wardrobe-enhanced](url))
While BetterWardrobe is enabled, none of Wardrobe Enhanced's features are available. There is no LUA error, it's just as if the addon is not loaded at all (although my addon list shows it as enabled). When I disable BetterWardrobe, Wardrobe Enhanced is working fine. 
Please let me know in case this should be addressed with the creator of Wardrobe Enhanced instead, I'll open an issue on the addon's page then. Thanks a lot for your great addon!

**Comment by SLOKnightfall** [comment]
Unfortunately both addon's heavily modify the Transmog frames and because of that are not compatible with each other.

**Comment by chasaya** [comment]
Thanks for the reply, just wanted to add that before 9.1/latest update I've been using both addons and they seemed to get along nicely, if that info helps. I could use the features of both with no issue, and I really liked some of Wardrobe Enhanced features like showing all versions and respective sources of an appearance or the filtering features (I like your Sets feature better tho :)). But no problem, I'll keep an eye on coming updates and keep my fingers crossed! Thanks again!

**Comment by SLOKnightfall** [comment]
My apologies.  When I originally replied I got Wardrobe/Legion Enhanced mistaken with another transmogrify addon.  You were correct that it was previously compatible together with Better Wardrobe.  I think that I should be able to come up with a compatibility plugin to get them working together.

**Comment by SLOKnightfall** [comment]
Created a plugin the allows Wardrobe/Legion Enhanced integration into BetterWardrobe
