### ISSUE TITLE
New error with 3.1.1 when opening Appearances tab

### ISSUE THREAD

**Issue by CMcFadyen** [SLOKnightfall/BetterWardrobe#180]
10x BetterWardrobe\Plugins\MogIt.lua:34: attempt to index global 'BetterWardrobe_Mogitdata' (a nil value)
[string "@BetterWardrobe\Plugins\MogIt.lua"]:34: in function <BetterWardrobe\Plugins\MogIt.lua:30>
[string "@BetterWardrobe\Plugins\MogIt.lua"]:53: in function `GetMogitOutfits'
[string "@BetterWardrobe\Modules\SavedOutfits.lua"]:87: in function `GetOutfits'
[string "@BetterWardrobe\Data\DataBase.lua"]:404: in function `GetSavedList'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:1205: in function `SetTab'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:1289: in function <BetterWardrobe\Modules\Wardrobe.lua:1262>
[string "=[C]"]: in function `Show'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:1036: in function `SetContainer'
[string "@BetterWardrobe\Modules\Core.lua"]:1237: in function <BetterWardrobe\Modules\Core.lua:1229>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `CollectionsJournal_UpdateSelectedTab'
[string "@Blizzard_Collections\Blizzard_Collections-1.0.lua"]:6: in function `CollectionsJournal_SetTab'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
name = "Grayson"
realm = "Turalyon"
profileName = "Grayson - Turalyon"
(*temporary) = nil
(*temporary) = "Turalyon"
(*temporary) = "attempt to index global 'BetterWardrobe_Mogitdata' (a nil value)"

I don't have any Mogit outfits saved, so it might be trying to load a non-existant savedvariable

**Comment by SLOKnightfall** [comment]
Fixed in the next update
