### ISSUE TITLE
latest build V3.1.1

### ISSUE THREAD

**Issue by Roneasaurus** [SLOKnightfall/BetterWardrobe#181]
Message: Interface\AddOns\BetterWardrobe\Plugins\MogIt.lua:34: attempt to index global 'BetterWardrobe_Mogitdata' (a nil value)
Time: Mon Jul  5 20:50:33 2021
Count: 1
Stack: Interface\AddOns\BetterWardrobe\Plugins\MogIt.lua:34: attempt to index global 'BetterWardrobe_Mogitdata' (a nil value)
[string "@Interface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua"]:123: in function `LookupIndexFromID'
[string "@Interface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua"]:134: in function <...rface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua:133>
[string "@Interface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua"]:307: in function `SelectOutfit'
[string "@Interface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua"]:263: in function <...rface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua:260>
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2883: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2957: in function `HideUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2645: in function <Interface\FrameXML\UIParent.lua:2637>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3512: in function <Interface\FrameXML\UIParent.lua:3495>
[string "=[C]"]: in function `HideUIPanel'
[string "@Interface\FrameXML\CinematicFrame.lua"]:59: in function <Interface\FrameXML\CinematicFrame.lua:44>

Locals: outfitID = 14
GetOutfits = <function> defined @Interface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua:47

**Comment by SLOKnightfall** [comment]
Fixed in the next update
