### ISSUE TITLE
Filter Error 3.1.1

### ISSUE THREAD

**Issue by Zepher01** [SLOKnightfall/BetterWardrobe#182]
Filters for expansions appear to be indexed forward by 1 xpac, e.g. Classic shows BC, BC shows Wrath etc. until Shadowlands which would show Classic but shows as empty.

![Filter error](https://user-images.githubusercontent.com/10968775/124464627-6b337500-dd62-11eb-8661-cfb56ef67352.JPG)

**Comment by SLOKnightfall** [comment]
Fixed in the next update
