### ISSUE TITLE
Errors that pop up upon opening transmog

### ISSUE THREAD

**Issue by Timaeria** [SLOKnightfall/BetterWardrobe#186]
Error 1:

7x BetterWardrobe\Plugins\MogIt.lua:34: attempt to index global 'BetterWardrobe_Mogitdata' (a nil value)
[string "@BetterWardrobe\Plugins\MogIt.lua"]:34: in function <BetterWardrobe\Plugins\MogIt.lua:30>
[string "@BetterWardrobe\Plugins\MogIt.lua"]:53: in function `GetMogitOutfits'
[string "@BetterWardrobe\Modules\SavedOutfits.lua"]:87: in function `GetOutfits'
[string "@BetterWardrobe\Data\DataBase.lua"]:404: in function `GetSavedList'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:1205: in function `SetTab'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:1289: in function <BetterWardrobe\Modules\Wardrobe.lua:1262>
[string "=[C]"]: in function `Show'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:1036: in function `SetContainer'
[string "@BetterWardrobe\Modules\Core.lua"]:1237: in function <BetterWardrobe\Modules\Core.lua:1229>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `CollectionsJournal_UpdateSelectedTab'
[string "@Blizzard_Collections\Blizzard_Collections-1.0.lua"]:6: in function `CollectionsJournal_SetTab'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
name = "Elaeana"
realm = "Stormrage"
profileName = "Elaeana - Stormrage"
(*temporary) = nil
(*temporary) = "Stormrage"
(*temporary) = "attempt to index global 'BetterWardrobe_Mogitdata' (a nil value)"

Error 2:
1x BetterWardrobe\Plugins\MogIt.lua:26: attempt to index global 'BetterWardrobe_Mogitdata' (a nil value)
[string "@BetterWardrobe\Plugins\MogIt.lua"]:26: in function <BetterWardrobe\Plugins\MogIt.lua:22>
[string "@BetterWardrobe\Plugins\MogIt.lua"]:39: in function <BetterWardrobe\Plugins\MogIt.lua:38>
[string "=(tail call)"]: ?
[string "@BetterWardrobe\Modules\CollectionList.lua"]:522: in function `SelectedCollectionList'
[string "@BetterWardrobe\Modules\CollectionList.lua"]:304: in function `func'
[string "@BetterWardrobe\Libs\UIDropDownMenu\UIDropDownMenu.lua"]:905: in function `BW_UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
name = "Elaeana"
realm = "Stormrage"
profileName = "Elaeana - Stormrage"
(*temporary) = nil
(*temporary) = "Stormrage"
(*temporary) = "attempt to index global 'BetterWardrobe_Mogitdata' (a nil value)"

I don't use MogIt which may be where these errors are coming from.

**Comment by SLOKnightfall** [comment]
Fixed in the next update
