### ISSUE TITLE
V 3.1.1 Saved sets are missing

### ISSUE THREAD

**Issue by rads3991** [SLOKnightfall/BetterWardrobe#189]
After updating all the saved sets I had for my characters are gone. I can remove the addon and they come back. Also it does not let me save a new set as I tested that as well. After trying to save the new set nothing happens

**Comment by Kestrelator** [comment]
Can confirm . . . same issue, all cases.

**Comment by rads3991** [comment]
I think it is likely that our saved sets are not gone but the addon is not
pulling from the stored location after the update.

**Comment by SLOKnightfall** [comment]
I believe that the issue is due to some changes to how things were saved in the addon's saved variables a few releases back and the update trigger code was commented out in the current version.  I uncommented it which should fix the issue.
