### ISSUE TITLE
Item/Slots are not set to pending when clicking (before applying) an Extended Saved Set (V3.3)

### ISSUE THREAD

**Issue by Ketrel** [SLOKnightfall/BetterWardrobe#195]
This one I have fixed and pull request is incoming, just opening this to link it to it.

**Comment by Ketrel** [comment]
Pull request has been submitted, but to clarify, this is what it's doing

https://i.imgur.com/zJIqm9s.png

**Comment by Ketrel** [comment]
(there may be more needed to get it to work with the enchant illusion slots as well, but I'm not familiar enough with the xmog code to address that part)

**Comment by Ketrel** [comment]
I think I may see an issue with slot IDs and whatnot in general.  

Does this command if run in game produce the output you're expecting when you loop 1-19?

`/run for i=1,20 do local x=TransmogUtil.GetSlotName(i) or '-'; print(i..': '..x); end`

**Comment by SLOKnightfall** [comment]
Added provided updates.
