### ISSUE TITLE
wardrobe transmog frame

### ISSUE THREAD

**Issue by Roneasaurus** [SLOKnightfall/BetterWardrobe#199]
Message: Interface\AddOns\BetterWardrobe\Modules\Wardrobe-Appearances.lua:7123: attempt to index global 'WardrobeTransmogFrame' (a nil value)
Time: Thu Jul  8 17:23:15 2021
Count: 1
Stack: Interface\AddOns\BetterWardrobe\Modules\Wardrobe-Appearances.lua:7123: attempt to index global 'WardrobeTransmogFrame' (a nil value)
[string "@Interface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua"]:287: in function <...rface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua:275>
[string "=[C]"]: in function `LoadOutfit'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:7056: in function `LoadOutfit'
[string "@Interface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua"]:318: in function `SelectOutfit'
[string "@Interface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua"]:263: in function <...rface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua:260>
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2883: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2957: in function `HideUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2645: in function <Interface\FrameXML\UIParent.lua:2637>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3512: in function <Interface\FrameXML\UIParent.lua:3495>
[string "=[C]"]: in function `HideUIPanel'
[string "@Interface\FrameXML\CinematicFrame.lua"]:59: in function <Interface\FrameXML\CinematicFrame.lua:44>

Locals: self = BetterWardrobeOutfitDropDown {
 0 = <userdata>
 LoadOutfit = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:7047
 Left = BetterWardrobeOutfitDropDownLeft {
 }
 OnLoad = <function> defined @Interface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua:247
 UpdateSaveButton = <function> defined @Interface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua:292
 CheckOutfitForSave = <function> defined @Interface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua:400
 width = 188
 OnSelectOutfit = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:7136
 Button = BetterWardrobeOutfitDropDownButton {
 }
 Icon = BetterWardrobeOutfitDropDownIcon {
 }
 IsDefaultSet = <function> defined @Interface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua:448
 Middle = BetterWardrobeOutfitDropDownMiddle {
 }
 OnOutfitApplied = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:7028
 Right = BetterWardrobeOutfitDropDownRight {
 }
 OnShow = <function> defined @Interface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua:260
 IsOutfitDressed = <function> defined @Interface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua:345
 GetLastOutfitID = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:7146
 Text = BetterWardrobeOutfitDropDownText {
 }
 maxMenuStringWidth = 216
 OnEvent = <function> defined @Interface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua:275
 SaveButton = <unnamed> {
 }
 minMenuStringWidth = 152
 GetItemTransmogInfoList = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:7122
 selectedOutfitID = 4
 OnHide = <function> defined @Interface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua:266
 SelectOutfit = <function> defined @Interface\AddOns\BetterWardrobe\Modules\SavedOutfits.lua:303
 OnOutfitSaved = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:7130
 noResize = 1
}
event = "TRANSMOGRIFY_UPDATE"

**Comment by SLOKnightfall** [comment]
Should be fixed in the next update
