### ISSUE TITLE
Error on attempting to view a set

### ISSUE THREAD

**Issue by solitha** [SLOKnightfall/BetterWardrobe#200]
"Extra" shows the same list as the base UI "Sets" and when anything is clicked shows error:

`3x BetterWardrobe\Modules\Wardrobe-Appearances.lua:5307: attempt to index local 'baseSet' (a nil value)
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:5307: in function `GetDefaultSetIDForBaseSet'
[string "@LegionWardrobe\LegionTransmog.lua"]:2861: in function `SelectSetFromButton'
[string "*:OnMouseUp"]:3: in function <[string "*:OnMouseUp"]:1>

Locals:
self = <unnamed> {
 0 = <userdata>
 LeftInset = <unnamed> {
 }
 GetDefaultSetIDForBaseSet = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:5288
 CanHandleKey = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:5419
 OnUnitModelChangedEvent = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:5237
 SelectSetFromButton = <function> defined @LegionWardrobe\LegionTransmog.lua:2858
 SetItemFrameQuality = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:5214
 ScrollFrame = BetterWardrobeCollectionFrameScrollFrame {
 }
 selectedExtraSetID = 50115
 OpenVariantSetsDropDown = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:5264
 GetSelectedSavedSetID = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:5663
 ClearLatestSource = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4958
 SelectSavedSet = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:5339
 GetSelectedSetID = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:5360
 RefreshAppearanceTooltip = <function> defined @LegionWardrobe\LegionTransmog.lua:3033
 UpdateProgressBar = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4950
 OnSearchUpdate = <function> defined =[C]:-1
 DetailsFrame = <unnamed> {
 }
 RefreshCameras = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:5251
 RightInset = <unnamed> {
 }
 selectedSavedSetID = 5000
 ClearAppearanceTooltip = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:5413
 init = true
 selectedVariantSets = <table> {
 }
 selectedSetID = 2262
 OnLoad = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4685
 OnHide = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4769
 Refresh = <function> defined @LegionWardrobe\LegionTransmog.lua:2851
 Model = <unnamed> {
 }
 OnEvent = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4809
 ScrollToSet = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:5461
 HandleKey = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:5426
 searchType = 2
 SetAppearanceTooltip = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:5371
 DisplaySet = <function> defined @LegionWardrobe\LegionTransmog.lua:2937
 DisplaySavedSet = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:5104
 OnShow = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4702
 SelectSet = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:5343
}
baseSetID = 2262
baseSet = nil
(*temporary) = <table> {
 ResetBaseSetNewStatus = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4557
 baseExtraSets = <table> {
 }
 baseSetsData = <table> {
 }
 IsBaseSetNew = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4530
 SortSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4065
 sourceData = <table> {
 }
 GetBaseSetData = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4456
 GetUsableSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4252
 GetIconForSet = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4633
 baseExtraSetsData = <table> {
 }
 GetBaseSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4179
 GetSetSourceData = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4402
 GetSetSourceCounts = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4449
 sourceExtraData = <table> {
 }
 DetermineFavorites = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4647
 ClearUsableSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4627
 GetSortedSetSo`

**Comment by SLOKnightfall** [comment]
Looks like there is an conflict with LegionWardrobe as its trying to modify the transmog frames also.

**Comment by solitha** [comment]
Aha! Thank you for the tip... I was able to find and turn off the new option in that addon that was conflicting. Both addons have very different functions, but they've been expanding theirs recently.

Thank you again!
