### ISSUE TITLE
BetterWardrobe Druid Weapons Fangs of Ashamane and Claws of Ursoc Artifact Bug

### ISSUE THREAD

**Issue by Galthariel** [SLOKnightfall/BetterWardrobe#201]
I first thought it was the bug caused by Shadowlands launch when Druids were unable to change their Polearms and/or Staves into Fangs of Ashamane or Claws of Ursoc. After researching the forums and Google about this issue I could not find anyone else complaining so I decided to start disabling a few Transmog Addons to see if was one of them causing the issue and guess what? It's BetterWardrobe. After disabling BetterWardrobe I can now change the Polearms and Staves appearance into Fangs or Claws.

Another Bug is that BetterWardrobe is preventing the use of "Find All Recolors" feature from Wardrobe Enhanced. Both addons use to work very fine together :-)

Thanks in advance

**Comment by SLOKnightfall** [comment]
So I've been trying to reproduce the issue with the next update version and it looks like it has sorted its self out some how.   I've tried transmoging with staves & polearms equipped to be either the Fangs when in feral spec and claws in Guardian spec with out any issue.  I'm going to mark this as closed for now.  If you still have the issues then please reopen and I'll revision.
