### ISSUE TITLE
Error message with new transmog design

### ISSUE THREAD

**Issue by mutanzoom** [SLOKnightfall/BetterWardrobe#206]
I always get this error message when I get a new transmog design.

> 5x BetterWardrobe\Modules\Wardrobe-Vorlagen.lua:1401: attempt to index global 'inventoryTypes' (a nil value)
> [string "@BetterWardrobe\Modules\Wardrobe-Vorlagen.lua"]:1401: in function `OnEvent'
> [string "@BetterWardrobe\Modules\Core.lua"]:1398: in function `?'
> [string "@Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
> [string "=[C]"]: ?
> [string "@Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
> [string "@Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
> [string "@TomTom\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...aceTomTom\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by SLOKnightfall** [comment]
Fixed in the next update
