### ISSUE TITLE
Wardrobe-Appearances.lua:4649: attempt to index local 'sourceData' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [SLOKnightfall/BetterWardrobe#220]
Mousing over a piece if gear on my mission table produces the following error.

2x BetterWardrobe\Modules\Wardrobe-Appearances.lua:4649: attempt to index local 'sourceData' (a nil value)
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:4649: in function `GetSetSourceCounts'
[string "@BetterWardrobe\Modules\Tooltips.lua"]:395: in function `ShowTooltip'
[string "@BetterWardrobe\Modules\Tooltips.lua"]:75: in function <BetterWardrobe\Modules\Tooltips.lua:73>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Vendor\sys\hook.lua"]:54: in function <Vendor\sys\hook.lua:50>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua"]:107: in function <...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:105>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetHyperlink'
[string "@VenturePlan\Widgets.lua"]:104: in function <VenturePlan\Widgets.lua:77>

Locals:
self = <table> {
 ResetBaseSetNewStatus = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4737
 baseSets = <table> {
 }
 baseSetsData = <table> {
 }
 IsBaseSetNew = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4709
 SortSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4257
 sourceData = <table> {
 }
 GetUsableSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4444
 GetBaseSetData = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4652
 GetIconForSet = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4866
 baseExtraSetsData = <table> {
 }
 GetBaseSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4371
 sourceExtraData = <table> {
 }
 GetSetSourceCounts = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4647
 GetSetSourceData = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4594
 DetermineFavorites = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4880
 ClearUsableSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4860
 GetSortedSetSources = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4744
 RefreshFavorites = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4901
 variantSets = <table> {
 }
 GetVariantSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4571
 ClearSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4834
 ClearBaseSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4850
 ClearVariantSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4856
 GetBaseSetByID = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4431
 GetSetSourceTopCounts = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4699
}
setID = 50032
sourceData = nil
(*temporary) = <table> {
 ResetBaseSetNewStatus = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4737
 baseSets = <table> {
 }
 baseSetsData = <table> {
 }
 IsBaseSetNew = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4709
 SortSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4257
 sourceData = <table> {
 }
 GetUsableSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4444
 GetBaseSetData = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4652
 GetIconForSet = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4866
 baseExtraSetsData = <table> {
 }
 GetBaseSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4371
 sourceExtraData = <table> {
 }
 GetSetSourceCounts = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4647
 GetSetSourceData = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4594
 DetermineFavorites = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4880
 ClearUsableSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4860
 GetSortedSetSources = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4744
 RefreshFavorites = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4901
 variantSets = <table> {
 }
 GetVariantSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4571
 ClearSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4834
 ClearBaseSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4850
 ClearVariantSets = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4856
 GetBaseSetByID = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:4431
 GetSetSourceTopCounts = <function> defined @BetterWardrobe\Modules\Wardrobe.l

**Comment by SLOKnightfall** [comment]
Fixed in next release
