### ISSUE TITLE
Error in equipment mouseovers

### ISSUE THREAD

**Issue by solitha** [SLOKnightfall/BetterWardrobe#222]
Just mousing over certain items causes an error that continues to fire so long as you hover over the item. The Nightcloaked Helm is one, for me. Blackhound Headguard is another.

`15x BetterWardrobe\Modules\BlizzardAPI.lua:179: attempt to index global 'BetterWardrobeCollectionFrame' (a nil value)
[string "@BetterWardrobe\Modules\BlizzardAPI.lua"]:179: in function <BetterWardrobe\Modules\BlizzardAPI.lua:175>
[string "=(tail call)"]: ?
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:4628: in function `GetSetSourceData'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:4648: in function `GetSetSourceCounts'
[string "@BetterWardrobe\Modules\Tooltips.lua"]:395: in function `ShowTooltip'
[string "@BetterWardrobe\Modules\Tooltips.lua"]:75: in function <BetterWardrobe\Modules\Tooltips.lua:73>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@FrameXML\ContainerFrame.lua"]:1371: in function `ContainerFrameItemButton_OnUpdate'
[string "@FrameXML\ContainerFrame.lua"]:1418: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
setID = 50018
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'BetterWardrobeCollectionFrame' (a nil value)"
addon = <table> {
 ViewDelay = 3
 useAltSet = false
 modules = <table> {
 }
 Sort = <table> {
 }
 SecureHook = <function> defined @BetterWardrobe\Libs\AceHook-3.0\AceHook-3.0.lua:336
 tooltip = BW_ProfileTooltip {
 }
 SetDefaultModulePrototype = <function> defined @AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 MogIt = <table> {
 }
 IsEnabled = <function> defined @AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 GetActiveCategory = <function> defined @BetterWardrobe\Modules\CollectionList.lua:217
 RefreshCharConfig = <function> defined @BetterWardrobe\Modules\Core.lua:997
 RegisterMessage = <function> defined @TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 validSetCache = <table> {
 }
 ArmorSetModCache = <table> {
 }
 db = <table> {
 }
 SetEnabledState = <function> defined @AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @BetterWardrobe\Libs\AceHook-3.0\AceHook-3.0.lua:274
 GetSourceFromItem = <function> defined @BetterWardrobe\Modules\Tooltips.lua:208
 InitExtendedSetsSwap = <function> defined @BetterWardrobe\Plugins\ExtendedTransmog.lua:6
 OnEnable = <function> defined @BetterWardrobe\Modules\Core.lua:1207
 RefreshOutfitData = <function> defined @BetterWardrobe\Modules\Core.lua:874
 GetArtifactSourceInfo = <function> defined @BetterWardrobe\Modules\ArtifactAppearances.lua:283
 IsWeaponCat = <function> defined @BetterWardrobe\Modules\CollectionList.lua:222
 ItemAppearance = <table> {
 }
 OnInitialize = <function> defined @BetterWardrobe\Modules\Core.lua:1017
 NewModule = <function> defined @AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 Globals = <table> {
 }
 SortSet = <function> defined @BetterWardrobe\Modules\SortingFunctions.lua:509
 HiddenAppearanceDB = <table> {
 }
 GetName = <function> defined @AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 C_TransmogCollection = <table> {
 }
 Camera = <table> {
 }
 name = "BetterWardrobe"
 UI = <table> {
 }
 Disable = <function> defined @AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 GetSetType = <function> defined @BetterWardrobe\Data\DataBase.lua:656
 Unhook = <function> defined @BetterWardrobe\Libs\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @AckisRecipeList\libs\AceConsole-3.0\AceConsole-3.0.lua:54
 IsFavoriteItem = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:3436
 usableSourceCache = <table> {
 }
 ExtendTransmogView = <function> defined @BetterWardrobe\Modules\TransmogVendor.lua:423
 BuildClassArtifactAppearanceList = <function> defined @BetterWardrobe\Modules\ArtifactAppearances.lua:177
 TRANSMOG_SET_FILTER = <table> {
 }
 Init = <table> {
 }
 CreateChatLinkTransmogVendor = <function> defined @BetterWardrobe\Modules\ImportExport.lua:299
 EventHandler = <function> defined @BetterWardrobe\Modules\Core.lua:1314
 SelecteSavedList = false
 CollectionList = <table> {
 }
 GetSetCounts = <function> defined @BetterWardrobe\Modules\BlizzardAPI.lua:487
 RemoveItemSubstitute = <function> defined @BetterWardrobe\Data\DataBase.lua:866
 UnregisterEvent = <`

**Comment by SLOKnightfall** [comment]
Fixed in the next update
