### ISSUE TITLE
saved sets all naked

### ISSUE THREAD

**Issue by Roneasaurus** [SLOKnightfall/BetterWardrobe#225]
Message: Usage: local apppearances = C_TransmogSets.GetSetPrimaryAppearances(transmogSetID)
Time: Fri Aug  6 01:14:18 2021
Count: 7
Stack: Usage: local apppearances = C_TransmogSets.GetSetPrimaryAppearances(transmogSetID)

Locals:

**Comment by SLOKnightfall** [comment]
Fixed in next update
