### ISSUE TITLE
Error with default set window (not with extra set tab) 

### ISSUE THREAD

**Issue by jamcdani** [SLOKnightfall/BetterWardrobe#226]
Each time I try to go to the "Sets" tab I get the following 3 LUA errors

Message: ...erface\AddOns\BetterWardrobe\Modules\BlizzardAPI.lua:185: attempt to index local 'setInfo' (a nil value)
Time: Thu Aug  5 21:32:06 2021
Count: 1
Stack: ...erface\AddOns\BetterWardrobe\Modules\BlizzardAPI.lua:185: attempt to index local 'setInfo' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\BetterWardrobe\Modules\BlizzardAPI.lua"]:185: in function `GetSetSources'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:7297: in function `GetLocationBasedCount'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:4479: in function `GetUsableSets'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:6407: in function `UpdateSets'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:6974: in function `ResetPage'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:6398: in function `Refresh'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:6305: in function <Interface\AddOns\BetterWardrobe\Modacules\Wardrobe.lua:6293>
[string "=[C]"]: in function `SetShown'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:1271: in function `SetTab'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:1176: in function `ClickTab'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: 

Message: Usage: local apppearances = C_TransmogSets.GetSetPrimaryAppearances(transmogSetID)
Time: Thu Aug  5 21:32:38 2021
Count: 15
Stack: Usage: local apppearances = C_TransmogSets.GetSetPrimaryAppearances(transmogSetID)
[string "=[C]"]: ?
[string "=[C]"]: in function `GetSetPrimaryAppearances'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:3160: in function `RefreshTooltip'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:3146: in function <Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:3143>

Locals: 

Message: Usage: local apppearances = C_TransmogSets.GetSetPrimaryAppearances(transmogSetID)
Time: Thu Aug  5 21:32:08 2021
Count: 2
Stack: Usage: local apppearances = C_TransmogSets.GetSetPrimaryAppearances(transmogSetID)
[string "=[C]"]: ?
[string "=[C]"]: in function `GetSetPrimaryAppearances'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:6705: in function `LoadSet'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:6914: in function `SelectSet'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:3130: in function <Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:3128>

Locals:

**Comment by SLOKnightfall** [comment]
Fixed in next update
