### ISSUE TITLE
Problem when opening normal sets

### ISSUE THREAD

**Issue by gottshy** [SLOKnightfall/BetterWardrobe#227]
Hey since yesterday this problem is occuring when opening the tab with the normal sets:

21x BetterWardrobe\Modules\BlizzardAPI.lua:185: attempt to index local 'setInfo' (a nil value)
[string "@BetterWardrobe\Modules\BlizzardAPI.lua"]:185: in function `GetSetSources'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:7297: in function `GetLocationBasedCount'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:4479: in function `GetUsableSets'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:6407: in function `UpdateSets'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:6974: in function `ResetPage'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:6398: in function `Refresh'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:6305: in function <BetterWardrobe\Modules\Wardrobe.lua:6293>
[string "=[C]"]: in function `SetShown'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:1271: in function `SetTab'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:1176: in function `ClickTab'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
setID = 2059
setInfo = nil
(*temporary) = 2059
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'setInfo' (a nil value)"
addon = <table> {
 TransmogVendorSizeUpdated = true
 ViewDelay = 3
 useAltSet = false
 modules = <table> {
 }
 Sort = <table> {
 }
 SecureHook = <function> defined @ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:336
 tooltip = BW_ProfileTooltip {
 }
 SetDefaultModulePrototype = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 MogIt = <table> {
 }
 IsEnabled = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 GetActiveCategory = <function> defined @BetterWardrobe\Modules\CollectionList.lua:217
 RefreshCharConfig = <function> defined @BetterWardrobe\Modules\Core.lua:1158
 RegisterMessage = <function> defined @ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 validSetCache = <table> {
 }
 ArmorSetModCache = <table> {
 }
 db = <table> {
 }
 SetEnabledState = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:274
 GetSourceFromItem = <function> defined @BetterWardrobe\Modules\Tooltips.lua:208
 InitExtendedSetsSwap = <function> defined @BetterWardrobe\Plugins\ExtendedTransmog.lua:6
 OnEnable = <function> defined @BetterWardrobe\Modules\Core.lua:1263
 RefreshOutfitData = <function> defined @BetterWardrobe\Modules\Core.lua:874
 GetArtifactSourceInfo = <function> defined @BetterWardrobe\Modules\ArtifactAppearances.lua:283
 IsWeaponCat = <function> defined @BetterWardrobe\Modules\CollectionList.lua:222
 ItemAppearance = <table> {
 }
 OnInitialize = <function> defined @BetterWardrobe\Modules\Core.lua:1178
 NewModule = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:235
 Globals = <table> {
 }
 SortSet = <function> defined @BetterWardrobe\Modules\SortingFunctions.lua:509
 HiddenAppearanceDB = <table> {
 }
 GetName = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 C_TransmogCollection = <table> {
 }
 Camera = <table> {
 }
 name = "BetterWardrobe"
 UI = <table> {
 }
 Disable = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:314
 GetSetType = <function> defined @BetterWardrobe\Data\DataBase.lua:661
 Unhook = <function> defined @ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:418
 Print = <function> defined @ElvUI\Libraries\Ace3\AceConsole-3.0\AceConsole-3.0.lua:54
 IsFavoriteItem = <function> defined @BetterWardrobe\Modules\Wardrobe.lua:3436
 usableSourceCache = <table> {
 }
 ExtendTransmogView = <function> defined @BetterWardrobe\Modules\TransmogVendor.lua:423
 BuildClassArtifactAppearanceList = <function> defined @BetterWardrobe\Modules\ArtifactAppearances.lua:177
 TRANSMOG_SET_FILTER = <table> {
 }
 Init = <table> {
 }
 CreateChatLinkTransmogVendor = <function> defined @BetterWardrobe\Modules\ImportExport.lua:299
 EventHandler = <function> defined @BetterWardrobe\Modules\Core.lua:1370
 SelecteSavedList = false
 CollectionList = <table> {
 }
 GetSetCounts = <function> defined @BetterWardrobe\Modules\BlizzardAPI.lua:495
 RemoveItemSubstitute = <function> defined @Interfac
 
 and this one :
 https://i.imgur.com/wzkfpyg.png

**Comment by zaphon** [comment]
Having same issue.

**Comment by SLOKnightfall** [comment]
Fixed in next update
