### ISSUE TITLE
Current Set When Opening Transmog Window

### ISSUE THREAD

**Issue by webdevdave** [SLOKnightfall/BetterWardrobe#230]
Hey, so it used to be that when I got a new item, when I opened the transmog vendor it would already be set to my current transmog, there it would detect that the new item wasn't transmogged yet so it would be glowing, I would then hit transmog and voila! Now it seems when I open the transmog window, it is no longer set to the current transmog and I need to look through my list and select the proper one, etc. No biggy, but I really preferred the previous way. Hoping it's a bug that you can fix to bring it back.

Thanks and keep up the great work!!!

**Comment by SLOKnightfall** [comment]
There were some issues with how it was storing the currently selected transmog which just got fixed.  It should be showing it again correctly although you may need to reapply the transmog again for it to store the value
