### ISSUE TITLE
Scroll window on Saved Mogs Dropdown is too small for default size

### ISSUE THREAD

**Issue by willgk** [SLOKnightfall/BetterWardrobe#232]
You have a 2 piece issue here, your "BetterWardrobeOutfitFrame"'s default "Height" is bad, it's set to 49.9999999, set it to something like 200 and it will correct the size there, you then need to set your BetterWardrobeOutfitFrameScrollFrame up to that approximate height, ie 198 or something. This will make it so you can actually view the frames instead of getting something like this:

https://i.imgur.com/q64emqN.png

If you make the changes i suggested it will look like this instead:

https://i.imgur.com/TcWkK02.png

**Comment by SLOKnightfall** [comment]
Fixed in next update
