### ISSUE TITLE
Outfit dropdown bug

### ISSUE THREAD

**Issue by Larsy93** [SLOKnightfall/BetterWardrobe#234]
When you have no outfits saved the dropdown looks like this, buggy and with no options visible to add outfits or anything. Disabling the addon and saving an outfit fixes this. Tried it with my normal addons enabled and with only BetterWardrobe enabled with the same results.

[With all addons enabled](https://i.gyazo.com/f8924e01f755129d943595a6daf17cc9.png)
[With only BetterWardrobe enabled](https://i.gyazo.com/a706f13091ce948d4410510133bc0492.jpg)

**Comment by SLOKnightfall** [comment]
Fixed in next update
