### ISSUE TITLE
Legion Artifact tab causing error. Wardrobe-Appearances.lua:1555: Usage: GameTooltip:SetText("text" [, color, wrap])

### ISSUE THREAD

**Issue by Ookami313** [SLOKnightfall/BetterWardrobe#238]
v3.9.8
Went to transmog my current Paladin's weapon with a Legion artifact skin and received the following error when I used the drop down menu to show/select the Legion Artifacts. Thanks.

Edit: Just noticed, it's not showing any of the The Silver Hand skins in the Legion Artifacts panel, only the skins for Ashbringer.

1x BetterWardrobe\Modules\Wardrobe-Appearances.lua:1555: Usage: GameTooltip:SetText("text" [, color, wrap])
[string "=[C]"]: in function `SetText'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:1555: in function `SetAppearanceTooltip'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:2879: in function `RefreshAppearanceTooltip'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:2869: in function `SetAppearanceTooltip'
[string "@BetterWardrobe\Modules\Wardrobe-Appearances.lua"]:3065: in function <BetterWardrobe\Modules\Wardrobe.lua:3041>

Locals:
(*temporary) = GameTooltip {
 BottomLeftCorner = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
 SetHyperlink = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 SetSocketGem = <function> defined =[C]:-1
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
 Show = <function> defined =[C]:-1
 default = 1
 SetLootItem = <function> defined =[C]:-1
 ttGradient = <unnamed> {
 }
 numMoneyFrames = 1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetWeeklyReward = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined =[C]:-1
 0 = <userdata>
 BottomOverlay = <unnamed> {
 }
 SetBackpackToken = <function> defined =[C]:-1
 ttIcon = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = <unnamed> {
 }
 ttCount = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 ItemTooltip = <unnamed> {
 }
 CIMI_tooltipWritten = false
 SetBagItem = <function> defined =[C]:-1
 RightEdge = <unnamed> {
 }
 SetAction = <function> defined =[C]:-1
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
 LeftEdge = <unnamed> {
 }
 SetAuctionItem = <function> defined =[C]:-1
 SetLFGDungeonReward = <function> defined @AllTheThings\AllTheThings.lua:5866
 SetCurrencyByID = <function> defined @AllTheThings\AllTheThings.lua:5802
 FadeOut = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 hasMoney = 1
 TopRightCorner = <unnamed> {
 }
 SetHeirloomByItemID = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 factionID = 2407
 progressBarPool = <table> {
 }
 SetCurrencyToken = <function> defined @Altoholic\Tooltip.lua:756
 SetGuildBankItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 owner = <unnamed> {
 }
 SetOwner = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetAuctionSellItem = <function> defined =[C]:-1
 comparing = false
 textRight2Font = "GameTooltipText"
 BottomRightCorner = <unnamed> {
 }
 ClearLines = <function> defined =[C]:-1
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
 waitingForData = false
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:462
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:400
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 updateTooltipTimer = 0.046000
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
 SetToyByItemID = <function> defined =[C]:-1
 widgetContainer = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 backdropInfo = <table> {
 }
 SetInboxItem = <function> defined =[C]:-1
 SetIconTextureAndText = <function> defined @TipTacItemRef\ttItemRef.lua:62
 TextLeft1 = GameTooltipTextLeft1 {
 }
 SetExistingSocketGem = <function> defined =[C]:-1
 SetLFGDungeonShortageReward = <function> defined @AllTheThings\AllTheThings.lua:5883
 Center = <unnamed> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
 SetTradeTargetItem = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 TextRight1 = GameTooltipTextRight1 {
 }
 BottomEdge = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 TextRi

**Comment by SLOKnightfall** [comment]
Thanks for the bug report.   When at the transmog vendor the Legion Artifacts section of the weapons dropdown only show the artifact skins available for your current spec.  If you want to mog it to one of the other spec appearance, they are selected via the normal weapon section.  I'll see if it might be possible to add the other skins when viewing the artifact section

**Comment by Ookami313** [comment]
OK, Good to know, thanks. I was under the impression that when they opened up all skins for available use that all 2-Handed skins (Ret/Holy) would be viewable. I was able to find them in the normal list for 2-Handed hammers like you stated, so I thought it might be a bug. Feel free to disregard that part of the report. Thanks again.

**Comment by SLOKnightfall** [comment]
The Legion Artifact section is somewhat of a legacy section from how things originally worked where the current spec artifact skins can be used over different weapon types, while the off spec appearances can only be mogged over compatible weapon types.  I played around with the code a little and was able to get the other appearances to be listed in that section now and be able to have the transmog applied which will make using off spec appearances much easier vs trying to find them.
