### ISSUE TITLE
error when preview an obtainable legion artifact appearance

### ISSUE THREAD

**Issue by soso-15** [SLOKnightfall/BetterWardrobe#239]
When I ctrl+click an artifact apearance that I have not unlocked, this error will show up:

Message: Interface\FrameXML\CollectionsUtil.lua:71: bad argument #1 to 'sort' (table expected, got nil)
Time: Sun Aug 22 08:35:01 2021
Count: 1
Stack: Interface\FrameXML\CollectionsUtil.lua:71: bad argument #1 to 'sort' (table expected, got nil)
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:2781: in function `GetAnAppearanceSourceFromVisual'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:2077: in function `DressUpVisual'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:3019: in function <Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:3000>

Locals: self = <unnamed> {
 0 = <userdata>
 ClearAppearanceTooltip = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2882
 ShadowCornerTopRight = <unnamed> {
 }
 IsAppearanceUsableForActiveCategory = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2957
 GoToSourceID = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2836
 SortVisuals = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2406
 ModelR1C2 = <unnamed> {
 }
 transmogLocation = <table> {
 }
 OnUnitModelChangedEvent = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2183
 OnShow = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2016
 ShadowCornerLeft = <unnamed> {
 }
 ModelR1C6 = <unnamed> {
 }
 UpdateSlotButtons = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2887
 BGCornerFilagreeBottomLeft = <unnamed> {
 }
 tooltipVisualID = 31208
 lastWeaponCategory = 29
 GetActiveCategory = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2197
 ShadowCornerRight = <unnamed> {
 }
 ModelR3C2 = <unnamed> {
 }
 UpdateProgressBar = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2737
 SetActiveCategory = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2302
 ModelR1C5 = <unnamed> {
 }
 BGCornerBottomLeft = <unnamed> {
 }
 SelectVisual = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2793
 FilterVisuals = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2377
 GetAnAppearanceSourceFromVisual = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2778
 BGCornerTopRight = <unnamed> {
 }
 ModelR1C1 = <unnamed> {
 }
 ShadowCornerBottomLeft = <unnamed> {
 }
 SlotsFrame = <unnamed> {
 }
 Bg = <unnamed> {
 }
 HiddenModel = <unnamed> {
 }
 OverlayShadowBottomLeft = <unnamed> {
 }
 ModelR2C6 = <unnamed> {
 }
 NineSlice = <unnamed> {
 }
 OnLoad = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:1939
 CheckHelpTip = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:1959
 OverlayShadowLeft = <unnamed> {
 }
 visualsList = <table> {
 }
 SetTransmogrifierAppearancesShown = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2270
 activeCategory = 29
 PAGE_SIZE = 18
 SetAppearanceTooltip = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2860
 ChangeModelsSlot = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2114
 RefreshVisualsList = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2754
 ShadowLineTop = <unnamed> {
 }
 NUM_ROWS = 3
 OverlayShadowRight = <unnamed> {
 }
 CreateSlotButtons = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:1857
 ResetPage = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2350
 BackgroundTile = <unnamed> {
 }
 ModelR3C1 = <unnamed> {
 }
 ModelR2C3 = <unnamed> {
 }
 CanHandleKey = <function> defined @Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2089
 ModelR3C6 = <unnamed> {
 }
 RightClickDropDown = BetterWardrobeModelRightClickDropDown {
 }
 BGCornerBottomRight = <unnamed> {
 }
 OverlayShadowTop = <unnamed> {
 }
 Models = <table> {
 }
 ShadowCornerTop = <unnamed> {
 }
 Model

**Comment by SLOKnightfall** [comment]
Fixed in next update
