### ISSUE TITLE
Ctrl + Clicking item is previewing applied transmog appearance

### ISSUE THREAD

**Issue by Ketrel** [SLOKnightfall/BetterWardrobe#243]
Normally one could preview a piece of gear by ctrl + clicking it and you'd see the actual gear's appearance.

Since one of the recent updates (not sure which one) ctrl + clicking previews the applied transmog appearance instead of the actual item's appearance.

**Comment by SLOKnightfall** [comment]
It appears that this was a change on Blizzard's end.  Ctrl + Clicking an item with the addon disabled previews the transmog appearance still.

**Comment by Ketrel** [comment]
Ok, this is odd, I'm on another toon (addon is enabled) and it's not happening.

I'm going to dig a bit deeper and will update.

**Comment by Ketrel** [comment]
It's Mogit.  

Mogit enabled = Ctrl + Click previews real item appearance  
Mogit disabled = Ctrl + Click previews applied xmog appearance

**Comment by Ketrel** [comment]
I should turn this into an enhancement request to make it an option in this addon :p

**Comment by Ketrel** [comment]
Closing this since it's a non-issue, and not associated with this addon.
