### ISSUE TITLE
"Moving "dead" Pixel" caused by Better Wardrobe

### ISSUE THREAD

**Issue by Avarien29** [SLOKnightfall/BetterWardrobe#247]
https://i.imgur.com/kbAYzoR.png

There's a moving pixel ever since around November, but only noticeable on my Highmountain Character ( faction changed yesterday ).
It's starts white, goes brown > black over the span of one or two seconds, disappears for one or two seconds, repeats infinetly.

**Comment by SLOKnightfall** [comment]
I updated the position of a few watcher frames that get created that might be causing the issue.  Let me know if you still experience it after the next update and I'll dig further.

**Comment by Avarien29** [comment]
It's still there after the update :)

**Comment by SLOKnightfall** [comment]
Should be finally fixed in V3.15
