### ISSUE TITLE
Dressing room visual bug/text overlapping

### ISSUE THREAD

**Issue by antedap** [SLOKnightfall/BetterWardrobe#248]
Hello, the dressing room is currently messed up.

If I disable the addon I see the normal blizzard dressing room, but with the addon enabled I get this, which is a mix of the 2 UI.
Or maybe there is a conflict with ElvUI

http://prntscr.com/22ap68q

**Comment by aislyrith** [comment]
I've had the same issue for several months and I'm using the default wow UI.

**Comment by SLOKnightfall** [comment]
Fixed in next update
