### ISSUE TITLE
Host the addon outside of CurseForge

### ISSUE THREAD

**Issue by JVemmer** [SLOKnightfall/BetterWardrobe#250]
As CurseForge is locking out everyone except Overwolf's own addon manager (source: [https://www.wowhead.com/news/ads-revenue-and-api-wowup-and-overwolf-split-over-addon-development-325912](https://www.wowhead.com/news/ads-revenue-and-api-wowup-and-overwolf-split-over-addon-development-325912)), please host this addon elsewhere than CurseForge (at least co-host it elsewhere). Options include:

- Hosting a .zip file of the addon here in the GitHub repository (this allows WowUp to pull it down)
- Hosting it on WowUpHub website
- Hosting it on wago.io (allows monetization to continue, if that is a concern)
- Hosting it on TukUI
- Hosting it on WowInterface

I am personally using WowUp to update addons, and while I very much respect that some addon creators want their work monetized, and believe that they should have the option, I do not support the Overwolf lock-out simply because they want everyone to use their app. If monetization is a priority, I suggest using wago.io as addon hosting, as it allows for monetization of addons, also while using WowUp; which shows they're willing to find solutions, rather than the Overwolf approach of refusing to cooperate.
I don't mind anyone hosting their addons on CurseForge, but please, please, please host it outside of CurseForge as well, for those of us who would like to cut ties with CurseForge, but still use your amazing addon :heart:

**Comment by SLOKnightfall** [comment]
Its definitely something I plan to do, especially with the new changes to Curseforge.

**Comment by stevietv** [comment]
curseforge API is now down, any chance you will be hosting elsewhere, or releases on github?

**Comment by SLOKnightfall** [comment]
Its still something that is being worked on.  Unfortunately I've little free time to work on addons right now so there is no ETA

**Comment by stevietv** [comment]
no worries, perhaps this GH action is of interest to you: https://github.com/marketplace/actions/wow-packager
ref also #257

**Comment by SLOKnightfall** [comment]
Thanks.  That will come in very handy.

**Comment by lyledouglass** [comment]
I created a PR to implement this. Hope it helps! https://github.com/SLOKnightfall/BetterWardrobe/pull/271

**Comment by SLOKnightfall** [comment]
Thanks @lyledouglass for the PR.  The addon is now set to create packaged releases and is also being hosted on wago.io   https://addons.wago.io/addons/betterwardrobe
