### ISSUE TITLE
Can't inspect weapons after new version

### ISSUE THREAD

**Issue by rainfordays** [SLOKnightfall/BetterWardrobe#26]
Last version fixed a lot of lua errors but now whenever I try inspecting a weapon it just flashes* the weapon and then removes it from the model. 
*(Flash as in the model gets loaded then unloaded immediately)

**Comment by SLOKnightfall** [comment]
Looks like there the "Hide weapon" option is the causing the issue and is hiding the preview instead of hiding weapons initially and then displaying the preview like intended.

**Comment by rainfordays** [comment]
Quick reply and right on the money. Disabled it for now, thanks.

**Comment by SLOKnightfall** [comment]
Fixed in the next release
