### ISSUE TITLE
9.2.5 update

### ISSUE THREAD

**Issue by zaphon** [SLOKnightfall/BetterWardrobe#263]
FYI Blizzard seems to have made some changes to the C_TransMogCollection category of API calls which breaks the addon. I tried this on the PTR yesterday, and any addon that was touching these calls is having issues.

**Comment by Fangzthewolf** [comment]
I am also having issues on live (9.2.5) with this addon. It is generating a lot of lua errors.

**Comment by Debuggernaut** [comment]
d'oh, hopefully @SLOKnightfall will have a chance to fix this soon

**Comment by Ketrel** [comment]
I'm going to look at it as well but I won't even get a chance until the weekend.  
(I'm not familiar with this new dropdown stuff that came out in 9.2.5 so I don't even want to say THAT much.)

**Comment by morticianoire** [comment]
im getting errors, ive deleted the addon and still getting the same error...

**Comment by SLOKnightfall** [comment]
I'm working on an update.  The api changes broke in a lot of places so its taking a little bit of time to fix.  Didn't help that the game update didnt get done until later in the evening when I didn't have a lot of time to work on it.

**Comment by SLOKnightfall** [comment]
V3.15 should fix the issues caused by the 9.2.5 api changes
