### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by HyperMac** [SLOKnightfall/BetterWardrobe#265]
Sorry to still bother, but for whatever reason the color picker tool is not working properly, and does not let me pick a color.
I had "Can i mog it" installed before. but made sure it was uninstalled, reinstalled "BetterWardrobe" from scratch, made sure only it and bug grabber were enabled, and still got the same issue.
```
3427x Usage: local appearances = C_TransmogCollection.GetCategoryAppearances(category, transmogLocation)
[string "=[C]"]: in function `GetCategoryAppearances'
[string "@CanIMogIt\code.lua"]:409: in function <CanIMogIt\code.lua:404>
[string "@CanIMogIt\code.lua"]:456: in function <CanIMogIt\code.lua:452>
[string "@CanIMogIt\code.lua"]:502: in function <CanIMogIt\code.lua:496>

Locals:
(*temporary) = "Usage: local appearances = C_TransmogCollection.GetCategoryAppearances(category, transmogLocation)"

```

**Comment by Hyphie24** [comment]
Wanted to verify, having same issue

**Comment by SLOKnightfall** [comment]
Fixed in the next update
