### ISSUE TITLE
LUA error when attempting to right click an appearance on the items tab

### ISSUE THREAD

**Issue by Fangzthewolf** [SLOKnightfall/BetterWardrobe#267]
With the latest version of Better Wardrobe (3.15.2), a lua error will generate if you right click an appearance in the items tab of the appearances tab.

The following LUA error is generated instead of showing the list of sources for that appearance:

**Message: Usage: local sources = C_TransmogCollection.GetAppearanceSources(appearanceID, categoryType, transmogLocation)
Time: Thu Jun  2 22:19:26 2022
Count: 2
Stack: Usage: local sources = C_TransmogCollection.GetAppearanceSources(appearanceID, categoryType, transmogLocation)
[string "=[C]"]: in function `GetAppearanceSources'
[string "@Interface\FrameXML\CollectionsUtil.lua"]:76: in function `GetSortedAppearanceSources'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:3404: in function `initFunction'
[string "@Interface\AddOns\BetterWardrobe\Libs\UIDropDownMenu\UIDropDownMenu.lua"]:78: in function `BW_UIDropDownMenu_Initialize'
[string "@Interface\AddOns\BetterWardrobe\Libs\UIDropDownMenu\UIDropDownMenu.lua"]:1055: in function `BW_ToggleDropDownMenu'
[string "@Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua"]:3016: in function <Interface\AddOns\BetterWardrobe\Modules\Wardrobe.lua:2978>

Locals: (*temporary) = "Usage: local sources = C_TransmogCollection.GetAppearanceSources(appearanceID, categoryType, transmogLocation)"**

**Comment by SLOKnightfall** [comment]
Issue appears to be fixed
