### ISSUE TITLE
Login error after updating to newest version (3.15.2).

### ISSUE THREAD

**Issue by Ookami313** [SLOKnightfall/BetterWardrobe#269]
Updated to 3.15.2 and I'm receiving the following error when I log into the game. Thanks.

2x Usage: local sources = C_TransmogCollection.GetAppearanceSources(appearanceID, categoryType, transmogLocation)
[string "=[C]"]: in function `GetAppearanceSources'
[string "@BetterWardrobe\Data\DataBase.lua"]:330: in function <BetterWardrobe\Data\DataBase.lua:323>
[string "@BetterWardrobe\Data\DataBase.lua"]:348: in function `BuildDB'
[string "@BetterWardrobe\Data\DataBase.lua"]:343: in function `InitDB'
[string "@BetterWardrobe\Modules\Core.lua"]:1268: in function <BetterWardrobe\Modules\Core.lua:1263>
[string "=[C]"]: ?
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@Rarity\Core\Collections-Collections.lua"]:63: in function `ScanToys'
...
[string "@PetTracker\libs\WildAddon-1.0\WildAddon-1.0-1.lua"]:56: in function <...dOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...eIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:591: in function `CombatLog_LoadUI'
[string "@FrameXML\UIParent.lua"]:1456: in function <FrameXML\UIParent.lua:1337>
[string "=[C]"]: ?

**Comment by Ookami313** [comment]
Just received the following error when I tried to CTRL-Click an item to look at it. Thanks.

3x ...rfaceBetterWardrobe\Modules\DressingRoom.lua:244: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@BetterWardrobe\Modules\DressingRoom.lua"]:244: in function <...rfaceBetterWardrobe\Modules\DressingRoom.lua:237>
[string "@BetterWardrobe\Modules\DressingRoom.lua"]:523: in function <...rfaceBetterWardrobe\Modules\DressingRoom.lua:522>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by SLOKnightfall** [comment]
Should be fixed in next build
