### ISSUE TITLE
Extra Set and Saved Tabs missing

### ISSUE THREAD

**Issue by Whippoorwill87** [SLOKnightfall/BetterWardrobe#273]
I had to reinstall WoW this week and afterwards, this addon is missing the Extra and Saved tabs.  I've tried several things, uninstalling and reinstalling and it is missing on all my characters.  The Dressing room features are working as intended.

**Comment by Whippoorwill87** [comment]
I compared my Better Wardrobe folder with a friends that was working and noticed I was missing modules.  So I deleted my Better Wardrobe folder and used the "Download" instead of "Install" and that fixed the issue.  All the missing modules were present and my missing tabs were back.

**Comment by panseit** [comment]
I am facing the same issue with the latest version atm (4.1.3) and installing/reinstalling/redownloading didn't fix the issue.
