### ISSUE TITLE
Feature Request: Sort saved sets alphabetical

### ISSUE THREAD

**Issue by Beet4** [SLOKnightfall/BetterWardrobe#275]
It would help very much if we could have a setting to sort the saved sets alphabetical in the apperances window as well as the dropdown menu in dressing room and transmog window (and saved sets tab in transmog window as well). When you have a lot of saved sets like me it easily gets messy. With alphabetical sorting I could sort completed sets at the top by applying for example # in front of the names. MogIt and MogIt SetTransmog does this and it's much cleaner. 

Thanks in advance! :) Some pictures to see why it would be helpful:

![image](https://user-images.githubusercontent.com/38279393/185766875-bbc9afef-510b-4001-bb6e-87a01ef5e34c.png)
![image](https://user-images.githubusercontent.com/38279393/185766923-f1c282ac-b1af-4d72-a815-a9eacf83fc86.png)
![image](https://user-images.githubusercontent.com/38279393/185766941-07e835d4-03a8-4fc2-896e-63f9897e9ae5.png)
![image](https://user-images.githubusercontent.com/38279393/185767050-7f51dce3-e2c7-419d-a0e2-df77ca95b0ea.png)

**Comment by SLOKnightfall** [comment]
Sorry it took so long to get implemented.  Saved sets are now sorted alphabetically in the saved sets area and dropdown

**Comment by dhaern** [comment]
Can you add more sorting options please? I would like we can choose more choices in the addon options because I was used to old one before last update. Maybe add sort from most recent to oldest besides alphabetically or more options you can think.

Thanks.
