### ISSUE TITLE
Collection List only shows collected appearances

### ISSUE THREAD

**Issue by Beet4** [SLOKnightfall/BetterWardrobe#279]
Collection List only shows collected appearances, not collected appearances are not shown in the list at all. They only show up in the Detailed List/Shopping List. Please see screenshot below:

![image](https://user-images.githubusercontent.com/38279393/185770243-b9c50cb7-27fb-480d-a5f8-c2e70b8641ab.png)

![image](https://user-images.githubusercontent.com/38279393/185770269-3b80c310-3025-420c-afc1-1aea473f0b8c.png)

**Comment by jbleijenberg-ehvg** [comment]
I've noticed it too, Vanilla WoW also doesn't show non-collected items anymore. So i maybe the API changed and that's the reason it doesn't work in BW either

**Comment by Beet4** [comment]
Seems to be fixed in https://github.com/SLOKnightfall/BetterWardrobe/tree/4.5
