### ISSUE TITLE
Support for packaged releases

### ISSUE THREAD

**Issue by Xionyus** [SLOKnightfall/BetterWardrobe#283]
Any way you could add packaged releases for this addon? I really enjoy using it but I would like to keep it updated through an addon manager other than curse and doing this would allow a ton of us access to do this. I figured I would ask, thank you!

**Comment by SLOKnightfall** [comment]
The addon is now set to create packaged releases and is also being hosted on wago.io   https://addons.wago.io/addons/betterwardrobe
