### ISSUE TITLE
"BetterWardrobe has been blocked from an action..." & LUA Error

### ISSUE THREAD

**Issue by nearlysober80** [SLOKnightfall/BetterWardrobe#285]
When entering "Edit Mode" to adjust my bars/layout in 10.0 getting the warning message that "BetterWardrobe has been blocked from an action only available to the Blizzard UI.  You can disable this addone and reload the UI" and the option to Disable or Ignore.

Hitting Ignore seems to dismiss it without issue.   I am also seeing 2 LUA errors in 10.0 - one might be related to CanIMogIt?

**#1 (CanIMogIt) reference:** 
Message: ...nterface/AddOns/BetterWardrobe/Plugins/CanIMogIt.lua:67: attempt to index field 'BetterWardrobeCollectionFrameScrollFrameScrollBar' (a nil value)
Time: Wed Oct 26 14:02:55 2022
Count: 1
Stack: ...nterface/AddOns/BetterWardrobe/Plugins/CanIMogIt.lua:67: attempt to index field 'BetterWardrobeCollectionFrameScrollFrameScrollBar' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/BetterWardrobe/Plugins/CanIMogIt.lua"]:67: in function `UpdateCanIMogIt'
[string "@Interface/AddOns/BetterWardrobe/Modules/Core.lua"]:1368: in function `LoadModules'
[string "@Interface/AddOns/BetterWardrobe/Modules/Core.lua"]:1376: in function `?'
[string "@Interface/AddOns/CanIMogIt/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...gIt/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/CanIMogIt/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...gIt/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/CanIMogIt/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/CanIMogIt/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../AddOns/CanIMogIt/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:530: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:704: in function `CollectionsJournal_LoadUI'
[string "@Interface/FrameXML/UIParent.lua"]:1152: in function `SetCollectionsJournalShown'
[string "@Interface/FrameXML/UIParent.lua"]:1146: in function `ToggleCollectionsJournal'
[string "TOGGLECOLLECTIONSPETJOURNAL"]:1: in function <[string "TOGGLECOLLECTIONSPETJOURNAL"]:1>

Locals: <none>

**2nd LUA Error:**
Message: Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1220: attempt to index global 'BW_DBSavedSetDropdown' (a nil value)
Time: Wed Oct 26 14:03:07 2022
Count: 1
Stack: Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1220: attempt to index global 'BW_DBSavedSetDropdown' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:1220: in function `SetTab'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:1184: in function `SetContainer'
[string "@Interface/AddOns/BetterWardrobe/Modules/Core.lua"]:1334: in function <Interface/AddOns/BetterWardrobe/Modules/Core.lua:1326>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `CollectionsJournal_UpdateSelectedTab'
[string "@Interface/AddOns/Blizzard_Collections/Blizzard_Collections.lua"]:6: in function `CollectionsJournal_SetTab'
[string "*Blizzard_Collections.xml:7_OnClick"]:1: in function <[string "*Blizzard_Collections.xml:7_OnClick"]:1>

Locals:

**Comment by SLOKnightfall** [comment]
Found and fixed the UI Editor Taint in the next release.

**Comment by SLOKnightfall** [comment]
The last 2 errors are fixed in the 4.1 update
