### ISSUE TITLE
Multiple Lua Errors

### ISSUE THREAD

**Issue by TPetersen5171** [SLOKnightfall/BetterWardrobe#286]
Getting 2 Lua Errors when opening transmogrify and hover mouse over any transmog pieces:

1st Lua Error:

Message: Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2890: attempt to call field 'GetVisibilityWarning' (a nil value)
Time: Thu Oct 27 16:51:40 2022
Count: 19
Stack: Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2890: attempt to call field 'GetVisibilityWarning' (a nil value)
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:2890: in function `RefreshAppearanceTooltip'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:2880: in function `SetAppearanceTooltip'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:3073: in function <Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3047>

Locals: self = Frame {
 0 = <userdata>
 ClearAppearanceTooltip = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2894
 ShadowCornerTopRight = Texture {
 }
 IsAppearanceUsableForActiveCategory = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2969
 GoToSourceID = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2844
 SortVisuals = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2350
 ModelR1C2 = DressUpModel {
 }
 transmogLocation = <table> {
 }
 OnUnitModelChangedEvent = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2077
 OnShow = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1908
 ShadowCornerLeft = Texture {
 }
 tooltipVisualID = 36123
 ModelR1C6 = DressUpModel {
 }
 UpdateSlotButtons = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2899
 BGCornerFilagreeBottomLeft = Texture {
 }
 tooltipModel = DressUpModel {
 }
 ModelR2C3 = DressUpModel {
 }
 GetActiveCategory = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2091
 ShadowCornerRight = Texture {
 }
 ModelR3C2 = DressUpModel {
 }
 UpdateProgressBar = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2683
 SetActiveCategory = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2196
 ModelR1C5 = DressUpModel {
 }
 ShadowCornerTopLeft = Texture {
 }
 BGCornerBottomLeft = Texture {
 }
 SelectVisual = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2768
 FilterVisuals = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2276
 GetAnAppearanceSourceFromVisual = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2751
 BGCornerTopRight = Texture {
 }
 ModelR1C1 = DressUpModel {
 }
 ShadowCornerBottomLeft = Texture {
 }
 SlotsFrame = Frame {
 }
 Bg = Texture {
 }
 HiddenModel = DressUpModel {
 }
 OverlayShadowBottomLeft = Texture {
 }
 ModelR2C6 = DressUpModel {
 }
 NineSlice = Frame {
 }
 OnLoad = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1830
 CheckHelpTip = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1851
 OverlayShadowLeft = Texture {
 }
 visualsList = <table> {
 }
 SetTransmogrifierAppearancesShown = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2164
 activeCategory = 1
 PAGE_SIZE = 18
 SetAppearanceTooltip = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2868
 ChangeModelsSlot = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2006
 RefreshVisualsList = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2701
 ShadowLineTop = Texture {
 }
 NUM_ROWS = 3
 OverlayShadowRight = Texture {
 }
 CreateSlotButtons = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1748
 ResetPage = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2247
 BackgroundTile = Texture {
 }
 ModelR3C1 = DressUpModel {
 }
 CanHandleKey = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1981
 ModelR3C6 = DressUpModel {
 }
 RightClickDropDown = BetterWardrobeModelRightClickDropDown {
 }
 BGCornerBottomRight = Texture {
 }
 OverlayShadowTop

Second Lua Error

Message: Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2890: attempt to call field 'GetVisibilityWarning' (a nil value)
Time: Thu Oct 27 16:51:32 2022
Count: 1
Stack: Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2890: attempt to call field 'GetVisibilityWarning' (a nil value)
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:2890: in function `RefreshAppearanceTooltip'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:2880: in function `SetAppearanceTooltip'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:3073: in function `OnEnter'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:2610: in function `UpdateItems'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:2272: in function `ResetPage'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:2863: in function `GoToSourceID'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:424: in function `SelectSlotButton'
[string "@Interface/AddOns/BetterWardrobe/Modules/Core.lua"]:1356: in function <Interface/AddOns/BetterWardrobe/Modules/Core.lua:1356>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SelectSlotButton'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:499: in function `Update'
[string "@Interface/AddOns/BetterWardrobe/Modules/Core.lua"]:1360: in function <Interface/AddOns/BetterWardrobe/Modules/Core.lua:1360>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetPendingTransmog'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:2832: in function `SelectVisual'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:3029: in function <Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3004>

Locals: self = Frame {
 0 = <userdata>
 ClearAppearanceTooltip = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2894
 ShadowCornerTopRight = Texture {
 }
 IsAppearanceUsableForActiveCategory = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2969
 GoToSourceID = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2844
 SortVisuals = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2350
 ModelR1C2 = DressUpModel {
 }
 transmogLocation = <table> {
 }
 OnUnitModelChangedEvent = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2077
 OnShow = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1908
 ShadowCornerLeft = Texture {
 }
 tooltipVisualID = 32535
 ModelR1C6 = DressUpModel {
 }
 UpdateSlotButtons = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2899
 BGCornerFilagreeBottomLeft = Texture {
 }
 tooltipModel = DressUpModel {
 }
 ModelR2C3 = DressUpModel {
 }
 GetActiveCategory = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2091
 ShadowCornerRight = Texture {
 }
 ModelR3C2 = DressUpModel {
 }
 UpdateProgressBar = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2683
 SetActiveCategory = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2196
 ModelR1C5 = DressUpModel {
 }
 ShadowCornerTopLeft = Texture {
 }
 BGCornerBottomLeft = Texture {
 }
 SelectVisual = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2768
 FilterVisuals = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2276
 GetAnAppearanceSourceFromVisual = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:2751
 BGCornerTopRight = Texture {
 }
 ModelR1C1 = DressUpModel {
 }
 ShadowCornerBottomLeft = Texture {
 }
 SlotsFrame = Frame {
 }
 Bg = Texture {
 }
 HiddenModel = DressUpModel {
 }
 OverlayShadowBottomLeft = Texture {
 }
 ModelR2C6 = DressUpModel {
 }
 NineSlice = Frame {
 }
 OnLoad = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1830
 CheckHelpTip = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lu

also the item names are no longer showing for any of the transmog items, I love this addon but the errors are a major issue.

**Comment by SLOKnightfall** [comment]
Should be fixed in the 4.0 release
