### ISSUE TITLE
Interface/AddOns/BetterWardrobe/Plugins/ElvUI.lua:214: attempt to index field 'ScrollFrame' (a nil value)

### ISSUE THREAD

**Issue by Beet4** [SLOKnightfall/BetterWardrobe#288]
Just tested the newest build 4.0.1 together with ElvUI and got this LUA error upon loading into the game.

1x Interface/AddOns/BetterWardrobe/Plugins/ElvUI.lua:214: attempt to index field 'ScrollFrame' (a nil value)
[string "@Interface/AddOns/BetterWardrobe/Plugins/ElvUI.lua"]:214: in function <Interface/AddOns/BetterWardrobe/Plugins/ElvUI.lua:117>

Locals:
WardrobeCollectionFrame = BetterWardrobeCollectionFrame {
 GetAppearanceItemHyperlink = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1644
 SetsTab = BetterWardrobeCollectionFrameTab2 {
 }
 searchBox = BetterWardrobeCollectionFrameSearchBox {
 }
 GetActiveTab = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1316
 progressBar = StatusBar {
 }
 selectedTransmogTab = 1
 ContentFrames = <table> {
 }
 VisualToggle = BetterWardrobeVisualToggle {
 }
 OnKeyDown = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1519
 SetContainer = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1170
 GoToSet = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1596
 OnShow = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1460
 ClickTab = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1200
 ItemsTab = BetterWardrobeCollectionFrameTab1 {
 }
 SavedSetsTab = BetterWardrobeCollectionFrameTab4 {
 }
 SetSearch = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1693
 HideAppearanceTooltip = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1615
 GetSearchType = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1708
 SetTab = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1207
 GoToItem = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1587
 UpdateTabButtons = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1601
 UpdateProgressBar = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1655
 selectedCollectionTab = 1
 OpenTransmogLink = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1540
 RestartSearchTracking = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1679
 Tabs = <table> {
 }
 SetsTransmogFrame = Frame {
 }
 SwitchSearchCategory = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1661
 SetsCollectionFrame = Frame {
 }
 ReloadTab = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1157
 ItemsCollectionFrame = Frame {
 }
 FilterButton = Button {
 }
 BW_SetsHideSlotButton = Button {
 }
 TransmogOptionsButton = BW_TransmogOptionsButton {
 }
 ExtraSetsTab = BetterWardrobeCollectionFrameTab3 {
 }
 GetAppearanceNameTextAndColor = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1635
 FilterDropDown = BetterWardrobeFilterDropDown {
 }
 OnLoad = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1324
 OnHide = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1495
 SearchBox = BetterWardrobeCollectionFrameSearchBox {
 }
 CheckTab = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1163
 OnEvent = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1338
 0 = <userdata>
 numTabs = 4
 RefreshCameras = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1629
 SetAppearanceTooltip = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1606
 ClearSearch = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1702
 GetAppearanceSourceTextAndColor = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1640
 selectedTab = 1
 UpdateUsableAppearances = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:1622
}
SetsCollectionFrame = Frame {
 BottomLeftCorner = Texture {
 }
 ClearAppearanceTooltip = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:5884
 LinkSetInChat = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:5943
 Center = Texture {
 }
 GetDefaultSetIDForBaseSet = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:5766
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 0 = <userdata>
 LeftInset = Frame {
 }
 GetBackdropCo

**Comment by fraerie** [comment]
GEtting the sam eor similar error:

1x ...nterface/AddOns/BetterWardrobe/Plugins/CanIMogIt.lua:67: attempt to index field 'BetterWardrobeCollectionFrameScrollFrameScrollBar' (a nil value)
[string "@Interface/AddOns/BetterWardrobe/Plugins/CanIMogIt.lua"]:67: in function `UpdateCanIMogIt'
[string "@Interface/AddOns/BetterWardrobe/Modules/Core.lua"]:1368: in function `LoadModules'
[string "@Interface/AddOns/BetterWardrobe/Modules/Core.lua"]:1287: in function <Interface/AddOns/BetterWardrobe/Modules/Core.lua:1287>

Locals:
self = <table> {
 TransmogVendorSizeUpdated = true
 ViewDelay = 3
 useAltSet = false
 modules = <table> {
 }
 Sort = <table> {
 }
 SecureHook = <function> defined @Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua:335
 tooltip = BW_ProfileTooltip {
 }
 GetBlizzID = <function> defined @Interface/AddOns/BetterWardrobe/Data/DataBase.lua:408
 MogIt = <table> {
 }
 IsEnabled = <function> defined @Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 GetActiveCategory = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:217
 RefreshCharConfig = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Core.lua:1157
 RegisterMessage = <function> defined @Interface/AddOns/Accountant/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterMessage = <function> defined @Interface/AddOns/Accountant/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 validSetCache = <table> {
 }
 GetBaseList = <function> defined @Interface/AddOns/BetterWardrobe/Data/DataBase.lua:392
 db = <table> {
 }
 SetEnabledState = <function> defined @Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua:273
 GetSourceFromItem = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Tooltips.lua:212
 InitExtendedSetsSwap = <function> defined @Interface/AddOns/BetterWardrobe/Plugins/ExtendedTransmog.lua:6
 OnEnable = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Core.lua:1263
 RefreshOutfitData = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Core.lua:871
 GetArtifactSourceInfo = <function> defined @Interface/AddOns/BetterWardrobe/Modules/ArtifactAppearances.lua:288
 IsWeaponCat = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:222
 ItemAppearance = <table> {
 }
 OnInitialize = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Core.lua:1179
 itemSourceID = <table> {
 }
 ColorFilterButton = Button {
 }
 ColorFilterFrame = Button {
 }
 Globals = <table> {
 }
 SortSet = <function> defined @Interface/AddOns/BetterWardrobe/Modules/SortingFunctions.lua:672
 Deserialize = <function> defined @Interface/AddOns/Ace3/AceSerializer-3.0/AceSerializer-3.0.lua:246
 GetName = <function> defined @Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 C_TransmogCollection = <table> {
 }
 Camera = <table> {
 }
 name = "BetterWardrobe"
 UI = <table> {
 }
 Disable = <function> defined @Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 GetSetType = <function> defined @Interface/AddOns/BetterWardrobe/Data/DataBase.lua:626
 Unhook = <function> defined @Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua:417
 Print = <function> defined @Interface/AddOns/Accountant/Libs/AceConsole-3.0/AceConsole-3.0.lua:50
 IsFavoriteItem = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3496
 usableSourceCache = <table> {
 }
 ExtendTransmogView = <function> defined @Interface/AddOns/BetterWardrobe/Modules/TransmogVendor.lua:423
 BuildClassArtifactAppearanceList = <function> defined @Interface/AddOns/BetterWardrobe/Modules/ArtifactAppearances.lua:177
 Serialize = <function> defined @Interface/AddOns/Ace3/AceSerializer-3.0/AceSerializer-3.0.lua:122
 Init = <table> {
 }
 CreateChatLinkTransmogVendor = <function> defined @Interface/AddOns/BetterWardrobe/Modules/ImportExport.lua:299
 EventHandler = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Core.lua:1374
 SelecteSavedList = false
 CollectionList = <table> {
 }
 GetSetCounts = <function> defined @Interface/AddOns/BetterWardrobe/Modules/BlizzardAPI.lua:609
 RemoveItemSubstitute = <function> defined @Interface/AddOns/BetterWardrobe/Data/DataBase.lua:899
 UnregisterEvent = <function> defined @Interface/AddOns/Accountant/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 SetsDataProvider = <table> {
 }
 GetTransmogLocation = <function> defined @Interface/AddOns/Be

**Comment by SLOKnightfall** [comment]
Fixes for these are in the 4.1 update
