### ISSUE TITLE
Not working with Can I Mog It? addon, Is it safe to comment this line?

### ISSUE THREAD

**Issue by eivl** [SLOKnightfall/BetterWardrobe#289]
![betterwardrobe_canimogit_fix](https://user-images.githubusercontent.com/132364/198535863-d4e25ff8-c37d-409b-843f-72793b19ad61.gif)

Line 67 from `BetterWardrobe/Plugins/CanIMogIt.lua`

**Comment by eivl** [comment]
PS: The addon works on its own. it stops working in combination with Can I Mog It.

**Comment by Fluke667** [comment]
Same here stops with CaniMogit. Howto fix this?

**Comment by SLOKnightfall** [comment]
A fix for the Can I Mog It error is in the 4.1 update
