### ISSUE TITLE
[4.1.1] Missing close button on Transmogrify-window with ElvUI Skin

### ISSUE THREAD

**Issue by Beet4** [SLOKnightfall/BetterWardrobe#292]
In 4.1.1 there no longer is a close button in the upper right corner of the Transmogrify-window when using the ElvUI Skin, it's still clickable if you press in the right spot:

![image](https://user-images.githubusercontent.com/38279393/198721802-475ac766-d904-46c5-9fdc-8185b2782f63.png)

**Comment by Beet4** [comment]
So the button re-appeared again randomly at the same time the ElvUI integration broke again as per my comment here: https://github.com/SLOKnightfall/BetterWardrobe/issues/256#issuecomment-1295433549

**Comment by Beet4** [comment]
As per my comment https://github.com/SLOKnightfall/BetterWardrobe/issues/256#issuecomment-1295438930 the close button only seems to work when the skin breaks upon initially loading into the game. After a /reload the skin works again but the close button disappears.

**Comment by 0Neurotica0** [comment]
this issue also happens with any menus opened using betterwardrobe, mainly the details cageing list and item sources list.
![image](https://user-images.githubusercontent.com/116988400/198900418-13faa9c0-483a-4113-bbe8-281e2222db18.png)

**Comment by SLOKnightfall** [comment]
Should be fixed in the next update
