### ISSUE TITLE
Forced to use Elvui Skin when BetterWardrobe is enabled

### ISSUE THREAD

**Issue by pesrou** [SLOKnightfall/BetterWardrobe#294]
When this addon is enabled, the ElvUi skin is forced on the Transmog and Appearances tab, checked Elvui Skins tab, AddonSkins as well, the issue seems to be on BetterWardrobe. 
![Screenshot 2022-10-30 010523](https://user-images.githubusercontent.com/93722498/198858144-3f8e8571-24a5-4b79-b329-b64f6186d639.png)
![Screenshot 2022-10-30 010537](https://user-images.githubusercontent.com/93722498/198858145-eabeca35-a92e-4750-a295-035332f8b949.png)

**Comment by BobSMASHPC** [comment]
I have the same issue. New to this addon since Mogit is broken. Would love this to be fixed.

**Comment by Pairaka** [comment]
This is happening for me, too. Both the appearances tab and the Transmogrify screen (at a Transmogrifier or on the yak mount) are using ElvUI's skin, even though I have Blizzard skins enabled. 

In addition to this, the labels on the tab buttons along the top ("Sets", "Extra", and "Saved") are even further misaligned than in OP's screenshot. They overlap the top of the main section. 

![WoWScrnShot_103122_074447](https://user-images.githubusercontent.com/39540618/199000720-7a94e648-204d-40c0-9d79-edc8b3982a03.jpg)

**Comment by SLOKnightfall** [comment]
Should be fixed in the next update
