### ISSUE TITLE
Dropdown menus break in "Items" tab with ElvUI.

### ISSUE THREAD

**Issue by 0Neurotica0** [SLOKnightfall/BetterWardrobe#295]
Dropdown menus are enlarged in the items tab.
![image](https://user-images.githubusercontent.com/116988400/198859990-fdf632e1-a9ab-4fda-a3e8-a30cf3925c1d.png)

**Comment by supzfly** [comment]
same. 
![image](https://user-images.githubusercontent.com/37372446/198895594-00c265e6-17a0-4dcf-96f3-83d83f12edbe.png)

using elvui

**Comment by 0Neurotica0** [comment]
i'm sorry! i forgot to provide details. 
so far, this only happens in the items tab. with betterwardrobe disabled, there are no issues. similarly, there are no issues when i disable the elvui skin for the collections tab. when i do that, however, #276 occurs. i'm using ElvUI 12.97.

**Comment by Beet4** [comment]
Seems similar to https://github.com/SLOKnightfall/BetterWardrobe/issues/256#issuecomment-1295794846

**Comment by SLOKnightfall** [comment]
Should be fixed in the next update
