### ISSUE TITLE
Appearance tabs overlapping with collection progress bar

### ISSUE THREAD

**Issue by JBabbb** [SLOKnightfall/BetterWardrobe#297]
![image](https://user-images.githubusercontent.com/89645548/199503517-61090306-ab70-4e53-a5df-1003eda90d2b.png)

Just mentioning this issue, it used to go Ext... and Sav... to not go into the bar, now it just clashes into it.

Thanks for making one of the best addons in WoW! <3

**Comment by SLOKnightfall** [comment]
Fixed in next update.
