### ISSUE TITLE
Version 4.3 treated as newer than 4.3.1 on Curseforge

### ISSUE THREAD

**Issue by AySz88** [SLOKnightfall/BetterWardrobe#300]
Curseforge is [listing](https://www.curseforge.com/wow/addons/better-wardrobe-and-transmog/files) and installing version 4.3 over 4.3.1. It appears the [builds](https://github.com/SLOKnightfall/BetterWardrobe/actions/workflows/build.yml) fired simultaneously on push, and 4.3.1 finished earlier than 4.3.

(A few things also seem to be reading the addon version as "`@project-version@`", like the changelog.)

**Comment by SLOKnightfall** [comment]
Pushed a new update that should fix the issue.  The builder should be substituting the ""@project-version@" with the version number getting released, so ill have to see why it is not.
