### ISSUE TITLE
Visual error on Appearances tab

### ISSUE THREAD

**Issue by antedap** [SLOKnightfall/BetterWardrobe#302]
Hello, there are no LUA errors that pop up but the Appearances tab is kinda this
![Screenshot_16](https://user-images.githubusercontent.com/73392980/201083711-1ae4dd00-913a-43d0-91fd-8321ec48e63b.png)

**Comment by antedap** [comment]
The transmog tab is bugged too
![Uploading Screenshot_17.png…]()

**Comment by SLOKnightfall** [comment]
What Version of the addon are you using?  There was an issue where curseforge had set v 4.3 as the most recent version instead of 4.3.1 which should fix this issue

**Comment by SLOKnightfall** [comment]
Hopefully 4.3.2 fixes the issue

**Comment by antedap** [comment]
Yes, it is fixed :) thank you so much.

**Comment by SLOKnightfall** [comment]
Great to hear. :)
