### ISSUE TITLE
Protected BS

### ISSUE THREAD

**Issue by DePhoegon** [SLOKnightfall/BetterWardrobe#303]
1x [ADDON_ACTION_FORBIDDEN] AddOn 'BetterWardrobe' tried to call the protected function 'UseContainerItem()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseContainerItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1384: in function <Interface/FrameXML/ContainerFrame.lua:1294>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1435: in function <Interface/FrameXML/ContainerFrame.lua:1423>

**Comment by DePhoegon** [comment]
UUUUGGGG  The following NONSENSE..  it triggered in a dungeon with a level up, & now won't stop causing headaches.

```1x [ADDON_ACTION_BLOCKED] AddOn 'BetterWardrobe' tried to call the protected function 'MultiBarBottomLeft:SetPointBase()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPointBase'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:62: in function `SetPoint'
[string "@Interface/FrameXML/EditModeManager.lua"]:629: in function `UpdateBottomActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:555: in function `UpdateActionBarLayout'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:655: in function `UpdateGridLayout'
[string "@Interface/FrameXML/StanceBar.lua"]:73: in function `UpdateState'
[string "@Interface/FrameXML/StanceBar.lua"]:12: in function <Interface/FrameXML/StanceBar.lua:10>
[string "=[C]"]: ?```

```18x Interface/FrameXML/EditModeUtil.lua:22: attempt to perform arithmetic on local 'offsetX' (a nil value)
[string "@Interface/FrameXML/EditModeUtil.lua"]:22: in function `GetRightActionBarWidth'
[string "@Interface/FrameXML/EditModeUtil.lua"]:53: in function `GetRightContainerAnchor'
[string "@Interface/FrameXML/UIParent.lua"]:3082: in function `UIParentManageFramePositions'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3104: in function `UIParent_ManageFramePositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:641: in function `UpdateBottomActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:555: in function `UpdateActionBarLayout'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:655: in function `UpdateGridLayout'
[string "@Interface/FrameXML/ActionBar.lua"]:350: in function `UpdateVisibility'
[string "@Interface/FrameXML/ActionBar.lua"]:282: in function <Interface/FrameXML/ActionBar.lua:278>
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals:
self = <table> {
 GetSettingMapFromSettings = <function> defined @Interface/FrameXML/EditModeUtil.lua:58
 IsRightAnchoredActionBar = <function> defined @Interface/FrameXML/EditModeUtil.lua:3
 GetRightContainerAnchor = <function> defined @Interface/FrameXML/EditModeUtil.lua:52
 IsBottomAnchoredActionBar = <function> defined @Interface/FrameXML/EditModeUtil.lua:8
 GetRightActionBarWidth = <function> defined @Interface/FrameXML/EditModeUtil.lua:18
 GetBottomActionBarHeight = <function> defined @Interface/FrameXML/EditModeUtil.lua:33
}
offset = 0
point = nil
relativeTo = nil
relativePoint = nil
offsetX = nil
offsetY = nil
(*temporary) = 44.999943
(*temporary) = 44.999943
(*temporary) = MultiBarRight {
 0 = <userdata>
 buttonPadding = 2
 UpdateSystemSettingAlwaysShowButtons = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:772
 UpdateMagnetismRegistration = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:506
 GetSnapOffsets = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:411
 UpdateFrameStrata = <function> defined @Interface/FrameXML/ActionBar.lua:194
 UpdateButtonArt = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:669
 IsFrameAnchoredToMe = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:469
 buttonTemplate = "MultiBar3ButtonTemplate"
 ShowBase = <function> defined =[C]:-1
 IsShown = <function> defined @Interface/FrameXML/ActionBar.lua:286
 GetSelectionOffset = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:363
 ResetToDefaultPosition = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:148
 RefreshButtonArt = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:662
 GetScaledSelectionSides = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:355
 SelectSystem = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:534
 buttonArtDirty = false
 GetFrameMagneticEligibility = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:489
 AddLayoutChildren = <function> defined @Interface/SharedXML/LayoutFrame.lua:48
 IsBelowFrame = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:322
 UpdateSystemSettingIconSize = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:714
 SetScaleBase = <function> defined =[C]:-1
 HasActiveChanges = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:244
 GetScaledCenter = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:348
 DoesSettingDisplayValueEqual = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:268
 Layout = <function> defined @Interface/SharedXML/LayoutFrame.lua:333
 settingDisplayInfoMap = <table> {
 }
 addSystemIndexToName = true
 IsLayoutFrame = <function> defined @Interface/SharedXML/LayoutFrame.lua:36
 DoesSettingValueEqual = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:263
 MarkDirty = <function> defined @Interface/SharedXML/LayoutFrame.lua:90
 ShouldResetSettingsDialogAnchors = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:91
 dirtySettings = <table> {
 }
 UpdateGridLayout = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:648
 IsToTheLeftOfFrame = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:304
 GetSettingsDialogAnchor = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:288
 hasActiveChanges = false
 OnSystemLoad = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:3
 ClearFrameSnap = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:448
 GetCombinedCenterOffset = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:398
 SetupSettingsDialogAnchor = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:232
 IsShownOverride = <function> defined @Interface/FrameXML/ActionBar.lua:286
 dirty = false
 SetPointBase = <function> defined =[C]:-1
 UpdateSystem = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:586
 CacheGridSettings = <function> ```

```3253x Interface/FrameXML/EditModeSystemTemplates.lua:631: attempt to perform arithmetic on local 'offsetY' (a nil value)
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:631: in function `GetBottomAnchoredHeight'
[string "@Interface/FrameXML/EditModeUtil.lua"]:39: in function `GetBottomActionBarHeight'
[string "@Interface/FrameXML/UIParent.lua"]:3074: in function `UIParentManageFramePositions'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3104: in function `UIParent_ManageFramePositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:641: in function `UpdateBottomActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:555: in function `UpdateActionBarLayout'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:655: in function `UpdateGridLayout'
[string "@Interface/FrameXML/ActionBar.lua"]:350: in function `UpdateVisibility'
[string "@Interface/FrameXML/ActionBar.lua"]:317: in function `Hide'
[string "@Interface/FrameXML/PetActionBar.lua"]:182: in function `Update'
[string "@Interface/FrameXML/PetActionBar.lua"]:84: in function <Interface/FrameXML/PetActionBar.lua:70>
[string "=[C]"]: ?

Locals:
self = MainMenuBar {
 0 = <userdata>
 QuickKeybindRightShadow = Texture {
 }
 UpdateSystemSettingAlwaysShowButtons = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:772
 UpdateMagnetismRegistration = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:506
 GetSnapOffsets = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:411
 UpdateFrameStrata = <function> defined @Interface/FrameXML/ActionBar.lua:194
 UpdateButtonArt = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:669
 IsFrameAnchoredToMe = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:469
 buttonTemplate = "MainBarActionBarButtonTemplate"
 ShowBase = <function> defined =[C]:-1
 IsShown = <function> defined @Interface/FrameXML/ActionBar.lua:286
 GetSelectionOffset = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:363
 ResetToDefaultPosition = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:148
 RefreshButtonArt = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:662
 GetScaledSelectionSides = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:355
 SelectSystem = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:534
 buttonArtDirty = false
 GetFrameMagneticEligibility = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:489
 AddLayoutChildren = <function> defined @Interface/SharedXML/LayoutFrame.lua:48
 IsBelowFrame = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:322
 UpdateSystemSettingIconSize = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:714
 SetScaleBase = <function> defined =[C]:-1
 HasActiveChanges = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:244
 GetScaledCenter = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:348
 DoesSettingDisplayValueEqual = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:268
 OnLoad = <function> defined @Interface/FrameXML/MainMenuBar.lua:6
 UpdateDisplayInfoOptions = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:279
 ActionBarPageNumber = Frame {
 }
 settingDisplayInfoMap = <table> {
 }
 addSystemIndexToName = true
 IsLayoutFrame = <function> defined @Interface/SharedXML/LayoutFrame.lua:36
 DoesSettingValueEqual = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:263
 MarkDirty = <function> defined @Interface/SharedXML/LayoutFrame.lua:90
 ShouldResetSettingsDialogAnchors = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:91
 dirtySettings = <table> {
 }
 UpdateGridLayout = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:648
 IsToTheLeftOfFrame = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:304
 GetSettingsDialogAnchor = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:288
 hasActiveChanges = false
 OnSystemLoad = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:3
 ClearFrameSnap = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:448
 GetCombinedCenterOffset = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:398
 SetupSettingsDialogAnchor = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:232
 IsShownOverride = <function> defined @Interface/FrameXML/ActionBar.lua:286
 dirty = false
 SetPointBase = <function> defined =[C]:-1
 UpdateSystem = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:586
 UpdateShownButtons = <function> defined @Interface/FrameXML/ActionBar.lua:198
 UpdateDirtySettings = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:112
 isHighlighted = false
 BreakSnappedFrames = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:431
 HideOverride = <function> defined @Interface/FrameXML/ActionBar.lua:313
 VehicleLeaveButton = MainMenuBarVehicleLeaveButton {
 }
 systemIndex = 1
 snappedFrames = <table> {
 }
 SetShownOverride = <function> defined @Interface/FrameXML/ActionBar.lua:298
 SetPointOverride```

X.x War non-cap..

**Comment by DePhoegon** [comment]
1x [ADDON_ACTION_FORBIDDEN] AddOn 'BetterWardrobe' tried to call the protected function 'UseToy()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseToy'
[string "@Interface/AddOns/Blizzard_Collections/Blizzard_ToyBox.lua"]:181: in function `ToySpellButton_OnClick'
[string "*Blizzard_ToyBox.xml:10_OnClick"]:4: in function <[string "*Blizzard_ToyBox.xml:10_OnClick"]:1>

**Comment by DePhoegon** [comment]
24x Interface/FrameXML/EditModeUtil.lua:22: attempt to perform arithmetic on local 'offsetX' (a nil value)
[string "@Interface/FrameXML/EditModeUtil.lua"]:22: in function `GetRightActionBarWidth'
[string "@Interface/FrameXML/EditModeUtil.lua"]:53: in function `GetRightContainerAnchor'
[string "@Interface/FrameXML/UIParent.lua"]:3082: in function `UIParentManageFramePositions'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3104: in function `UIParent_ManageFramePositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:641: in function `UpdateBottomActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:555: in function `UpdateActionBarLayout'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:655: in function `UpdateGridLayout'
[string "@Interface/FrameXML/ActionBar.lua"]:350: in function `UpdateVisibility'
[string "@Interface/FrameXML/ActionBar.lua"]:282: in function <Interface/FrameXML/ActionBar.lua:278>
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals:
self = <table> {
 GetSettingMapFromSettings = <function> defined @Interface/FrameXML/EditModeUtil.lua:58
 IsRightAnchoredActionBar = <function> defined @Interface/FrameXML/EditModeUtil.lua:3
 GetRightContainerAnchor = <function> defined @Interface/FrameXML/EditModeUtil.lua:52
 IsBottomAnchoredActionBar = <function> defined @Interface/FrameXML/EditModeUtil.lua:8
 GetRightActionBarWidth = <function> defined @Interface/FrameXML/EditModeUtil.lua:18
 GetBottomActionBarHeight = <function> defined @Interface/FrameXML/EditModeUtil.lua:33
}
offset = 0
point = nil
relativeTo = nil
relativePoint = nil
offsetX = nil
offsetY = nil
(*temporary) = 44.999943
(*temporary) = 44.999943
(*temporary) = MultiBarRight {
 0 = <userdata>
 buttonPadding = 2
 UpdateSystemSettingAlwaysShowButtons = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:772
 UpdateMagnetismRegistration = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:506
 GetSnapOffsets = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:411
 UpdateFrameStrata = <function> defined @Interface/FrameXML/ActionBar.lua:194
 UpdateButtonArt = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:669
 IsFrameAnchoredToMe = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:469
 buttonTemplate = "MultiBar3ButtonTemplate"
 ShowBase = <function> defined =[C]:-1
 IsShown = <function> defined @Interface/FrameXML/ActionBar.lua:286
 GetSelectionOffset = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:363
 ResetToDefaultPosition = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:148
 RefreshButtonArt = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:662
 GetScaledSelectionSides = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:355
 SelectSystem = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:534
 buttonArtDirty = false
 GetFrameMagneticEligibility = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:489
 AddLayoutChildren = <function> defined @Interface/SharedXML/LayoutFrame.lua:48
 IsBelowFrame = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:322
 UpdateSystemSettingIconSize = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:714
 SetScaleBase = <function> defined =[C]:-1
 HasActiveChanges = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:244
 GetScaledCenter = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:348
 DoesSettingDisplayValueEqual = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:268
 Layout = <function> defined @Interface/SharedXML/LayoutFrame.lua:333
 settingDisplayInfoMap = <table> {
 }
 addSystemIndexToName = true
 IsLayoutFrame = <function> defined @Interface/SharedXML/LayoutFrame.lua:36
 DoesSettingValueEqual = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:263
 MarkDirty = <function> defined @Interface/SharedXML/LayoutFrame.lua:90
 ShouldResetSettingsDialogAnchors = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:91
 dirtySettings = <table> {
 }
 UpdateGridLayout = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:648
 IsToTheLeftOfFrame = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:304
 GetSettingsDialogAnchor = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:288
 hasActiveChanges = false
 OnSystemLoad = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:3
 ClearFrameSnap = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:448
 GetCombinedCenterOffset = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:398
 SetupSettingsDialogAnchor = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:232
 IsShownOverride = <function> defined @Interface/FrameXML/ActionBar.lua:286
 dirty = false
 SetPointBase = <function> defined =[C]:-1
 UpdateSystem = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:586
 CacheGridSettings = <function>

**Comment by DePhoegon** [comment]
3390x Interface/FrameXML/EditModeSystemTemplates.lua:631: attempt to perform arithmetic on local 'offsetY' (a nil value)
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:631: in function `GetBottomAnchoredHeight'
[string "@Interface/FrameXML/EditModeUtil.lua"]:39: in function `GetBottomActionBarHeight'
[string "@Interface/FrameXML/UIParent.lua"]:3074: in function `UIParentManageFramePositions'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3104: in function `UIParent_ManageFramePositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:641: in function `UpdateBottomActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:555: in function `UpdateActionBarLayout'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:655: in function `UpdateGridLayout'
[string "@Interface/FrameXML/ActionBar.lua"]:350: in function `UpdateVisibility'
[string "@Interface/FrameXML/ActionBar.lua"]:317: in function `Hide'
[string "@Interface/FrameXML/PetActionBar.lua"]:182: in function `Update'
[string "@Interface/FrameXML/PetActionBar.lua"]:84: in function <Interface/FrameXML/PetActionBar.lua:70>
[string "=[C]"]: ?

Locals:
self = MainMenuBar {
 0 = <userdata>
 QuickKeybindRightShadow = Texture {
 }
 UpdateSystemSettingAlwaysShowButtons = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:772
 UpdateMagnetismRegistration = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:506
 GetSnapOffsets = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:411
 UpdateFrameStrata = <function> defined @Interface/FrameXML/ActionBar.lua:194
 UpdateButtonArt = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:669
 IsFrameAnchoredToMe = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:469
 buttonTemplate = "MainBarActionBarButtonTemplate"
 ShowBase = <function> defined =[C]:-1
 IsShown = <function> defined @Interface/FrameXML/ActionBar.lua:286
 GetSelectionOffset = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:363
 ResetToDefaultPosition = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:148
 RefreshButtonArt = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:662
 GetScaledSelectionSides = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:355
 SelectSystem = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:534
 buttonArtDirty = false
 GetFrameMagneticEligibility = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:489
 AddLayoutChildren = <function> defined @Interface/SharedXML/LayoutFrame.lua:48
 IsBelowFrame = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:322
 UpdateSystemSettingIconSize = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:714
 SetScaleBase = <function> defined =[C]:-1
 HasActiveChanges = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:244
 GetScaledCenter = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:348
 DoesSettingDisplayValueEqual = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:268
 OnLoad = <function> defined @Interface/FrameXML/MainMenuBar.lua:6
 UpdateDisplayInfoOptions = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:279
 ActionBarPageNumber = Frame {
 }
 settingDisplayInfoMap = <table> {
 }
 addSystemIndexToName = true
 IsLayoutFrame = <function> defined @Interface/SharedXML/LayoutFrame.lua:36
 DoesSettingValueEqual = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:263
 MarkDirty = <function> defined @Interface/SharedXML/LayoutFrame.lua:90
 ShouldResetSettingsDialogAnchors = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:91
 dirtySettings = <table> {
 }
 UpdateGridLayout = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:648
 IsToTheLeftOfFrame = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:304
 GetSettingsDialogAnchor = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:288
 hasActiveChanges = false
 OnSystemLoad = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:3
 ClearFrameSnap = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:448
 GetCombinedCenterOffset = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:398
 SetupSettingsDialogAnchor = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:232
 IsShownOverride = <function> defined @Interface/FrameXML/ActionBar.lua:286
 dirty = false
 SetPointBase = <function> defined =[C]:-1
 UpdateSystem = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:586
 UpdateShownButtons = <function> defined @Interface/FrameXML/ActionBar.lua:198
 UpdateDirtySettings = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:112
 isHighlighted = false
 BreakSnappedFrames = <function> defined @Interface/FrameXML/EditModeSystemTemplates.lua:431
 HideOverride = <function> defined @Interface/FrameXML/ActionBar.lua:313
 VehicleLeaveButton = MainMenuBarVehicleLeaveButton {
 }
 systemIndex = 1
 snappedFrames = <table> {
 }
 SetShownOverride = <function> defined @Interface/FrameXML/ActionBar.lua:298
 SetPointOverride

**Comment by DePhoegon** [comment]
X.x it short these are loving to have issues if you get dropped directly into combat (from say a mount, a teleport [zoning more or less], or

**Comment by SLOKnightfall** [comment]
The errors are all due to Blizzards new UI and taint, which are affecting quite a few addons.  Only 2 of the errors list this addon, the rest are errors on action & stance bars that this addon does not deal with.  They are most likely due to an action bar addon.
