### ISSUE TITLE
Wardrobe Inconsistency 

### ISSUE THREAD

**Issue by ZhrChaos** [SLOKnightfall/BetterWardrobe#304]
I keep having weird issues with the wardrobe. Either some of the buttons and outfit selection are messed up, or sometimes the sizing doesn't stay correct. Rarely is it the normal clean version that I couldn't even get a screenshot of it.
![Betterwardrobe](https://user-images.githubusercontent.com/37288807/201237666-9c9edaf5-c86b-4e7e-9607-42517dee030b.jpg)
![Betterwardrobe2](https://user-images.githubusercontent.com/37288807/201237673-3cd029eb-d8ff-4dfb-a6f9-76f6bc38f850.jpg)

**Comment by SLOKnightfall** [comment]
Are you still seeing the issue in V4.3.2?  It is causes from some timing issues of when Elvui skins things and this release should fix it

**Comment by SLOKnightfall** [comment]
V4.3.3 should fix the issue

**Comment by ZhrChaos** [comment]
So far it does seem to have been fixed with V4.3.3. Thank you!
