### ISSUE TITLE
New error with DF phase 2 patch

### ISSUE THREAD

**Issue by tommy610** [SLOKnightfall/BetterWardrobe#308]
2x BetterWardrobe/Modules/Tooltips.lua:79: GameTooltip doesn't have a "OnTooltipSetItem" script
[string "=[C]"]: in function `HookScript'
[string "@BetterWardrobe/Modules/Tooltips.lua"]:79: in function `BuildTooltips'
[string "@BetterWardrobe/Modules/Core.lua"]:1278: in function <BetterWardrobe/Modules/Core.lua:1263>
[string "=[C]"]: ?
[string "@CanIMogIt/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <CanIMogIt/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@CanIMogIt/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@CanIMogIt/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <CanIMogIt/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by SLOKnightfall** [comment]
Should be fixed in the next update
