### ISSUE TITLE
repeated text in tooltips for non-items

### ISSUE THREAD

**Issue by durandal42** [SLOKnightfall/BetterWardrobe#309]
Here's what happens when I hovered the necrolord command table: https://imgur.com/a/jlA2QFz

The tooltip gets noticeable larger over time, sometimes growing to cover the entire screen. I haven't been able to pin down what specifically triggers this, but the text "Part of Extra Set" is coming from BetterWardrobe.

**Comment by SLOKnightfall** [comment]
Could you verify if you are still seeing the issue with the most recent update.

**Comment by durandal42** [comment]
I haven't seen it since updating to 4.4.6. I'll post again here if I do!
