### ISSUE TITLE
lua error SetShowMissingSourceInItemTooltips

### ISSUE THREAD

**Issue by agentschmitt** [SLOKnightfall/BetterWardrobe#310]
3x Interface/AddOns/BetterWardrobe/Modules/Core.lua:64: attempt to call field 'SetShowMissingSourceInItemTooltips' (a nil value)
[string "@Interface/AddOns/BetterWardrobe/Modules/Core.lua"]:64: in function <Interface/AddOns/BetterWardrobe/Modules/Core.lua:38>
[string "=[C]"]: ?
[string "@Interface/AddOns/BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:831: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Ace3/AceGUI-3.0-41/widgets/AceGUIWidget-CheckBox.lua"]:64: in function <...ns/Ace3/AceGUI-3.0/widgets/AceGUIWidget-CheckBox.lua:53>

**Comment by SLOKnightfall** [comment]
Fixed in next update
