### ISSUE TITLE
Error when clicking a character name in chat with BasicChatMod addon

### ISSUE THREAD

**Issue by tommy610** [SLOKnightfall/BetterWardrobe#312]
17x BetterWardrobe/Modules/Wardrobe.lua:7854: attempt to call field 'SetItemRef' (a nil value)
[string "@BetterWardrobe/Modules/Wardrobe.lua"]:7854: in function <BetterWardrobe/Modules/Wardrobe.lua:7829>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Blizzard_CombatLog/Blizzard_CombatLog.lua"]:3534: in function <...aceBlizzard_CombatLog/Blizzard_CombatLog.lua:3475>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetItemRef'
[string "@FrameXML/ChatFrame.lua"]:4031: in function `ChatFrame_OnHyperlinkShow'
[string "*ChatFrame.xml:15_OnHyperlinkClick"]:1: in function <[string "*ChatFrame.xml:15_OnHyperlinkClick"]:1>
[string "=[C]"]: ?

Locals:
link = "BNplayer:|Kq94|k:40:15:BN_WHISPER:|Kq94|k"
linkType = "BNplayer"
id = "|Kq94|k"
(*temporary) = nil
(*temporary) = "BNplayer:|Kq94|k:40:15:BN_WHISPER:|Kq94|k"
(*temporary) = "|HBNplayer:|Kq94|k:40:15:BN_WHISPER:|Kq94|k|h[|cFF33937f|Kq94|k|r]|h"
(*temporary) = "LeftButton"
(*temporary) = ChatFrame1 {
 GatherSelectedText = <function> defined =[C]:-1
 RefreshIfNecessary = <function> defined =[C]:-1
 OnPostShow = <function> defined =[C]:-1
 CalculateLineAlphaValueFromTimestamp = <function> defined =[C]:-1
 ScrollUp = <function> defined =[C]:-1
 GetSnapOffsets = <function> defined @FrameXML/EditModeSystemTemplates.lua:411
 EditMode_OnResized = <function> defined @FrameXML/EditModeSystemTemplates.lua:1601
 systemInfo = <table> {
 }
 OnFontObjectUpdated = <function> defined =[C]:-1
 IsFrameAnchoredToMe = <function> defined @FrameXML/EditModeSystemTemplates.lua:469
 GetFading = <function> defined =[C]:-1
 IsTextCopyable = <function> defined =[C]:-1
 BaseAddMessage = <function> defined =[C]:-1
 shouldFadeAfterInactivity = true
 SetIndentedWordWrap = <function> defined =[C]:-1
 GetJustifyV = <function> defined =[C]:-1
 ScrollToBottom = <function> defined =[C]:-1
 GetMaxLines = <function> defined =[C]:-1
 GetSelectionOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:363
 ResetToDefaultPosition = <function> defined @FrameXML/EditModeSystemTemplates.lua:148
 GetScaledSelectionSides = <function> defined @FrameXML/EditModeSystemTemplates.lua:355
 GetIndentedWordWrap = <function> defined =[C]:-1
 SelectSystem = <function> defined @FrameXML/EditModeSystemTemplates.lua:534
 GetFont = <function> defined =[C]:-1
 GetFrameMagneticEligibility = <function> defined @FrameXML/EditModeSystemTemplates.lua:489
 SetMaxLines = <function> defined =[C]:-1
 CalculateSelectingCharacterIndicesForVisibleLine = <function> defined =[C]:-1
 OnPostUpdate = <function> defined =[C]:-1
 RefreshDisplay = <function> defined =[C]:-1
 SetFontObject = <function> defined =[C]:-1
 IsBelowFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:322
 SetOnScrollChangedCallback = <function> defined =[C]:-1
 CalculateNumVisibleLines = <function> defined =[C]:-1
 GetScaledCenter = <function> defined @FrameXML/EditModeSystemTemplates.lua:348
 overrideFadeTimestamp = 540448.400000
 DoesSettingDisplayValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:268
 MarkDisplayDirty = <function> defined =[C]:-1
 UpdateDisplayInfoOptions = <function> defined @FrameXML/EditModeSystemTemplates.lua:279
 GetMessageInfo = <function> defined =[C]:-1
 GetOnScrollChangedCallback = <function> defined =[C]:-1
 GetSettingValueBool = <function> defined @FrameXML/EditModeSystemTemplates.lua:259
 AtTop = <function> defined =[C]:-1
 GetFontObject = <function> defined =[C]:-1
 fontStringPool = <table> {
 }
 DoesSettingValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:263
 CanEffectivelyFade = <function> defined =[C]:-1
 ShouldResetSettingsDialogAnchors = <function> defined @FrameXML/EditModeSystemTemplates.lua:91
 OnPreSizeChanged = <function> defined =[C]:-1
 dirtySettings = <table> {
 }
 GetScrollOffset = <function> defined =[C]:-1
 IsToTheLeftOfFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:304
 GetSettingsDialogAnchor = <function> defined @FrameXML/EditModeSystemTemplates.lua:288
 OnSystemLoad = <function> defined @FrameXML/EditModeSystemTemplates.lua:3
 ClearFrameSnap = <function> defined @FrameXML/EditModeSystemTemplates.lua:448
 GetCombinedCenterOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:398
 SetupSettingsDialogAnchor = <function> defined @FrameXML/EditModeSystemTemplates.lua:232
 GetSpacing = <function> defined =[C]:-1
 OnPreLoad = <function> defined =[C]:-1
 SetPointBase = <function> defined =[C]:-1
 SetSpacing = <function> defined =[C]:-1
 UpdateSystem = <function> defined @Inter

**Comment by SLOKnightfall** [comment]
Fixed in the next update
