### ISSUE TITLE
Error: open transmog

### ISSUE THREAD

**Issue by LutzFO** [SLOKnightfall/BetterWardrobe#321]
This happen when transmog open:

https://user-images.githubusercontent.com/94018267/203443704-3e7543e4-607c-4162-8f15-96bbd253f305.mp4

**Comment by SLOKnightfall** [comment]
Strange.  I'm currently not able to reproduce the issue on my end.  Are you seeing the issue if this addon is the only one loaded?  Are you using any other transmog addons, as there might be some conflict going on?

**Comment by SLOKnightfall** [comment]
Turns out the issue is being caused by the wowhead loader addon.
