### ISSUE TITLE
Bug: TinyTooltil-Reforged Compatibility Issue

### ISSUE THREAD

**Issue by nancikennedy** [SLOKnightfall/BetterWardrobe#322]
On Retail, with TTR v9.3.12 and BWAT v4.4.71 installed, when clicking on sets (where there are any unknown items) in the extra tabs that BWAT creates in the Appearance section of the Collections, this error is generated.

84x TinyTooltip-Reforged/Core.lua:136: attempt to index local 'line' (a nil value)
[string "@TinyTooltip-Reforged/Core.lua"]:136: in function `FindLine'
[string "@TinyTooltip-Reforged/LinkID.lua"]:16: in function <TinyTooltip-Reforged/LinkID.lua:12>
[string "@TinyTooltip-Reforged/LinkID.lua"]:34: in function <TinyTooltip-Reforged/LinkID.lua:31>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
...
[string "@SharedXML/Scroll/ScrollBox.lua"]:589: in function `SetDataProvider'
[string "@BetterWardrobe/Modules/Wardrobe.lua"]:6305: in function `UpdateDataProvider'
[string "@BetterWardrobe/Modules/Wardrobe.lua"]:5191: in function `Refresh'
[string "@BetterWardrobe/Modules/Wardrobe.lua"]:5828: in function `SelectSet'
[string "@BetterWardrobe/Modules/Wardrobe.lua"]:5075: in function <BetterWardrobe/Modules/Wardrobe.lua:5032>
[string "=[C]"]: in function `SetShown'
[string "@BetterWardrobe/Modules/Wardrobe.lua"]:1299: in function `SetTab'
[string "@BetterWardrobe/Modules/Wardrobe.lua"]:1201: in function `ClickTab'
[string "*Wardrobe.xml:450_OnClick"]:1: in function <[string "*Wardrobe.xml:450_OnClick"]:1>
[string "=[C]"]: ?

Locals:
self = <table> {
GetLine = <function> defined @TinyTooltip-Reforged/Core.lua:164
GetRGBColor = <function> defined @TinyTooltip-Reforged/Core.lua:184
GetClassIcon = <function> defined @TinyTooltip-Reforged/Core.lua:253
tooltips = <table> {
}
ColorUnitBackground = <function> defined @TinyTooltip-Reforged/Unit.lua:40
GetBgFile = <function> defined @TinyTooltip-Reforged/Core.lua:205
filterfunc = <table> {
}
GetBarFile = <function> defined @TinyTooltip-Reforged/Core.lua:214
GetUnitSpeed = <function> defined @TinyTooltip-Reforged/Core.lua:281
GetHexColor = <function> defined @TinyTooltip-Reforged/Core.lua:173
icons = <table> {
}
GetUnitData = <function> defined @TinyTooltip-Reforged/Core.lua:496
GetGender = <function> defined @TinyTooltip-Reforged/Core.lua:306
bgs = <table> {
}
GetFont = <function> defined @TinyTooltip-Reforged/Core.lua:194
GetRoleIcon = <function> defined @TinyTooltip-Reforged/Core.lua:235
GetZone = <function> defined @TinyTooltip-Reforged/Core.lua:320
FindLine = <function> defined @TinyTooltip-Reforged/Core.lua:132
G = <table> {
}
GetTitle = <function> defined @TinyTooltip-Reforged/Core.lua:296
ParseItemLink = <function> defined @TinyTooltip-Reforged/ExpansionInfo.lua:11
db = <table> {
}
L = <table> {
}
HideLine = <function> defined @TinyTooltip-Reforged/Core.lua:143
print = <function> defined @TinyTooltip-Reforged/ExpansionInfo.lua:7
GetBattlePet = <function> defined @TinyTooltip-Reforged/Core.lua:274
colorfunc = <table> {
}
HideLines = <function> defined @TinyTooltip-Reforged/Core.lua:155
FormatData = <function> defined @TinyTooltip-Reforged/Core.lua:483
CheckFilter = <function> defined @TinyTooltip-Reforged/Core.lua:460
SettingsGetUnitInfo = <function> defined @TinyTooltip-Reforged/Core.lua:401
GetUnitInfo = <function> defined @TinyTooltip-Reforged/Core.lua:340
GetRaidIcon = <function> defined @TinyTooltip-Reforged/Core.lua:246
GetFriendIcon = <function> defined @TinyTooltip-Reforged/Core.lua:259
FixNumericKey = <function> defined @TinyTooltip-Reforged/Core.lua:97
GetFactionIcon = <function> defined @TinyTooltip-Reforged/Core.lua:242
GetPVPIcon = <function> defined @TinyTooltip-Reforged/Core.lua:229
GetNpcTitle = <function> defined @TinyTooltip-Reforged/Core.lua:314
MergeVariable = <function> defined @TinyTooltip-Reforged/Core.lua:118
ColorUnitBorder = <function> defined @TinyTooltip-Reforged/Unit.lua:24
GetQuestBossIcon = <function> defined @TinyTooltip-Reforged/Core.lua:223
}
tooltip = BW_ScanGameTooltip {
0 = <userdata>
SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetQuestPartyProgress = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:303
SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetRuneforgeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetHyperlink = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetUnit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetVoidWithdrawalItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
SetInfoBackdropStyle = <function> defined @

**Comment by SLOKnightfall** [comment]
This looks like an issue with TinyTooltil-Reforged  where the addon is not taking into account that the data it is looking for does not exist and needs to be addressed/fixed in that addon.
