### ISSUE TITLE
Evokers 

### ISSUE THREAD

**Issue by cwwood0322** [SLOKnightfall/BetterWardrobe#324]
There is an issue with seeing sets displayed properly with Evokers. The visual display is messed up. Again, have to disable addon to see what sets look like on them, just as I still have to do so with new set pieces on any set any class. The set icon still lights up with the blue border when a new piece is acquired but the piece is not showing up on the set like it is supposed to do.

**Comment by SLOKnightfall** [comment]
The Evokers display should be fixed in the next update.
