### ISSUE TITLE
Not able to add items/sets to collection list

### ISSUE THREAD

**Issue by Dreadful-Sanity** [SLOKnightfall/BetterWardrobe#327]
When trying to add an item or a set to a collection, I'm getting the following error and the collection list stays empty. 

Lua Error:

> `3x ...aceBetterWardrobe/Modules/CollectionList.lua:142: attempt to call field 'GetSetSources' (a nil value)
> [string "@BetterWardrobe/Modules/CollectionList.lua"]:142: in function `UpdateList'
> [string "@BetterWardrobe/Modules/Wardrobe.lua"]:6138: in function `func'
> [string "@BetterWardrobe/Libs/UIDropDownMenu/UIDropDownMenu.lua"]:905: in function `BW_UIDropDownMenuButton_OnClick'
> [string "*UIDropDownMenuTemplates.xml:139_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:139_OnClick"]:1>
> 
> Locals:
> self = <table> {
>  UpdateList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:118
>  SelectedCollectionList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:522
>  GenerateSourceListView = <function> defined @BetterWardrobe/Modules/Sources.lua:459
>  BuildCollectionList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:23
>  AddMogItData = <function> defined @BetterWardrobe/Modules/CollectionList.lua:420
>  AddList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:428
>  GenerateListView = <function> defined @BetterWardrobe/Modules/CollectionList.lua:573
>  CurrentList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:511
>  IsInList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:467
>  TSMGroupExport = <function> defined @BetterWardrobe/Modules/CollectionList.lua:668
>  Dropdown_Initialize = <function> defined @BetterWardrobe/Modules/CollectionList.lua:311
>  CreateDropdown = <function> defined @BetterWardrobe/Modules/CollectionList.lua:341
>  ListCount = <function> defined @BetterWardrobe/Modules/CollectionList.lua:496
>  DeleteList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:453
>  Dropdown_OnClick = <function> defined @BetterWardrobe/Modules/CollectionList.lua:303
>  BuildShoppingList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:101
>  RenameList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:442
>  showAll = true
>  OptionButton_OnClick = <function> defined @BetterWardrobe/Modules/CollectionList.lua:370
> }
> type = "set"
> typeID = 483
> add = true
> sourceID = nil
> addSet = false
> setName = nil
> setInfo = nil
> itemModID = nil
> selectedList = 1
> collectionList = <table> {
>  set = <table> {
>  }
>  item = <table> {
>  }
>  name = "CollectionList"
>  extraset = <table> {
>  }
> }
> sources = nil
> (*temporary) = nil
> (*temporary) = 483
> (*temporary) = "attempt to call field 'GetSetSources' (a nil value)"
> CollectionList = <table> {
>  UpdateList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:118
>  SelectedCollectionList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:522
>  GenerateSourceListView = <function> defined @BetterWardrobe/Modules/Sources.lua:459
>  BuildCollectionList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:23
>  AddMogItData = <function> defined @BetterWardrobe/Modules/CollectionList.lua:420
>  AddList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:428
>  GenerateListView = <function> defined @BetterWardrobe/Modules/CollectionList.lua:573
>  CurrentList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:511
>  IsInList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:467
>  TSMGroupExport = <function> defined @BetterWardrobe/Modules/CollectionList.lua:668
>  Dropdown_Initialize = <function> defined @BetterWardrobe/Modules/CollectionList.lua:311
>  CreateDropdown = <function> defined @BetterWardrobe/Modules/CollectionList.lua:341
>  ListCount = <function> defined @BetterWardrobe/Modules/CollectionList.lua:496
>  DeleteList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:453
>  Dropdown_OnClick = <function> defined @BetterWardrobe/Modules/CollectionList.lua:303
>  BuildShoppingList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:101
>  RenameList = <function> defined @BetterWardrobe/Modules/CollectionList.lua:442
>  showAll = true
>  OptionButton_OnClick = <function> defined @BetterWardrobe/Modules/CollectionList.lua:370
> }
> addon = <table> {
> `

**Comment by michael-farwell** [comment]
I ran into the same error

**Comment by SLOKnightfall** [comment]
Should be fixed in the next update
