### ISSUE TITLE
Wardrobe.lua:1361: Usage: GetItemInfoInstant(itemID|"name"|"itemlink")

### ISSUE THREAD

**Issue by Ookami313** [SLOKnightfall/BetterWardrobe#329]
Was adding leatherworker's tools and accessories to my profession panel and received the following error. Thanks.

1x BetterWardrobe/Modules/Wardrobe.lua:1361: Usage: GetItemInfoInstant(itemID|"name"|"itemlink")
[string "=[C]"]: in function `GetItemInfoInstant'
[string "@BetterWardrobe/Modules/Wardrobe.lua"]:1361: in function `OnEvent'
[string "@BetterWardrobe/Modules/Core.lua"]:1350: in function `?'
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

**Comment by SLOKnightfall** [comment]
Sho
