### ISSUE TITLE
BW causes slow bag item status update

### ISSUE THREAD

**Issue by SiderealDay** [SLOKnightfall/BetterWardrobe#330]
Hi,

It seems BW is causing slowdown in the update of item status in ELVUI bags.
I don't know if this also happens with other bag addons.

ELVUI has an option to show certain icons and text on items inside the bags, for example "BOE" on BOE items, or "coin" icon for junk.
With BA disabled, these show up as soon as I open the bags.
With BA enabled, these do not show until I perform an action on each item, like move each individual item in the bag.
All icons eventually update properly if I play the game and start looting things, but that can take a while.

Any way to solve this?

**Comment by SLOKnightfall** [comment]
That's wierd as I can't think of a reason BW would be interacting with ELVUI that way.  I'll look into it and see what can be done.

**Comment by SiderealDay** [comment]
I also found out that **CanIMogIt** addon is also causing the delay, but to a lesser degree than BW.
With CIMI the delay happens sometimes, but mostly in bank frame.
I need to disable both BW and CIMI for equipment icons to show properly.

**Comment by SLOKnightfall** [comment]
I believe that this issue has been fixed.
