### ISSUE TITLE
Lua Error in ColorFilter ConvertRGB_to_LAB

### ISSUE THREAD

**Issue by agentschmitt** [SLOKnightfall/BetterWardrobe#333]
I got a lua error in BetterWardrobe when using the color picker.

`34x BetterWardrobe/Modules/ColorFilter.lua:160: attempt to call global 'ConvertRGB_to_LAB' (a nil value)
[string "@BetterWardrobe/Modules/ColorFilter.lua"]:160: in function `func'
[string "*ColorPickerFrame.xml:107_OnColorSelect"]:3: in function <[string "*ColorPickerFrame.xml:107_OnColorSelect"]:1>
[string "=[C]"]: in function `SetColorRGB'
[string "@BetterWardrobe/Modules/ColorFilter.lua"]:186: in function <BetterWardrobe/Modules/ColorFilter.lua:122>
[string "@BetterWardrobe/Modules/ColorFilter.lua"]:217: in function <BetterWardrobe/Modules/ColorFilter.lua:216>

Locals:
ItemsCollectionFrame = Frame {
 0 = <userdata>
 ClearAppearanceTooltip = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2885
 ShadowCornerTopRight = Texture {
 }
 IsAppearanceUsableForActiveCategory = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2960
 GoToSourceID = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2835
 SortVisuals = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2341
 ModelR1C2 = DressUpModel {
 }
 transmogLocation = <table> {
 }
 OnUnitModelChangedEvent = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2068
 OnShow = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:1900
 ShadowCornerLeft = Texture {
 }
 lastWeaponCategory = 29
 UpdateSlotButtons = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2890
 BGCornerFilagreeBottomLeft = Texture {
 }
 ModelR2C2 = DressUpModel {
 }
 GetActiveCategory = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2082
 ShadowCornerRight = Texture {
 }
 ModelR3C2 = DressUpModel {
 }
 UpdateProgressBar = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2674
 SetActiveCategory = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2187
 ModelR1C5 = DressUpModel {
 }
 visualsList = <table> {
 }
 BGCornerBottomLeft = Texture {
 }
 tooltipModel = DressUpModel {
 }
 FilterVisuals = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2267
 OnPageChanged = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2929
 BGCornerTopRight = Texture {
 }
 ModelR1C1 = DressUpModel {
 }
 ShadowCornerBottomLeft = Texture {
 }
 SlotsFrame = Frame {
 }
 Bg = Texture {
 }
 HiddenModel = DressUpModel {
 }
 OverlayShadowBottomLeft = Texture {
 }
 ModelR2C6 = DressUpModel {
 }
 NineSlice = Frame {
 }
 CheckHelpTip = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:1843
 activeCategory = 10
 OverlayShadowLeft = Texture {
 }
 DressUpVisual = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:1958
 ModelR2C3 = DressUpModel {
 }
 ModelR1C6 = DressUpModel {
 }
 GetAnAppearanceSourceFromVisual = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2742
 OnMouseWheel = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:1968
 SetAppearanceTooltip = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2859
 NUM_ROWS = 3
 RefreshVisualsList = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2692
 ShadowLineTop = Texture {
 }
 SelectVisual = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2759
 searchType = 1
 CreateSlotButtons = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:1740
 ResetPage = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2238
 BackgroundTile = Texture {
 }
 ModelR3C1 = DressUpModel {
 }
 SetTransmogrifierAppearancesShown = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2155
 BGCornerBottomRight = Texture {
 }
 ModelR3C6 = DressUpModel {
 }
 RightClickDropDown = BetterWardrobeModelRightClickDropDown {
 }
 ShadowCornerTopLeft = Texture {
 }
 GetActiveSlotInfo = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2377
 ModelR1C4 = DressUpModel {
 }
 OverlayShadowTop = Texture {
 }
 OnLoad = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:1822
 PendingTransmogFrame = Frame {
 }
 PAGE_SIZE = 18
 ValidateChosenVisualSources = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:3270
 OverlayShadowTopRight = Texture {
 }
 chosenVisualSources = <table> {
 }
 GetActiveSlot = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:2078
 ChangeModelsSlot = <function> defined @BetterWardrobe/Modules/Wardrobe.lua:1997
 ShadowCornerTop = Texture {
 }
 ModelR2C5 = DressUpModel {
 }
 OverlayShadowR`

**Comment by agentschmitt** [comment]
This can be fixed by change in line 160
ConvertRGB_to_LAB -> addon:ConvertRGB_to_LAB

**Comment by SLOKnightfall** [comment]
Fixed in next release
