### ISSUE TITLE
Error when adding a set to Collection List

### ISSUE THREAD

**Issue by michael-farwell** [SLOKnightfall/BetterWardrobe#341]
Message: ...ace/AddOns/BetterWardrobe/Modules/CollectionList.lua:141: attempt to call field 'GetSetSources' (a nil value)
Time: Sat Jan 28 08:06:24 2023
Count: 2
Stack: ...ace/AddOns/BetterWardrobe/Modules/CollectionList.lua:141: attempt to call field 'GetSetSources' (a nil value)
[string "@Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua"]:141: in function `UpdateList'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:6108: in function `func'
[string "@Interface/AddOns/BetterWardrobe/Libs/UIDropDownMenu/UIDropDownMenu.lua"]:905: in function `BW_UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:139_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:139_OnClick"]:1>

Locals: self = <table> {
 UpdateList = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:117
 SelectedCollectionList = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:503
 GenerateSourceListView = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Sources.lua:424
 BuildCollectionList = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:17
 AddMogItData = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:405
 AddList = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:413
 GenerateListView = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:550
 CurrentList = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:493
 IsInList = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:453
 TSMGroupExport = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:642
 Dropdown_Initialize = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:303
 CreateDropdown = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:332
 ListCount = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:479
 DeleteList = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:438
 Dropdown_OnClick = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:295
 BuildShoppingList = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:101
 RenameList = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:427
 showAll = true
 OptionButton_OnClick = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:355
}
type = "set"
typeID = 522
add = true
sourceID = nil
addSet = false
setName = nil
setInfo = nil
itemModID = nil
selectedList = 1
collectionList = <table> {
 set = <table> {
 }
 item = <table> {
 }
 name = "CollectionList"
 extraset = <table> {
 }
}
sources = nil
(*temporary) = nil
(*temporary) = 522
(*temporary) = "attempt to call field 'GetSetSources' (a nil value)"
CollectionList = <table> {
 UpdateList = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:117
 SelectedCollectionList = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:503
 GenerateSourceListView = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Sources.lua:424
 BuildCollectionList = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:17
 AddMogItData = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:405
 AddList = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:413
 GenerateListView = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:550
 CurrentList = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:493
 IsInList = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:453
 TSMGroupExport = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:642
 Dropdown_Ini

**Comment by SLOKnightfall** [comment]
Should be fixed in the next update
