### ISSUE TITLE
Sets, Extra tabs not displaying content

### ISSUE THREAD

**Issue by M-Munk** [SLOKnightfall/BetterWardrobe#348]
I disabled all mods except BetterWardrobe and these are the lua errors I get when trying to view sets and extras. 

Message: Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:6903: attempt to call field '?' (a nil value)
Time: Sun Feb 12 01:54:17 2023
Count: 1
Stack: Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:6903: attempt to call field '?' (a nil value)
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:6903: in function <Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:6899>
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:6951: in function `UpdateSets'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:7540: in function `ResetPage'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:6891: in function `Refresh'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:6798: in function <Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:6786>
[string "=[C]"]: in function `SetShown'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:1299: in function `SetTab'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:1187: in function `ClickTab'
[string "*Wardrobe.xml:450_OnClick"]:1: in function <[string "*Wardrobe.xml:450_OnClick"]:1>

Locals: model = DressUpModel {
 RefreshTooltip = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3225
 OnLeave = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3308
 OnShow = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3313
 OnLoad = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3184
 OnHide = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3317
 cameraID = 1027
 Border = Texture {
 }
 OnEvent = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3198
 SetInfo = Frame {
 }
 CollectionListVisual = Frame {
 }
 OnModelLoaded = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3321
 TransmogStateTexture = Texture {
 }
 OnMouseDown = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3204
 OnEnter = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3219
 Favorite = Frame {
 }
 0 = <userdata>
}
_ = "Dark Iron Dwarf"
raceFilename = "DarkIronDwarf"
gender = 3
(*temporary) = nil
(*temporary) = "attempt to call field '?' (a nil value)"
addon = <table> {
 TransmogVendorSizeUpdated = true
 ViewDelay = 3
 useAltSet = false
 modules = <table> {
 }
 SecureHook = <function> defined @Interface/AddOns/BetterWardrobe/Libs/AceHook-3.0/AceHook-3.0.lua:335
 GetBlizzID = <function> defined @Interface/AddOns/BetterWardrobe/Data/DataBase.lua:426
 MogIt = <table> {
 }
 IsEnabled = <function> defined @Interface/AddOns/BetterWardrobe/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 GetActiveCategory = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:213
 RefreshCharConfig = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Core.lua:1163
 RegisterMessage = <function> defined @Interface/AddOns/BetterWardrobe/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Interface/AddOns/BetterWardrobe/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 validSetCache = <table> {
 }
 SortItems = <function> defined @Interface/AddOns/BetterWardrobe/Modules/SortingFunctions.lua:538
 GetBaseList = <function> defined @Interface/AddOns/BetterWardrobe/Data/DataBase.lua:410
 db = <table> {
 }
 SetEnabledState = <function> defined @Interface/AddOns/BetterWardrobe/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Interface/AddOns/BetterWardrobe/Libs/AceHook-3.0/AceHook-3.0.lua:273
 InitExtendedSetsSwap = <function> defined @Interface/AddOns/BetterWardrobe/Plugins/ExtendedTransmog.lua:6
 OnEnable = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Core.lua:1254
 RefreshOutfitData = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Core.lua:894
 GetArtifactSourceInfo = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Artif

Message: Usage: local apppearances = C_TransmogSets.GetSetPrimaryAppearances(transmogSetID)
Time: Sun Feb 12 01:56:32 2023
Count: 8
Stack: Usage: local apppearances = C_TransmogSets.GetSetPrimaryAppearances(transmogSetID)
[string "=[C]"]: in function `GetSetPrimaryAppearances'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:3236: in function `RefreshTooltip'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:3222: in function <Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3219>

Locals: (*temporary) = "Usage: local apppearances = C_TransmogSets.GetSetPrimaryAppearances(transmogSetID)"

Message: Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:6903: attempt to call field '?' (a nil value)
Time: Sun Feb 12 01:57:43 2023
Count: 1
Stack: Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:6903: attempt to call field '?' (a nil value)
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:6903: in function <Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:6899>
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:7056: in function `UpdateSets'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:7540: in function `ResetPage'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:6891: in function `Refresh'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:6798: in function <Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:6786>
[string "=[C]"]: in function `SetShown'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:1299: in function `SetTab'
[string "@Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua"]:1187: in function `ClickTab'
[string "*Wardrobe.xml:485_OnClick"]:1: in function <[string "*Wardrobe.xml:485_OnClick"]:1>

Locals: model = DressUpModel {
 0 = <userdata>
 OnEnter = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3219
 Border = Texture {
 }
 OnMouseDown = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3204
 cameraID = 1027
 RefreshTooltip = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3225
 TransmogStateTexture = Texture {
 }
 OnShow = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3313
 OnLoad = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3184
 OnHide = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3317
 OnEvent = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3198
 CollectionListVisual = Frame {
 }
 OnLeave = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3308
 SetInfo = Frame {
 }
 Favorite = Frame {
 }
 OnModelLoaded = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Wardrobe.lua:3321
}
_ = "Dark Iron Dwarf"
raceFilename = "DarkIronDwarf"
gender = 3
(*temporary) = nil
(*temporary) = "attempt to call field '?' (a nil value)"
addon = <table> {
 TransmogVendorSizeUpdated = true
 ViewDelay = 3
 useAltSet = false
 modules = <table> {
 }
 SecureHook = <function> defined @Interface/AddOns/BetterWardrobe/Libs/AceHook-3.0/AceHook-3.0.lua:335
 GetBlizzID = <function> defined @Interface/AddOns/BetterWardrobe/Data/DataBase.lua:426
 MogIt = <table> {
 }
 IsEnabled = <function> defined @Interface/AddOns/BetterWardrobe/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 GetActiveCategory = <function> defined @Interface/AddOns/BetterWardrobe/Modules/CollectionList.lua:213
 RefreshCharConfig = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Core.lua:1163
 RegisterMessage = <function> defined @Interface/AddOns/BetterWardrobe/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Interface/AddOns/BetterWardrobe/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 validSetCache = <table> {
 }
 SortItems = <function> defined @Interface/AddOns/BetterWardrobe/Modules/SortingFunctions.lua:538
 GetBaseList = <function> defined @Interface/AddOns/BetterWardrobe/Data/DataBase.lua:410
 db = <table> {
 }
 SetEnabledState = <function> defined @Interface/AddOns/BetterWardrobe/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Interface/AddOns/BetterWardrobe/Libs/AceHook-3.0/AceHook-3.0.lua:273
 InitExtendedSetsSwap = <function> defined @Interface/AddOns/BetterWardrobe/Plugins/ExtendedTransmog.lua:6
 OnEnable = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Core.lua:1254
 RefreshOutfitData = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Core.lua:894
 GetArtifactSourceInfo = <function> defined @Interface/AddOns/BetterWardrobe/Modules/Artif

**Comment by zcourge** [comment]
I went into the changelog, and saw that some lines were updated in the last version, and those updated lines (before the update) is the same that is throwing an error now, so I tried to fix it, and so far it seems to be working.

Open up BetterWardrobe/Modules/Wardrobe.lua, navigate to line 6903 (inside function SetModelUnit), and change the line from

`local force =  addon.Globals.mods[addon.Profile.TooltipPreview_SwapModifier]()`

to

`local force =  addon.Profile.TooltipPreview_SwapModifier ~= L["None"] and addon.Globals.mods[addon.Profile.TooltipPreview_SwapModifier]()`

**Comment by M-Munk** [comment]
That seems to fix the issue for me, thank you!

**Comment by aepracorn** [comment]
That appears to have worked for me too. Ty so much.

**Comment by SLOKnightfall** [comment]
Thanks for the fix.  I'll get a update out shortly
