### ISSUE TITLE
Worgen altered form swap button is blocking the dropdown list for weapon transmogs, please fix! (

### ISSUE THREAD

**Issue by tethys-ocean** [SLOKnightfall/BetterWardrobe#353]
DIALOG
<1> GlobalFXDialogModel Scene
HIGH
<33> UIParent.20a18d22260
MEDIUM
-><600> Better WardrobeCollection Frame.Altered FormSwapButton
<600>
<500> WardrobeFrame.NineSlice
<121> UIWidgetPowerBarContainerFrame.FrontModel Scene
<70> UIWidgetPowerBarContainerFrame.BackModel Scene
<51> Objective TrackerUIWidgetContainer.FrontModel Scene
<51> UIWidgetCenterScreenContainerFrame.FrontModel Scene
<51> UIWidget TopCenterContainerFrame.FrontModel Scene
<4> BetterWardrobeCollection FrameWeapon DropDownButton
<4> BetterWardrobeCollection FrameWeapon DropDown ButtonHighlight Texture
<4> Better WardrobeCollection Frame Weapon DropDownButton Normal Texture
<3> BetterWardrobeCollection FrameWeapon DropDown
<3>
BetterWardrobeCollection FrameWeapon DropDown Middle
BetterWardrobeCollection Frame.AlteredForm SwapButton.Portrait
<3>
BW_SortDropDown
<3>
BW_SortDropDown Middle TOPLEFT 00
<2> BetterWardrobeCollection Frameme BOTTOMRIGHT 00
<2> BetterWardrobeCollection Frame.Items Collection Frame.NineSlice
<2> BetterWardrobeCollection Frame.Items Collection Frame
<2>
<2>
<2>
BetterWardrobeCollection
<2> Better WardrobeCollection
<1> Weak AurasFrame
Frame.Items Collection Frame.BGCorner TopRight
Frame.Items Collection Frame.Shadow Corner TopRight
WardrobeFrame.NineSlice.LeftEdge
<1> WardrobeFrame
<1>
WardrobeFrame.NineSlice.RightEdge
WardrobeFrame.NineSlice. Top Edge
age
<1> Weak AurasAttachToMouseFrame robeFrame.NineSlice. TopLeftCorner
<1> Timer Tracker htCorner
WardrobeFrame.NineSlice. TopRightCorner
<1> GlobalFXMediumModel Scene
ottomEdge
Better WardrobeCollection Frame.Items Collection Frame.Background Tile
BetterWardrobeCollection Frame.Items Collection Frame.Bg ghtCorner
WardrobeFrameBg
<0> ELVUIParent nap Disabled
<0> Narci_GuideLineFrame
<0> UIParentA
<0> UIWidgetCenterScreenContainerFrame.BackModelScene tomLeftCorner
<0> Objective TrackerUIWidgetContainerBackModelSceneBottomRightCorner
<0> UIWidgetTopCenterContainerFrame.BackModel Scene
LOW
WORLD
<1> MotionSicknessFrame
<52> UIWidgetBelow MinimapContainerFrame.FrontModel Scene
<1> DebuffFrame
<1> GlobalFXBackgroundModelScene
<1> UIWidgetBelow MinimapContainerFrame.BackModel Scene
BACKGROUND
<0> WorldFrame
ANCHORS
true
WardrobeFrame.NineSlice.BottomEdge
<1> TOPRIGHT WardrobeFrame TOPRIGHT -50.00 -50.00
SOURCE
Interface/AddOns/BetterWardrobe/Modules/Wardrobe.xml:717

**Comment by SLOKnightfall** [comment]
Should be fixed in the next update
