### ISSUE TITLE
Transmogs showing in reverse order

### ISSUE THREAD

**Issue by RaefWolfe** [SLOKnightfall/BetterWardrobe#355]
The most recent expansion is shown at the last page, rather than the first. I also cannot find options like "no helm" when I'm at the transmogrifier.

**Comment by SLOKnightfall** [comment]
The reversed sorting order should be fixed in the next update.

**Comment by Ketrel** [comment]
The reverse issue is happening for saved sets Alphabetically.
(Also the drop down for sort by is not positioned well in extra large mode and I think the others as well)
![Wow_2023-04-06_21-50-54](https://user-images.githubusercontent.com/1002607/230524370-043872ac-832a-47fa-a730-acdef6f0666c.png)

**Comment by Ketrel** [comment]
I think the issue comes from

```lua
local function SortOrder(a, b)
	if not a or not b then return end
	if IsModifierKeyDown() then 
		return a < b
	else
		return a > b
	end
end
```
It looks like naturally "newest to oldest" and "alphabetical" are reverses of each other for the purposes of "a > b" comparisons.
