### ISSUE TITLE
BetterWardrobe & PetTracker bug

### ISSUE THREAD

**Issue by ghost** [SLOKnightfall/BetterWardrobe#361]
Hello,

A bit annoying bug when this addon interacts with PetTracker:

Reproduce:
1) Open Appearances tab
2) Open "Rivals" tab right after
3) You will see tabs on top of each other inside Rivals tab (look at the top)
4) Hit reload and open Rivals tab right away, you will notice no issues
![image](https://user-images.githubusercontent.com/122007087/235331039-d45fe498-82f2-4c30-9095-6e2902e58f70.png)

Please consider some kind of a solution, as PetTracker author abandoned the project years ago and only shows up for a minor update during expansion hits. All sorts of visual bugs are met with "tough luck, delete it" kind of attitude.

Thank you!!

**Comment by SLOKnightfall** [comment]
It looks like its just an issue of BetterWardrobe's frames not being properly hidden when the new Rivals tab is selected.  I should be able to come up with a fix for the issue.

**Comment by Rezy942** [comment]
Thank you so much im glad this can be done without relying on pettracker author :)
And thank you for the wonderful addon, I and many others cant live without it!

**Comment by SLOKnightfall** [comment]
Took a while but I finally figured out how to fix the issue in the next update.
