### ISSUE TITLE
Error when clicking toys

### ISSUE THREAD

**Issue by loz100loz** [SLOKnightfall/BetterWardrobe#364]
Keep getting the same error when clicking on toys

``12x [ADDON_ACTION_FORBIDDEN] AddOn 'BetterWardrobe' tried to call the protected function 'UseToy()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseToy'
[string "@Blizzard_Collections/Blizzard_ToyBox.lua"]:181: in function `ToySpellButton_OnClick'
[string "*Blizzard_ToyBox.xml:10_OnClick"]:4: in function <[string "*Blizzard_ToyBox.xml:10_OnClick"]:1>``

**Comment by Sherlockell** [comment]
Same issue here. Seems to go away when reloading, but bug is present every time on initial login

3x [ADDON_ACTION_FORBIDDEN] AddOn 'BetterWardrobe' tried to call the protected function 'UseToy()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `UseToy'
[string "@Blizzard_Collections/Blizzard_ToyBox.lua"]:181: in function `ToySpellButton_OnClick'
[string "*Blizzard_ToyBox.xml:10_OnClick"]:4: in function <[string "*Blizzard_ToyBox.xml:10_OnClick"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by Sherlockell** [comment]
@SLOKnightfall the issue above now seems to be fixed in the latest update, for me at least. Using Elvui, I can now use toys directly from the Toy collection without errors. Thanks so much for looking into this 👍

**Comment by SLOKnightfall** [comment]
Glad to hear it.  Tracking down the taint issues causing it was a royal pain, but worth it if thing are working again.
