### ISSUE TITLE
Dropdown.lua:148: calling 'IsMouseOver' on bad self (Usage: local isMouseOver = self:IsMouseOver([offsetTop, offsetBottom, offsetLeft, offsetRight]))

### ISSUE THREAD

**Issue by Ookami313** [SLOKnightfall/BetterWardrobe#368]
I've been getting the following error for a while, but kept forgetting to report it because it only seems to happen every so often. When I ATL+TAB out of the game to do something like look up something on Wowhead or the like, then click on the game frame again to re-enter the game I keep getting the following error. I thought that the issue would occur each time I either reload or log out and back in, but it seems to be just a hit or miss occurrence. Thanks.

1x ...erWardrobe/Libs/Sushi-3.1-5/classes/drops/Dropdown.lua:148: calling 'IsMouseOver' on bad self (Usage: local isMouseOver = self:IsMouseOver([offsetTop, offsetBottom, offsetLeft, offsetRight]))
[string "=[C]"]: in function `IsMouseOver'
[string "@BetterWardrobe/Libs/Sushi-3.1-5/classes/drops/Dropdown.lua"]:148: in function <...erWardrobe/Libs/Sushi-3.1/classes/drops/Dropdown.lua:147>
[string "@BetterWardrobe/Libs/Sushi-3.1-5/classes/drops/Dropdown.lua"]:153: in function <...erWardrobe/Libs/Sushi-3.1/classes/drops/Dropdown.lua:147>
[string "=(tail call)"]: ?
[string "@BetterWardrobe/Libs/Sushi-3.1-5/classes/drops/Dropdown.lua"]:93: in function <...erWardrobe/Libs/Sushi-3.1/classes/drops/Dropdown.lua:92>

Locals:
(*temporary) = SimpleCheckout {
 0 = <userdata>
 RightOutside = Line {
 }
 RightInside = Line {
 }
 Background = Frame {
 }
 CalculateDesiredSize = <function> defined @Blizzard_StoreUI/Blizzard_Shared_SimpleCheckout.lua:101
 OnShow = <function> defined @Blizzard_StoreUI/Blizzard_Shared_SimpleCheckout.lua:54
 OnLoad = <function> defined @Blizzard_StoreUI/Blizzard_Shared_SimpleCheckout.lua:25
 OnHide = <function> defined @Blizzard_StoreUI/Blizzard_Shared_SimpleCheckout.lua:61
 LeftOutside = Line {
 }
 OnExternalLink = <function> defined @Blizzard_StoreUI/Blizzard_Shared_SimpleCheckout.lua:83
 TopInside = Line {
 }
 BottomOutside = Line {
 }
 CloseButton = Button {
 }
 TopOutside = Line {
 }
 BottomInside = Line {
 }
 OnEvent = <function> defined @Blizzard_StoreUI/Blizzard_Shared_SimpleCheckout.lua:29
 LeftInside = Line {
 }
 RecalculateSize = <function> defined @Blizzard_StoreUI/Blizzard_Shared_SimpleCheckout.lua:139
 OnRequestNewSize = <function> defined @Blizzard_StoreUI/Blizzard_Shared_SimpleCheckout.lua:75
}

**Comment by SLOKnightfall** [comment]
I've removed the Sushi library in the last release, so you should not be seeing the errors any more.
