### ISSUE TITLE
Some actual support would be amazing.

### ISSUE THREAD

**Issue by Fubuflex** [SLOKnightfall/BetterWardrobe#377]
This addon has been full of bugs and broken windows for months now. I see all the new sets and transmogs getting listed so i know the team is adding bits trying to keep this addon current but guys, you have to fix the issues. 

How many of us now are seeing errors nearly every time we try to preview a piece of clothing or a weapon? How many of us are getting errors pop up from better wardrobe just for trying to cast a spell on our hotbars..

Can we firstly get someone from the team to confirm they at least know about these issues and then have some sort of idea posted of when or roughly when a fix can be implemented?

We fully understand Blizzards UI has changed and that's caused issues across most addons, however you would be hard pressed to find an addon as broken as this one is right now.

Please fix retail better wardrobe. There really isn't any other addon like it.

**Comment by KTBL-KS** [comment]
I agree with you the addon has not seen support and the developer has not even posted if the project is no loneger supported.

**Comment by gothnate** [comment]
You can fix the LUA error by adding two dashes to lines 316 to 320 in the DressingRoom.lua file. The file is located here: \Interface\AddOns\BetterWardrobe\Modules

It should look like this when finished:
![image](https://github.com/SLOKnightfall/BetterWardrobe/assets/73508750/4e8ec7b3-d1c6-4ee0-9737-3a5a7d711173)
You'll need something to open it, like VS Code or Notepad++. You can use Windows' Notepad, but you'll need to find the lines in the file that matches the image above.

**Comment by KTBL-KS** [comment]
That’s wonderful thanks 😊 will definitely do it tomorrow.

**Comment by Fubuflex** [comment]
Amazing will try this fix and let the boys know. :)
