### ISSUE TITLE
Hiding item causes error

### ISSUE THREAD

**Issue by ChloeMarie** [SLOKnightfall/BetterWardrobe#378]
Got this error when right-clicking a cloak appearance and trying to hide it. Nothing happened other than the error.

1x BetterWardrobe/Modules/BlizzardAPI.lua:53: Usage: GetItemInfoInstant(itemID|"name"|"itemlink")
[string "=[C]"]: in function `GetItemInfoInstant'
[string "@BetterWardrobe/Modules/BlizzardAPI.lua"]:53: in function <BetterWardrobe/Modules/BlizzardAPI.lua:52>
[string "@BetterWardrobe/Modules/BlizzardAPI.lua"]:64: in function `GetTransmogLocation'
[string "@BetterWardrobe/Modules/Wardrobe.lua"]:3420: in function <BetterWardrobe/Modules/Wardrobe.lua:3415>
[string "@BetterWardrobe/Modules/Wardrobe.lua"]:3489: in function `func'
[string "@BetterWardrobe/Libs/UIDropDownMenu/UIDropDownMenu.lua"]:905: in function `BW_UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:139_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:139_OnClick"]:1>

Locals:
(*temporary) = nil

**Comment by SLOKnightfall** [comment]
Fixed in the next release.
