### ISSUE TITLE
Couldn't open BetterWardrobe/Libs/TaintLess/TaintLess.xml

### ISSUE THREAD

**Issue by ntowle** [SLOKnightfall/BetterWardrobe#382]
```
4x Interface\FrameXML\Bindings.xml:1 Interface\FrameXML\Bindings.xml:34 Couldn't open BetterWardrobe/Libs/TaintLess/TaintLess.xml
4x Interface\FrameXML\Bindings.xml:34 Couldn't open BetterWardrobe/Libs/TaintLess/TaintLess.xml
```

https://github.com/SLOKnightfall/BetterWardrobe/tree/28b6c040ff3abe2f1d99843aefcabe98715b18fc/Libs/TaintLess

There is no TaintLess.xml present even though it's defined in BetterWardrobe.toc, leading to this error.

**Comment by SLOKnightfall** [comment]
Fixed in 4.11.2
