### ISSUE TITLE
Bug Recent update broke elvui skin

### ISSUE THREAD

**Issue by Konsafloof** [SLOKnightfall/BetterWardrobe#383]
![Wow_Nuj2bDiEKS](https://github.com/SLOKnightfall/BetterWardrobe/assets/109347817/aaa6a887-fd80-4a45-a12f-f010e72e2c43)

Recent update broke elvui skin + removed search bar

Addons enabled
BetterWardrobe
Elvui
BetterAddonList

**Comment by SLOKnightfall** [comment]
Should be fixed in the next update.

**Comment by Konsafloof** [comment]
Thank you <3
