### ISSUE TITLE
Extra Window since last release.

### ISSUE THREAD

**Issue by zaphon** [SLOKnightfall/BetterWardrobe#385]
Since the release that came out yesterday, when I open the appearance tabs (ctrl-p) and look at sets, when I hit the X in the upper right corner to close it, it closes but leaves behind a blank window still titled Appearances that I also have to close.

![2023-09-10_11-33-27](https://github.com/SLOKnightfall/BetterWardrobe/assets/1243870/ce115d60-0b14-447f-a320-3a6e48684b85)

**Comment by SLOKnightfall** [comment]
Fixed in the next release
