### ISSUE TITLE
'BetterWardrobe' tried to call the protected function 'SetGuildRankOrder()'

### ISSUE THREAD

**Issue by darbiirue** [SLOKnightfall/BetterWardrobe#390]
Hi there. I'm getting a LOT of BetterWardrobe LUA errors for some reason. I'm not sure what exactly is causing them, but they were preventing me from doing anything guild-related.

`1x [ADDON_ACTION_FORBIDDEN] AddOn 'BetterWardrobe' tried to call the protected function 'SetGuildRankOrder()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetGuildRankOrder'
[string "@Blizzard_Communities/GuildRoster.lua"]:174: in function `func'
[string "@SharedXML/UIDropDownMenu.lua"]:1008: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:131_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:131_OnClick"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}
`

`1x [ADDON_ACTION_FORBIDDEN] AddOn 'BetterWardrobe' tried to call the protected function 'GuildSetLeader()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `GuildSetLeader'
[string "@FrameXML/ChatFrame.lua"]:1747: in function `?'
[string "@FrameXML/ChatFrame.lua"]:5261: in function <FrameXML/ChatFrame.lua:5227>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4938: in function <FrameXML/ChatFrame.lua:4937>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4974: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:141_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:141_OnEnterPressed"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}
`

**Comment by SLOKnightfall** [comment]
I redid a bunch of stuff to fix some of the taint issues that cause the blocked actions.  Hopefully it fixes what you are encountering

**Comment by darbiirue** [comment]
> I redid a bunch of stuff to fix some of the taint issues that cause the blocked actions. Hopefully it fixes what you are encountering

Looks like it helped with the guild part, but I received another bug tonight when trying to preview something:

`1x ...rfaceBetterWardrobe/Modules/SavedOutfits.lua:213: attempt to call method 'GetLastOutfitID' (a nil value)
[string "@BetterWardrobe/Modules/SavedOutfits.lua"]:213: in function <...rfaceBetterWardrobe/Modules/SavedOutfits.lua:210>
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:3245: in function <FrameXML/UIParent.lua:3231>
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML/DressUpFrames.lua"]:321: in function `DressUpFrame_Show'
[string "@FrameXML/DressUpFrames.lua"]:79: in function <FrameXML/DressUpFrames.lua:76>
[string "=(tail call)"]: ?
[string "@FrameXML/DressUpFrames.lua"]:4: in function `DressUpLink'
[string "@FrameXML/ItemButtonTemplate.lua"]:391: in function <FrameXML/ItemButtonTemplate.lua:371>
[string "=[C]"]: ?
[string "=[C]"]: in function `HandleModifiedItemClick'
[string "@FrameXML/ItemRef.lua"]:457: in function <FrameXML/ItemRef.lua:7>
[string "=[C]"]: ?
[string "@Blizzard_CombatLog/Blizzard_CombatLog.lua"]:3535: in function <...aceBlizzard_CombatLog/Blizzard_CombatLog.lua:3476>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetItemRef'
[string "@FrameXML/ChatFrame.lua"]:4070: in function `ChatFrame_OnHyperlinkShow'
[string "*ChatFrame.xml:23_OnHyperlinkClick"]:1: in function <[string "*ChatFrame.xml:23_OnHyperlinkClick"]:1>
[string "=[C]"]: ?

Locals:
self = BetterWardrobeDressUpFrameDropDown {
 0 = <userdata>
 LoadOutfit = <function> defined @BetterWardrobe/Modules/DressingRoom.lua:757
 Left = BetterWardrobeDressUpFrameDropDownLeft {
 }
 CheckOutfitForSave = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:370
 OnOutfitModified = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:252
 IsOutfitDressed = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:317
 Button = BetterWardrobeDressUpFrameDropDownButton {
 }
 width = 163
 IsDefaultSet = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:415
 Icon = BetterWardrobeDressUpFrameDropDownIcon {
 }
 maxMenuStringWidth = 190
 Middle = BetterWardrobeDressUpFrameDropDownMiddle {
 }
 OnShow = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:210
 OnLoad = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:197
 Right = BetterWardrobeDressUpFrameDropDownRight {
 }
 Text = BetterWardrobeDressUpFrameDropDownText {
 }
 BetterWardrobeOutfitDropDown_OnHide = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:216
 OnEvent = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:225
 SaveButton = Button {
 }
 minMenuStringWidth = 127
 ShouldReplaceInvalidSources = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:419
 GetItemTransmogInfoList = <function> defined @BetterWardrobe/Modules/DressingRoom.lua:749
 UpdateSaveButton = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:238
 SelectOutfit = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:258
 OnOutfitSaved = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:246
 noResize = 1
}
(*temporary) = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:258
(*temporary) = BetterWardrobeDressUpFrameDropDown {
 0 = <userdata>
 LoadOutfit = <function> defined @BetterWardrobe/Modules/DressingRoom.lua:757
 Left = BetterWardrobeDressUpFrameDropDownLeft {
 }
 CheckOutfitForSave = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:370
 OnOutfitModified = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:252
 IsOutfitDressed = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:317
 Button = BetterWardrobeDressUpFrameDropDownButton {
 }
 width = 163
 IsDefaultSet = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:415
 Icon = BetterWardrobeDressUpFrameDropDownIcon {
 }
 maxMenuStringWidth = 190
 Middle = BetterWardrobeDressUpFrameDropDownMiddle {
 }
 OnShow = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:210
 OnLoad = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:197
 Right = BetterWardrobeDressUpFrameDropDownRight {
 }
 Text = BetterWardrobeDressUpFrameDropDownText {
 }
 BetterWardrobeOutfitDropDown_OnHide = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:216
 OnEvent = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:225
 SaveButton = Button {
 }
 minMenuStringWidth = 127
 ShouldReplaceInvalidSources = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:419
 GetItemTransmogInfoList = <function> defined @BetterWardrobe/Modules/DressingRoom.lua:749
 UpdateSaveButton = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:238
 SelectOutfit = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:258
 OnOutfitSaved = <function> defined @BetterWardrobe/Modules/SavedOutfits.lua:246
 noResize = 1
}
(*temporary) = nil
(*temporary) = BetterWardrobeDressUpFrameDropDown {
 0 = <userdata>
 LoadOutfit = <function> defined @BetterWardrobe/Modules/DressingRoom.lua:757
 Left = BetterWardr`

**Comment by SLOKnightfall** [comment]
Glad that the guild stuff is looking fixed.  A fix for the other error should be out shortly.
