### ISSUE TITLE
Not sure what triggers this error but I saw it when trying to find an error from a different addon.

### ISSUE THREAD

**Issue by gotex007** [SLOKnightfall/BetterWardrobe#396]
62x [ADDON_ACTION_BLOCKED] AddOn 'BetterWardrobe' tried to call the protected function 'MountJournal:SetShown()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetShown'
[string "@Blizzard_Collections/Blizzard_Collections.lua"]:62: in function <Blizzard_Collections/Blizzard_Collections.lua:54>
[string "=[C]"]: in function `CollectionsJournal_UpdateSelectedTab'
[string "@Blizzard_Collections/Blizzard_Collections.lua"]:6: in function `CollectionsJournal_SetTab'
[string "@BetterWardrobe/Modules/Wardrobe.lua"]:1817: in function `CheckLatestAppearance'
[string "@BetterWardrobe/Modules/Wardrobe.lua"]:1799: in function <BetterWardrobe/Modules/Wardrobe.lua:1782>

**Comment by SLOKnightfall** [comment]
Can you try clearing the error cache for bug grabber/bug sack and see if the message changes

**Comment by gotex007** [comment]
I mean like I said I have no idea what caused the error. I just happened to see it. I'll go ahead and close this ticket and reopen it if I see it again.
