### ISSUE TITLE
Retail Bug 10.1.5

### ISSUE THREAD

**Issue by GeoRam2016** [SLOKnightfall/BetterWardrobe#400]
Hi
there is a mini Bug in Version 4.14.4

1x BetterWardrobe/Modules/Wardrobe.lua:5089: Usage: local baseTransmogSetID = C_TransmogSets.GetBaseSetID(transmogSetID)
[string "=[C]"]: in function `GetBaseSetID'
[string "@BetterWardrobe/Modules/Wardrobe.lua"]:5089: in function `GetBaseSetData'
[string "@BetterWardrobe/Modules/Wardrobe.lua"]:5168: in function `ResetBaseSetNewStatus'
[string "@BetterWardrobe/Modules/Wardrobe.lua"]:7025: in function <BetterWardrobe/Modules/Wardrobe.lua:7002>

Locals:
(*temporary) = nil

**Comment by SLOKnightfall** [comment]
Fixed in the next release.
