### ISSUE TITLE
Keybindings no longer obviously part of BetterWardrobe

### ISSUE THREAD

**Issue by mbattersby** [SLOKnightfall/BetterWardrobe#401]
Since DF header= hasn't worked in the keybindings (just adds a spacer) so the bindings aren't obviously attached to the addon.

![image](https://github.com/SLOKnightfall/BetterWardrobe/assets/1300207/acc84e0c-fcc9-41cf-b70d-32eefbb04a33)

I think the fix is probably to remove header= and use category="BINDING_HEADER_BETTERWARDROBE" in Bindings.xml

**Comment by mbattersby** [comment]
See also https://github.com/Stanzilla/WoWUIBugs/issues/305

**Comment by SLOKnightfall** [comment]
Finally fixed in next version
