### ISSUE TITLE
Bug: recent update broke Elvui skin

### ISSUE THREAD

**Issue by Konsafloof** [SLOKnightfall/BetterWardrobe#404]
Recent update(BetterWardrobe-4.16.~) broke elvui skin and removed the search bar
![Wow_0lXTlTYkFC](https://github.com/SLOKnightfall/BetterWardrobe/assets/109347817/919eeda8-b0da-496a-a790-3aa211f2e56c)

**Comment by SLOKnightfall** [comment]
LOL Missing searchbox and the ticket number is 404.  Fixed in next update

**Comment by Konsafloof** [comment]
Oddly blizzards default background still shows
