### ISSUE TITLE
Bug: Default blizzard background shows when using Elvui

### ISSUE THREAD

**Issue by Konsafloof** [SLOKnightfall/BetterWardrobe#405]
Sorry about another bug report

Before BetterWardrobe-4.16
![Wow_lcjRUVABeT](https://github.com/SLOKnightfall/BetterWardrobe/assets/109347817/f87a345e-80c2-44f7-8823-ade7211b1278)

After BetterWardrobe-4.16
![Wow_HpbyQBQNHw](https://github.com/SLOKnightfall/BetterWardrobe/assets/109347817/88030f73-87a2-4a5f-9683-c8f5277458ef)

**Comment by SLOKnightfall** [comment]
@Konsafloof No worries about putting in bug reports :)

**Comment by Beet4** [comment]
Any updates on this issue? Just recently returned to WoW and noticed that this bug is still there. :)

**Comment by Beet4** [comment]
This seems to be fixed now, isseu can be closed. @SLOKnightfall
