### ISSUE TITLE
Dressing Room: "General Options" and "Import/Export Options" tooltips cover the context menu content when left-clicked

### ISSUE THREAD

**Issue by ryankhart** [SLOKnightfall/BetterWardrobe#418]
Repro Steps:
- Open dressing room while Better Wardrobe is enabled.
- Left-click down on either "General Options" or "Import/Export Options" (notice how the tooltip goes away here.)
- Release left-click.

What I expect to happen:
I expect to view the context menu without obstructions from other UI elements.

What actually happens:
The context menu comes up but the tooltip for "General Options" or "Import/Export Options" shows over the top of the context menu items.

Workaround:
I can either right-click the buttons instead or left-click and drag away from the button, then release to get it to work as expected.

![image](https://github.com/SLOKnightfall/BetterWardrobe/assets/3673962/aa3f1f4f-dd14-44af-9022-dc4912651be6)

It also stays on the HUD even after I close the dressing room window until I open the dressing room and right click one of those buttons.

![image](https://github.com/SLOKnightfall/BetterWardrobe/assets/3673962/ff173ee9-2287-4d91-b129-f49a944023a5)

**Comment by SLOKnightfall** [comment]
This is fixed in the next update.
