### ISSUE TITLE
Can I Mog It? update to Sets count code

### ISSUE THREAD

**Issue by amiyuy** [SLOKnightfall/BetterWardrobe#420]
Hi!  I'm the project manager for Can I Mog It?  We were making an update to our Appearances Sets code and realized that BetterWardrobe uses some of it to show the counter on your Sets too (Yay! I use BetterWardrobe and love it).

We wanted to let you know that what we're changing will break how you are using the Sets code right now and that changes were made to our code try and make it easier and work better for you.

Here's our GitLab issue with links to the commits: https://gitlab.com/toreltwiddler/CanIMogIt/-/issues/316

> ...refactors things so some of the sets code can be modified without needing to copy our code verbatim.
> Any conflicting addons will break due to some of these changes. For BetterWardrobe, please comment out the following lines: BetterWardrobe/Plugins/CanIMogIt.lua: 14~46.
> 
> As for BetterWardrobe, they will need to modify their plugin for CIMI to use the new functions. If what we've supplied isn't sufficient, they can contact us to make more updates to help them out.

If you have any questions please let us know either here or on GitLab.  We're planning to push our update this week.

**Comment by SLOKnightfall** [comment]
Thanks for the heads up.  I've updated things so the next release will now be compatible with both CanIMogIt 10.1.5v1.53 and the changes in 10.2.5v1.54.
