### ISSUE TITLE
Cannot transmog shoulders seperatley 10.2.6

### ISSUE THREAD

**Issue by thecosmicdrake** [SLOKnightfall/BetterWardrobe#425]
The separate shoulder option has not worked for any of my characters since 10.2.6 with BetterWardrobe enabled. All of my characters that I log into are not presented with the second shoulder slot when checking the “transmog each shoulder separately” box. I’ve tested this on a class of each armor type.

When I disable BetterWardrobe this option finally works for me. I've checked other addons and none of them seem to cause the issue, only BetterWardrobe.

**Comment by SLOKnightfall** [comment]
Should be fixed in next update

**Comment by Ketrel** [comment]
What you did to correct it, broke it again for me.
