### ISSUE TITLE
Bug: Collection Journal wont open-LUA error

### ISSUE THREAD

**Issue by jana8878** [SLOKnightfall/BetterWardrobe#43]
All tabs work except the collection journal. I click on the button but I keep getting a LUA error. I even disabled all other addons and i still have the same issue. I just downloaded this addon tonight and it worked for about 10 mins before I couldn't get it to work anymore. 

THank you

Love the add
![WoWScrnShot_100720_212428](https://user-images.githubusercontent.com/71347449/95407759-8bbdc400-08e3-11eb-95da-5f749f76e1de.jpg)
 on please fix! :)

**Comment by SLOKnightfall** [comment]
Fixed in the next version
