### ISSUE TITLE
Saved Transmog profile list needs a scroll bar and min/max height

### ISSUE THREAD

**Issue by JSON-135** [SLOKnightfall/BetterWardrobe#432]
Hey @SLOKnightfall 

I just wanted to open an issue regarding how the profile dropdown works in the saved tab for Betterwardrobe.

Currently as it stands if you have lots of character profiles saved. The dropdown becomes HUGE and goes off the screen making it impossible to properly view your other characters transmog profiles.

Please see image:
https://imgur.com/a/j3HzcRl

Could you please add a scroll wheel to the dropdown list and also give it a min/max height to prevent big lists from going off the screen?

Much love <3

**Comment by SLOKnightfall** [comment]
I finally got this working and it will be in the next update.

**Comment by JSON-135** [comment]
Thank you soooooo much!!!

**Comment by SLOKnightfall** [comment]
And all the work for this gets tossed out due to the new menu system.  On the plus side the new system has built in support for scrolling dropdowns.

**Comment by JSON-135** [comment]
Hahahaha. Of course. It was a great addition while it lasted. The new update broke soooo much. I always appreciate your efforts.
