### ISSUE TITLE
Bug: Extra Set Filters don't work (Collected/Uncollected filter)

### ISSUE THREAD

**Issue by jana8878** [SLOKnightfall/BetterWardrobe#44]
When looking in the tab Extra sets. The filters for "collected" and "uncollected" only don't work. I wanted to look at only the ones I have collected and the filter changed nothing. I also tried just using uncollected and that changed nothing either. 

I disabled all other addons and the issue still occurs.

**Comment by SLOKnightfall** [comment]
Fixed in the next update.
