### ISSUE TITLE
Error: "Has bad mixin: BW_AlertTrackingFeatureMixin"

### ISSUE THREAD

**Issue by FlareStarrr** [SLOKnightfall/BetterWardrobe#449]
`14x BetterWardrobe/Modules/Wardrobe.xml:556 Frame: Has bad mixin: BW_AlertTrackingFeatureMixin`

**Comment by Spennig** [comment]
I got both:

1x Blizzard_SharedXMLBase/Mixin.lua:9: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/Mixin.lua"]:9: in function <Blizzard_SharedXMLBase/Mixin.lua:6>
[string "=(tail call)"]: ?
[string "@BetterWardrobe/Modules/Wardrobe.lua"]:586: in main chunk

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"


And: 

2x BetterWardrobe/Modules/Wardrobe.xml:556 Frame: Has bad mixin: BW_AlertTrackingFeatureMixin
