### ISSUE TITLE
Blizzard's transmog tooltip is modified even with all Tooltip Options disabled

### ISSUE THREAD

**Issue by amiyuy** [SLOKnightfall/BetterWardrobe#45]
I disabled all of the Tooltip Options for BetterWardrobe, but Blizzard's transmog tooltip was still being modified.

When I disabled the Tooltip portion of the addon (BetterWardrobe_Tooltips), the tooltip went back to default.

1. If you're going to modify the Blizzard transmog tooltip, please at least capitalize it the same way.
2. Modifying the Blizzard transmog tooltip should be an option.
3. If all options for tooltips are disabled, no tooltip modification should be happening at all.

v1.10.5

With BetterWardrobe_Tooltips enabled, but all Tooltip Options disabled - https://i.imgur.com/RizwCvW.jpg

With BetterWardrobe_Tooltips disabled - https://i.imgur.com/vYEcZso.jpg

**Comment by SLOKnightfall** [comment]
Thanks for letting me know about the tooltip bugs.  The capitalization is fixed and the tool tips shouldn't be modified if "Show if appearance is known" is unchecked.
