### ISSUE TITLE
BetterWardrobe/Data/DataBase.lua:181: unexpected symbol near ']'

### ISSUE THREAD

**Issue by RedAces** [SLOKnightfall/BetterWardrobe#452]
It seems the version 5.0-beta pushed to Curse has a problematic line 181 in DataBase.lua:
```
--[==[@debug@ 
addon:AddTestSets()
--@end-debug@]==]]==]
```
Removing these lines fixes the issue and your Addon works again :)

**Comment by SLOKnightfall** [comment]
Looks like
