### ISSUE TITLE
Sort by box intersecting in some places

### ISSUE THREAD

**Issue by Raenore** [SLOKnightfall/BetterWardrobe#453]
Hello there,

Just gotten the new BetterWardrobe 5.0.1 and the improvements for TWW (and compat) are great.

However wanted to not a few nitpicks with the "Sort by" dropdown intersecting with data.
![image](https://github.com/user-attachments/assets/0651aac1-ea85-4075-8be9-46755786c2e8)
![image](https://github.com/user-attachments/assets/0a7cc201-3081-4586-864a-c81093a9bbe0)

The one at "Saved sets" is right though.
![image](https://github.com/user-attachments/assets/501c223d-864b-4c89-8b38-a3347bd09e5e)

Mind you, I haven't tested this without ElvUI so it could very much be a ElvUI specific thing. I don't know.

**Comment by paulbuechner** [comment]
Same for me... ElvUI user here, but deactivated the skinning for the Wardrobe.

**Comment by tamikonatsu** [comment]
![image_2024-08-01_201342912](https://github.com/user-attachments/assets/08b0aacf-a46d-441b-8380-298f2e76ffd7)

double outfit boxes in the dressing room as well. I was just going to add the sort by issue for the visuals as I've mentioned it on curseforge. Saves making duplicate report

**Comment by SLOKnightfall** [comment]
Its probably an elvui issue as I haven't updated the elvui skinning file to handle new menu elements

**Comment by tamikonatsu** [comment]
Yup, just elvui skinning file. Due to not using the elvui skin on my collections tab, I also often forget to check stuff like that without elvui on.

**Comment by SLOKnightfall** [comment]
Fixed in next release
