### ISSUE TITLE
Multiple Lua errors with the August 1sr update

### ISSUE THREAD

**Issue by Wanny** [SLOKnightfall/BetterWardrobe#456]
At launch, I get **22** Lua errors, related to:

- "Has bad mixin: BW_UIDropDownMenuButtonMixin" x5
- "Unknown method OnMouseDown in element OnMouseDown" x5
- "Unknown method OnLeave in element OnLeave" x5
- "Unknown method OnEnter in element OnEnter" x5

And single occurrences of
- "Unknown function BetterWardrobeSetsTransmogModelRightClickDropDown_OnLoad in element OnLoad "
- "Couldn't find inherited node: BW_ColorSwatchTemplate"

**Comment by Wanny** [comment]
Also, when opening the Transmogrifier, a Lua error appears with "attempt to index global 'BetterWardrobeOutfitDropDown' (a nil value)"

**Comment by Meilinn** [comment]
I'm having the same Lua errors

**Comment by SLOKnightfall** [comment]
Fixed in 5.0.5

**Comment by Wanny** [comment]
Seems not.

![image](https://github.com/user-attachments/assets/c4cfdb42-e8c6-4407-95c0-db752f14bd1f)

**Comment by Wanny** [comment]
I made sure to update the addon. I'm using version 5.0.7.
