### ISSUE TITLE
Error Upon Login to Character

### ISSUE THREAD

**Issue by WhiteFox097** [SLOKnightfall/BetterWardrobe#461]
Following error received when logging into character completes.
(Should note this error has been present since I came back to playing at the launch of pre-patch. Could be an older issue, not sure but could not locate in list of current issues).

Attempted re-install via Curse, as well as delete (ensuring no folder/files remain in Addons folder) and then fresh install from Curse.

I'd say priority low as it does not re-appear until next login. Can simply close the error for now and it doesn't re-appear during play session.

Message: Interface/AddOns/BetterWardrobe/Libs/UIDropDownMenu/UIDropDownMenuTemplates.xml:184 BetterWardrobeContextMenuFrameButton: Has bad mixin: BW_UIDropDownMenuButtonMixin
Time: Sat Aug  3 14:44:58 2024
Count: 2

**Comment by Wanny** [comment]
This (and the other 21 Lua errors) was supposed to be fixed in version 5.0.5 :C

**Comment by WhiteFox097** [comment]
Just double checked Curse to make sure, and I am running what I assume is latest release version: 5.0.7

**Comment by WhiteFox097** [comment]
Can confirm issue no longer present in release 5.0.8.1

Thanks for the quick update!
