### ISSUE TITLE
Request: Option to remove characters from the saved character list

### ISSUE THREAD

**Issue by FBHawkes** [SLOKnightfall/BetterWardrobe#471]
Title.

I've looked around as best I believe I can and do not see a way to remove characters from the list. It would be a nice option being that I use a lot of trial toons to farm warfront xmog. Also, possibly the ability to rearrange the order of said list. Just a thought!

Love the addon btw! Thank you for that!

**Comment by SLOKnightfall** [comment]
There is already the ability to do so.  Open the addon options and then click on the Saved Outfits tab.  That will list every character saved in the addon DB.  Just click remove button and the character will be removed from the list.
