### ISSUE TITLE
[5.1] Saved Sets don't work - Makes all items hidden

### ISSUE THREAD

**Issue by Raenore** [SLOKnightfall/BetterWardrobe#476]
Hello there,

As of 5.1, saved sets don't seem to work properly anymore and make the items hidden.

Example:
| Saved Set  | Mog Output |
| :-----------:| :-----------: |
| ![image](https://github.com/user-attachments/assets/3f4bce2d-8383-42d4-82ff-74e84b3e5ac5)  | ![image](https://github.com/user-attachments/assets/a1c474c2-4089-45a3-98b6-c32308dbae5b)  |

Example 2:
| Saved Set  | Mog Output |
| :-----------:| :-----------: |
| ![image](https://github.com/user-attachments/assets/6f0fdba5-f569-4f6f-b561-871a0e0c4608) | ![image](https://github.com/user-attachments/assets/4fb2dd97-e8d0-4018-86ea-6b80d73f8e2c) |

There seems to be an error too regarding ElvUI and BetterWardrobe. I don't know if that is related to it.
![image](https://github.com/user-attachments/assets/456a334c-d25c-4a39-b637-b8dc6349d0e0)

**Comment by CRYPTfromCATACOMBZ** [comment]
Having the very same problem, i thought i accidentally pressed reset button or something ^^ Tried to put back my very old backup from 2023 and it worked, but the newest update let it broke

**Comment by zaphon** [comment]
Yeah, you also can't delete sets, I'm thinking this should have been marked BETA. :)

**Comment by Volchesta** [comment]
Yes, same problem here also, had to disable the addon.  I am sure it will be fixed soon!

**Comment by SLOKnightfall** [comment]
> Yeah, you also can't delete sets, I'm thinking this should have been marked BETA. :) I rolled back to 5.0.10.

Everything works fine for me, which is why it got released.
