### ISSUE TITLE
Typo in Wardrobe.lua breaks "View Sources"

### ISSUE THREAD

**Issue by andr-a** [SLOKnightfall/BetterWardrobe#478]
Got the following LUA error when clicking "View Sources":

`4x bad argument #1 to '?' (Usage: local itemModifiedAppearanceIDs = C_TransmogCollection.GetAllAppearanceSources(itemAppearanceID))
[string "=[C]"]: in function `GetAllAppearanceSources'
[string "@BetterWardrobe/Modules/Sources.lua"]:190: in function <BetterWardrobe/Modules/Sources.lua:180>
[string "@BetterWardrobe/Modules/Sources.lua"]:459: in function `GenerateSourceListView'
[string "@BetterWardrobe/Modules/Wardrobe.lua"]:3704: in function <BetterWardrobe/Modules/Wardrobe.lua:3703>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_Menu/Menu.lua"]:868: in function `Pick'
[string "@Blizzard_Menu/MenuTemplates.lua"]:74: in function <Blizzard_Menu/MenuTemplates.lua:68>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local itemModifiedAppearanceIDs = C_TransmogCollection.GetAllAppearanceSources(itemAppearanceID))"`

I found this line and removing the 'P' from the end fixed the issue.
https://github.com/SLOKnightfall/BetterWardrobe/blob/a74b7f4d5edb33c6cfc4e98f09b5c1b044f8f357/Modules/Wardrobe.lua#L3704

**Comment by SLOKnightfall** [comment]
Thanks.  Fixed in the next update
