### ISSUE TITLE
5.1 ElvUI/Core/Modules/Skins/Skins.lua:753: doesn't exist!

### ISSUE THREAD

**Issue by wiiittttt** [SLOKnightfall/BetterWardrobe#479]
36x ElvUI/Core/Modules/Skins/Skins.lua:753: doesn't exist!
[string "=[C]"]: ?
[string "@ElvUI/Core/Modules/Skins/Skins.lua"]:753: in function <ElvUI/Core/Modules/Skins/Skins.lua:752>
[string "=[C]"]: in function `HandleButton'
[string "@BetterWardrobe/Plugins/ElvUI.lua"]:172: in function <BetterWardrobe/Plugins/ElvUI.lua:41>
[string "@BetterWardrobe/Plugins/ElvUI.lua"]:330: in function `ApplyElvUISkin'
[string "@BetterWardrobe/Modules/Core.lua"]:1469: in function <BetterWardrobe/Modules/Core.lua:1457>

Locals:
(*temporary) = nil
(*temporary) = "doesn't exist!"

Possibly related to #454

**Comment by SLOKnightfall** [comment]
Fixed in the next update
