### ISSUE TITLE
Not an Issue but a request only

### ISSUE THREAD

**Issue by Galthariel** [SLOKnightfall/BetterWardrobe#48]
@SLOKnightfall 

First of all thanks for adding the Target Options Button but I was wondering if there is a way to split the button in 3 to make it easy and fast to choose from it. As I said not a big deal since you already added the option. I just think isn't friendly and fast but I'm OK if you can't change it 👍

**Comment by SLOKnightfall** [comment]
I'll see what can be done :)

**Comment by SLOKnightfall** [comment]
Buttons split in the prepatch update version.

**Comment by Galthariel** [comment]
Thank you so much :-)
