### ISSUE TITLE
Cannot Put on ANY Saved Sets

### ISSUE THREAD

**Issue by darbiirue** [SLOKnightfall/BetterWardrobe#480]
I'm having an issue on my Monk, specifically, where I cannot put on any saved sets at all. Whether they're on the Saved Tab or in the drop-down, I'm unable to select any of them. They all turn my attire invisible.

If I turn off Better Wardrobe, I'm then able to use any of my saved options from the drop-down, and any of the sets.

I've included a video here that should help show what's going on.

BugGrabber hasn't picked up any errors while doing this.

https://imgur.com/a/cw8osyP

**Comment by sabrinalilithblack** [comment]
Same issue. Goes away when disabling BW.

**Comment by darbiirue** [comment]
@sabrinalilithblack They just put out an addon update, it fixed the problem!
