### ISSUE TITLE
Gladiator sets missing when looking for sets

### ISSUE THREAD

**Issue by xDaney** [SLOKnightfall/BetterWardrobe#484]
this is currently the issue with every class, while looking for gladiator sets, half of them are missing beetwen season 12 and bfa s4
No lua errors
![изображение](https://github.com/user-attachments/assets/01c09366-c909-4773-bc4b-7ff3c1f8ddd8)

**Comment by SLOKnightfall** [comment]
It was being caused by an error in how faction sets were being filtered.  Fixed in the next update
