### ISSUE TITLE
Curious when next version will be released? 

### ISSUE THREAD

**Issue by jana8878** [SLOKnightfall/BetterWardrobe#49]
Wanting to know if you have an idea when the next version will be released. My whole guild uses it and we’ve been discussing it and how much we love the add on! 

Always be a supporter

**Comment by SLOKnightfall** [comment]
Version 1.11 just got released last night, so unless I need to push out a quick bug fix the next version probably will be next Tuesday to deal with all the prepatch updates.  Glad to hear that you and your guild like the addon, and please feel free to post any suggestions that you think that might make it even better.  :)
