### ISSUE TITLE
New saved sets only showing current gear and not saved items to that set

### ISSUE THREAD

**Issue by Melange20** [SLOKnightfall/BetterWardrobe#65]
Just updated this addon through Wowup.io. I've made 3 new saved sets in the past two days, but when I go back to look at the sets later by clicking on that set name, in the viewer it shows the current gear i'm wearing and not the items i saved as that set. Redid the sets again after the latest update today, still doing the same thing.

**Comment by SLOKnightfall** [comment]
There was a bug in the load saved set section that just got fixed, so you should be able to load sets properly after updating to the newest version.
