### ISSUE TITLE
Dressing room issues

### ISSUE THREAD

**Issue by Neurotoxin001** [SLOKnightfall/BetterWardrobe#69]
1. If you target NPC and press "Use target model" you will get 132 error and crash
2. Dressing room options don't load until I open appearances menu (because addon is "load on demand")
3. When I open dressing doom by clicking on items in character window (where all stats items etc (opening by "C" by default)) I have smaller version of dressing room and buttons is overlapping:
![image](https://user-images.githubusercontent.com/39812401/96224490-57f43580-0f98-11eb-8a01-3ab83de730b7.png)

v 2.0.6

**Comment by SLOKnightfall** [comment]
Items 1 & 3 are fixed in the next update.
Item 2:  Run the BetterWardrobe_Tooltips addon which will load BetterWardrobe
