### ISSUE TITLE
Conflict with BlizzMove addon

### ISSUE THREAD

**Issue by Neurotoxin001** [SLOKnightfall/BetterWardrobe#73]
When I open appearances tab and try to move it with addon [BlizzMove](https://github.com/the-rebel-Mermaid/BlizzMove) window become broken. With BetterWardrobe disabled all is fine. Idk where I must report it – to BlizzMove or here...

https://i.imgur.com/iwjNN5K.mp4

v 2.0.8

**Comment by SLOKnightfall** [comment]
Think i figured out what was causing the issue and should be fixed in the next version.
