### ISSUE TITLE
Blocking player's frames

### ISSUE THREAD

**Issue by Penaloppe** [SLOKnightfall/BetterWardrobe#76]
I did an Heroic Warfront the day after I installed this addon and I was unable to click on 3 character frame in my raid party (I was able to click on mine). The reason why I think it's your addon is because of the blizzard warning that opened each time I clicked on one of those 3 frames (see picture of the warning).
+
I marked with red line the three name I was not able to click. (Note that I was able to right click on them to whisper them, for exemple)

I understand that the pre-patch might not help.

Thank for your time and addon :D

![Capture](https://user-images.githubusercontent.com/73070909/96372795-a50e0e00-1136-11eb-81aa-0e09148f6e2b.PNG)
![Capture2](https://user-images.githubusercontent.com/73070909/96372796-a50e0e00-1136-11eb-8ed1-5faf671fa625.PNG)

**Comment by SLOKnightfall** [comment]
That's caused by UI taint from using the blizzard default menu api.  I'm currently in the process of redoing the menus to try to not be the addon listed in the error.
