### ISSUE TITLE
How do I remove the 'You havent collected this appearance' in the tooltips after uninstalling?

### ISSUE THREAD

**Issue by bunster** [SLOKnightfall/BetterWardrobe#80]
Uninstalled this mod because I didnt particularly care for it, but the 'You havent collected this appearance' text still shows on cloth, mail, and plate items for my rogue.

**Comment by SLOKnightfall** [comment]
use the following command in the game chat window to disable it 

`/run C_TransmogCollection.SetShowMissingSourceInItemTooltips(false)`
