### ISSUE TITLE
Request: Add checkbox to hide helm in previews in "Extra" tab

### ISSUE THREAD

**Issue by ascott18** [SLOKnightfall/BetterWardrobe#82]
Many of us generally always hide helm on all our transmogs. It would be nice when looking through the sets in the Extra tab to be able to have the same done there. Just something in the bottom left corner of the preview area that can be easily toggled on and off.

![image](https://user-images.githubusercontent.com/5017521/96658837-70e34a80-12fa-11eb-97d1-be92149cbed2.png)

**Comment by SLOKnightfall** [comment]
Thanks for the suggestion.  That should be something that I can add.

**Comment by SLOKnightfall** [comment]
This has been added to the next release.  There is now a button in the bottom left like in your image.  With that you can select what items you want to hide and toggle the view on/off.  A matching button was added to the transmog vendor so you can select slots to always get set to be hidden.
