### ISSUE TITLE
Constant LUA Errors 

### ISSUE THREAD

**Issue by DKDABU** [SLOKnightfall/BetterWardrobe#87]
I've had this addon installed for a few days at this point, but for some reason every time I'm on my survival hunter and use Harpoon I get:
"Message: ADDON_ACTION_BLOCKED: BetterWardrobe tried to call the protected function 'CompactRaidFrame1:Show()'.
Time: Wed Oct 21 19:48:13 2020
Count: 16
Stack: ADDON_ACTION_BLOCKED: BetterWardrobe tried to call the protected function 'CompactRaidFrame1:Show()'.
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\CompactUnitFrame.lua"]:375: in function `CompactUnitFrame_UpdateVisible'
[string "@Interface\FrameXML\CompactUnitFrame.lua"]:306: in function `CompactUnitFrame_UpdateAll'
[string "@Interface\FrameXML\CompactUnitFrame.lua"]:154: in function <Interface\FrameXML\CompactUnitFrame.lua:57>

Locals: <none>"

I've tried turning off some settings, but nothing seem to work.. 
Hope someone can help me figure out what isn't working for me.
Thanks

*Edit* I tried a few more characters with a charge to them, both my druid and warrior get the same Error, word for word.

**Comment by SLOKnightfall** [comment]
V2.3 should fix the issue
