### ISSUE TITLE
modifier right click (falsely) opens context menu

### ISSUE THREAD

**Issue by rml9ty** [SLOKnightfall/BetterWardrobe#91]
when you, for instance, ctrl right click the context menu (for right click) opens. I would like it to only open if you right click without any modifiers active.

when you use MogIt you often ctrl right click stuff to preview it and every time the context menu opens along side, which is super annoying.

when I explained it too badly I'll try to make a quick video tomorrow of what's happening. (:

**Comment by SLOKnightfall** [comment]
Should be fixed in the next update.  I also added a plugin for Mogit that makes ctrl right clicking of the extra and saved sets create mogit preview window now. :)
