### ISSUE TITLE
Conqueror's plate set is missing

### ISSUE THREAD

**Issue by palacode** [SLOKnightfall/BetterWardrobe#92]
Conqueror's plate set is missing items: here is fixed full set:

[349]={
    ["armorType"] =  4 ,
    ["label"] =  44 ,
    ["setID"] =  349 ,
    ["expansionID"] =  2 ,
    ["sources"] = { [25006] = 6553,[25007] = 6554,[25008] = 6555,[25009] = 6556,[25010] = 6557,[25011] = 6558,[25012] = 6526,[25013] = 6559, },
    ["maxLevel"] =  68 ,
    ["filter"] =  2 ,
    ["minLevel"] =  68 ,
    ["name"] =  "Conqueror's Plate" ,
    ["items"] = { 25006,25007,25008,25009,25010,25011,25012,25013, },

**Comment by SLOKnightfall** [comment]
Added to DB
