### ISSUE TITLE
unable to add (not yet learned) items to collections

### ISSUE THREAD

**Issue by rml9ty** [SLOKnightfall/BetterWardrobe#95]
not sure if this is intended or not, but I thought of collections of a sort of wishlist feature also.

by unable I mean that one is not able to right click items that have not been learned yet.

(btw is says "remove to collection" if you want to remove an item _from_ the collecton list. should be 'from', grammatically speaking :P)

**Comment by SLOKnightfall** [comment]
It should allow you to.  It looks like a change I made to make it play nicer with Mogit broke the feature.  It will be fixed in the next release that should be out later today.
