### ISSUE TITLE
LUA errors for a while now

### ISSUE THREAD

**Issue by Zaborg21** [SLOKnightfall/BetterWardrobe#98]
Hi, reporting some LUA errors I'm constantly getting:

`13x [ADDON_ACTION_BLOCKED] AddOn 'BetterWardrobe' tried to call the protected function 'CompactRaidFrame1:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\CompactUnitFrame.lua"]:375: in function `CompactUnitFrame_UpdateVisible'
[string "@FrameXML\CompactUnitFrame.lua"]:306: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML\CompactUnitFrame.lua"]:154: in function <FrameXML\CompactUnitFrame.lua:57>`

`1x ...ceBlizzard_Collections\Blizzard_Wardrobe.lua:1421: Usage: Script_GetAppearanceSourceInfo(sourceID, [optionalSlotID])
[string "=[C]"]: in function `GetAppearanceSourceInfo'
[string "@Blizzard_Collections\Blizzard_Wardrobe.lua"]:1421: in function <...ceBlizzard_Collections\Blizzard_Wardrobe.lua:1399>
[string "=[C]"]: in function `SetActiveSlot'
[string "@BetterWardrobe\Modules\CollectionList.lua"]:191: in function `Toggle'
[string "*:OnHide"]:1: in function <[string "*:OnHide"]:1>
[string "=[C]"]: in function `Hide'
[string "@FrameXML\UIParent.lua"]:2877: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2957: in function `HideUIPanel'
[string "@FrameXML\UIParent.lua"]:2610: in function <FrameXML\UIParent.lua:2602>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3477: in function `HideUIPanel'
[string "@FrameXML\UIParent.lua"]:2054: in function <FrameXML\UIParent.lua:1258>

Locals:
(*temporary) = nil
`

**Comment by SLOKnightfall** [comment]
Should be fixed in the next version
